<?php
  $server = "api.insparq.com";
  $apiVersion = "20120319";
  $url = (($_SERVER['SERVER_PORT'] != 443)? "http://" : "https://") . $server . '/api/v' . $apiVersion . '/key/' . $this->getPublisherId() . '/user?' . $this->getDataQueryString();
?>
 <div id="issw" data-issw-type="purchase" data-issw-widget-promotion-labels-primary="Share this with your friends!" data-issw-widget-buttons-display="&rdquo;ftpes&quot;" data-issw-dialogs-twitter-defaults-personal="Love this $1 from @MyTotsy!" data-issw-dialogs-pinterest-defaults-description="Love this $1 for [PRICE] from Totsy." data-issw-dialogs-email-labels-subject="I love Totsy! This is one of my favorites." data-issw-dialogs-email-defaults-personal="Hi there! I saw this on Totsy and thought you would like it. Have a look!" data-issw-dialogs-sms-defaults-personal="&rdquo;Check" this="" data-issw-capture-email="0" data-issw-text-dialog-success="Thanks for sharing!">
 </div>

    <script language="javascript" type="text/javascript">
  (function(d, t) {
        var match = decodeURIComponent(d.cookie).match(/\{"ut":"([^"]*)/);
        var ut = (match != null) ? match[1] : '';
        var url = '<?php echo $url; ?>&ut=' + ut;
        var g = d.createElement(t),
            s = d.getElementsByTagName(t)[0];
        g.type = 'text/javascript';
        g.async = true;
        g.src = url;
        s.parentNode.insertBefore(g, s);
      }(document, 'script'));
    </script>
