<?php
  $server = "api.insparq.com";
  $apiVersion = "20120319";
  $url = (($_SERVER['SERVER_PORT'] != 443)? "http://" : "https://") . $server . '/api/v' . $apiVersion . '/key/' . $this->getPublisherId() . '/user?' . $this->getDataQueryString();
?>
<script language="javascript" type="text/javascript">
      (function(d, t) {
		var match = decodeURIComponent(d.cookie).match(/\{"ut":"([^"]*)/);
		var ut = (match != null) ? match[1] : '';
        var url = '<?php echo $url; ?>&ut=' + ut;
        var g = d.createElement(t),
            s = d.getElementsByTagName(t)[0];
        g.type = 'text/javascript';
        g.async = true;
        g.src = url;
        s.parentNode.insertBefore(g, s);
      }(document, 'script'));
</script>
