<form id="hpcheckout-billing-form" action="">
    <ul class="form-list">
	    <li id="billing-new-address-form">
	        <ul>
	            <li class="fields">
	            	<div class="field half-of-half">
	            		<label class="required ui-input-text" for="billing:firstname" class="required"><?php echo $this->__('First Name') ?><span>*</span></label>
	                    <input type="text" name="billing[firstname]" title="<?php echo $this->__('First Name') ?>" class="inputbox ui-input-text ui-body-c ui-corner-all ui-shadow-inset input-text required-entry" value="<?php echo $this->htmlEscape($this->getFirstname()) ?>" id="billing:firstname" />
	            	</div>
	            	<div class="field half-of-half">
	            		<label for="billing:lastname" class="required ui-input-text"><em>*</em><?php echo $this->__('Last Name') ?></label>
	                    <input type="text" name="billing[lastname]" title="<?php echo $this->__('Last Name') ?>" class="inputbox ui-input-text ui-body-c ui-corner-all ui-shadow-inset input-text required-entry" value="<?php echo $this->htmlEscape($this->getLastname()) ?>" id="billing:lastname" />
	            	</div>
	            </li>
				<input type="hidden" name="billing[email]" id="billing:email" value="<?php echo $this->getCustomer()->getEmail() ?>" />
	            <!--li class="fields">
	            	<div class="field half-of-half">
		                <label for="billing:email" class="required ui-input-text"><em>*</em><?php echo $this->__('Email Address') ?></label>
		                <input type="text" name="billing[email]" id="billing:email" title="<?php echo $this->__('Email Address') ?>" class="ui-input-text ui-body-c ui-corner-all ui-shadow-inset input-text validate-email required-entry" value="<?php echo $this->htmlEscape($this->getAddress()->getEmail()) ?>" />
		            </div>
	            </li-->
	<input type="hidden" name="billing[selected]" id="billing:selected" />			
	            <li class="fields">
	                <div class="field half-of-half">
	                    <label for="billing:telephone" class="required ui-input-text"><em>*</em><?php echo $this->__('Telephone') ?></label>
	                    <input type="text" name="billing[telephone]" title="<?php echo $this->__('Telephone') ?>" class="input-text required-entry ui-input-text ui-body-c ui-corner-all ui-shadow-inset" id="billing:telephone" value="<?php echo $this->htmlEscape($this->getAddress()->getTelephone()) ?>" />
	                </div>
	            </li>
	            <li class="fields">
	            	<div class="field minus-padding half-of-half">
		                <label for="billing:street1" class="required ui-input-text"><em>*</em><?php echo $this->__('Street Address Line 1') ?></label>
		                <input type="text" title="<?php echo $this->__('Street Address Line 1') ?>" name="billing[street][0]" id="billing:street1" value="<?php echo $this->htmlEscape($this->getAddress()->getStreet(1)) ?>" class="ui-input-text ui-body-c ui-corner-all ui-shadow-inset input-text required-entry" />
	                </div>
	                <div class="field half-of-half">
	                	<label class="ui-input-text" for="billing:street2">&nbsp;&nbsp;<?php echo $this->__('Street Address Line 2') ?></label>
	                	<input type="text" title="<?php echo $this->__('Street Address Line 2') ?>" name="billing[street][1]" id="billing:street2" value="<?php echo $this->htmlEscape($this->getAddress()->getStreet(2)) ?>" class="ui-input-text ui-body-c ui-corner-all ui-shadow-inset input-text" />
	                </div>
	            </li>
	            <li class="fields"> 
	                <div class="field half-of-half">
	                    <label for="billing:city" class="ui-input-text required"><em>*</em><?php echo $this->__('City') ?></label>
	                    <input type="text" title="<?php echo $this->__('City') ?>" name="billing[city]" class="ui-input-text ui-body-c ui-corner-all ui-shadow-inset input-text required-entry" value="<?php echo $this->htmlEscape($this->getAddress()->getCity()) ?>" id="billing:city" />
	                </div>
	                <div class="field half-of-half">
	                    <label for="billing:region_id" class="required"><em>*</em><?php echo $this->__('State') ?></label>
						<div class="totsy-selective-input-box">
							<span>State</span>
							<select id="billing:region_id" name="billing[region_id]" title="<?php echo $this->__('State') ?>" class="validate-select" style="display:none;" >
								<option value=""><?php echo $this->__('Please select state') ?></option>
							</select>
						</div>
	                    <script type="text/javascript">
                        //<![CDATA[
                            $('billing:region_id').setAttribute('defaultValue',  "<?php echo $this->getAddress()->getRegionId() ?>");
                        //]]>
                        </script>
                        <input type="text" id="billing:region" name="billing[region]" value="<?php echo $this->htmlEscape($this->getAddress()->getRegion()) ?>"  title="<?php echo $this->__('State') ?>" class="input-text hidden-state ui-input-text ui-body-c ui-corner-all ui-shadow-inset" style="display:none;" />
	                </div>
	            </li>
	            <li class="fields">
	                <div class="field half-of-half">
	                    <label for="billing:postcode" class="ui-input-text required"><em>*</em><?php echo $this->__('Zip/Postal Code') ?></label>
	                    <input type="text" title="<?php echo $this->__('Zip/Postal Code') ?>" name="billing[postcode]" id="billing:postcode" class="ui-input-text ui-body-c ui-corner-all ui-shadow-inset input-text validate-zip-international required-entry" value="<?php echo $this->htmlEscape($this->getAddress()->getPostcode()) ?>" />
	                </div>
	                <div class="field half-of-half">
                        <label for="billing:country_id" class="ui-input-text required"><em>*</em><?php echo $this->__('Country') ?></label>
						<div class="totsy-selective-input-box totsy-selective-input-box-billing-country">
							<span>United States</span>
							<?php //echo $this->getCountryHtmlSelect('billing') ?>
							<select name="billing[country_id]" id="billing:country_id" class="validate-select" title="Country" ><option value="US" selected="selected" >United States</option></select>
						</div>
                    </div>
	            </li>
	        </ul>
	     </li>
    <?php if ($this->canShip()): ?>
        <li class="control">
            <button type="button" class="button button-exception" onclick="hpcheckout.copyBillingToShipping()"><div class="totsy-button-white"><?php echo  $this->__('SHIP TO THIS ADDRESS') ?></div></button>
        </li>
    <?php endif; ?>
    </ul>
</form>

<div class="spinner" style="display: none;"><img src="<?php echo $this->getSkinUrl( 'images/ajax-loader.gif' ) ?>"></div>

<script type="text/javascript">
//<![CDATA[
    var checkoutPayment = {};
    checkoutPayment.hasProfile = true;

    var billingRegionUpdater = new RegionUpdater('billing:country_id', 'billing:region', 'billing:region_id', countryRegions, undefined, 'billing:postcode');
//    var billingForm = new VarienForm('hpcheckout-billing-form');

    jQuery( document ).ready( function() {
    	jQuery("[id='billing:region']").val(jQuery("[id='billing:region_id'] option:selected").text());
    
		jQuery( '#billing-address-select' ).bind( 'change', hpcheckout.switchAddress );
    	//jQuery( '#billing\\:region_id, #billing\\:postcode' ).bind( 'change', hpcheckout.update );
//    	/jQuery( '#billing\\:postcode, #billing\\:country_id' ).bind( 'change', hpcheckout.update );
	});
	
	var hpcheckoutAddresses = <?php echo $this->getAddressesJson() ?>;
	
//]]>
</script>
