<div class="page-title">
    <h1><?php echo $this->__('Your order has been received') ?></h1>
</div>
<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<h2 class="sub-title"><?php echo $this->__('Thank you for your purchase!') ?></h2>

<?php if ($this->getOrderId()):?>
<?php 
	$orderIncrementId = $this->getOrderId();
	$order = Mage::getModel('sales/order')->loadByIncrementId($orderIncrementId);
	$quoteId = $order->getQuoteId();
	$quote = Mage::getModel('sales/quote')->load($quoteId);
	//$quote = Mage::getModel('checkout/cart')->getQuote();
	
?>
<?php if ($this->getCanViewOrder()) :?>
    <p><?php echo $this->__('Your order # is: %s.', sprintf('<a href="%s">%s</a>', $this->escapeHtml($this->getViewOrderUrl()), $this->escapeHtml($this->getOrderId()))) ?></p>
<?php  else :?>
    <p><?php echo $this->__('Your order # is: %s.', $this->escapeHtml($this->getOrderId())) ?></p>
<?php endif;?>
    <p><?php echo $this->__('You will receive an order confirmation email with details of your order and a link to track its progress.') ?></p>
<?php if ($this->getCanViewOrder() && $this->getCanPrintOrder()) :?>
    <p>
       
        <?php echo $this->getChildHtml() ?>
    </p>
	<p class="red review-order-detail">
    	<?php 		
    		$order_id = $order->getId();
			$url = $this->getBaseUrl().'sales/order/history/';
		?>
		You will redirect to orders review page in 5 second. Or <a class="red" href="<?php echo $url?>">click here</a>
    </p>
    <script language="javascript" type="text/javascript">
		function redirect(){window.location.href="<?php echo $url?>"};
		setTimeout("redirect()",5000);
	</script>
	<?php 
		$coupon = $order->getCouponCode();
		$couponStr = isset($coupon)?"&promocode=".$order->getCouponCode():"";
 		echo "<img src='http://api.theechosystem.com/Core/Conversion/Save?echoTrackPack=".($_COOKIE['EchoTrackPack']."&revenue=".$order->getData('grand_total')."&quantity=".$quote->getItemsQty().$couponStr."&orderId=".$order->getId()."' style='width:1px;height:1px;' />");
	?> 
<?php endif;?>
<?php endif;?> 

<script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', <?php echo Mage::getStoreConfig("google/analytics/account")?>);  
  _gaq.push(['_trackPageview']);
  _gaq.push(['_addTrans',
    '<?php echo $order->getData('increment_id'); ?>',           // order ID - required
    'Totsy',  // affiliation or store name
    '<?php echo $order->getData('grand_total'); ?>',          // total - required
    '<?php echo $order->getData('tax_amount'); ?>',           // tax
    '<?php echo $order->getData('shipping_amount'); ?>',              // shipping
    '<?php echo $order->getShippingAddress()->getData('city')?>',       // city
    '<?php echo $order->getShippingAddress()->getData('region')?>',     // state or province
    'USA'             // country
  ]);
	<?php 
	$category = array();
//	$productid = Mage::getModel('catalog/product')->getData('category_ids');
//	$order  = Mage::getModel('catalog/category')->getCollection()->load($productid);
	foreach($order->getAllItems() as $item):?>
	<?php 	if( !! $item->getParentItemId() ) {
			continue;
		}
		unset($category);
		$product = Mage::getModel( 'catalog/product' )->load( $item->getProductId() );
		$categoryIds = $product->getCategoryIds();
		foreach ($categoryIds as $cateId){
			$category[] = Mage::getModel('catalog/category')->load($cateId)->getData('name');
		}
	?>

   // add item might be called for every item in the shopping cart
   // where your ecommerce engine loops through each item in the cart and
   // prints out _addItem for each
  _gaq.push(['_addItem',
    '<?php echo $order->getData('increment_id'); ?>',           // order ID - required
    '<?php echo $item->getData('sku'); ?>',           // SKU/code - required
    '<?php echo $item->getData('name')?>',        // product name
    '<?php foreach($category as $cat){
    	echo $cat.',';
    } ?>',   // category or variation
    '<?php echo $item->getPrice() ?>',          // unit price - required
    '<?php echo $item->getQtyOrdered() ?>'               // quantity - required
  ]);
  <?php   		
  endforeach;
  ?>
  _gaq.push(['_trackTrans']); //submits transaction to the Analytics servers

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>