<?php /* @var $this Litle_Palorus_Block_Vault_List */ ?><?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<div class="page-header">
    <h2><?php echo $this->__('Manage Credit Cards') ?> <img class="cart-type pull-right"  width="180px;" src="<?php echo $this->getSkinUrl('images/creditcards.jpg')?>"/></h2>
</div>
<div class="well">
    <div class="page-title">
        <h4>My Credit Cards <button onclick="location.href='<?php echo $this->getAddUrl() ?>';" class="add-new-card-button btn btn-primary pull-right">Add New Card</button>
            <button class="add-new-card-close btn pull-right add-new-card-form" style="display:none;">Close</button>
        </h4>
        <hr />
    </div>
    <?php $cards = $this->getStoredCards() ?>
    <?php if (count($cards)): ?>
        <div class="cards-info">
            <?php foreach($cards as $card): ?>
                <table class="table table-striped table-bordered">
                    <?php if ($card): ?>
                        <tr>
                            <td><img src="<?php echo $this->getSkinUrl('images/cc_' . strtolower(str_replace(' ','_',$card->getTypeName())) . '.gif'); ?>"> </td>
                            <td width="71%">
                                <?php echo $card->getTypeName(); ?> ending in <strong><?php echo $card->getLast4(); ?></strong>
                                expires <strong><?php echo $card->getData('expiration_month');?>/<?php echo $card->getData('expiration_year');?></strong>
                            </td>
                            <td width="2%">
                                <a href="#" onclick="return deleteCard('<?php echo $card->getId() ?>');" id="remove_<?php echo $card->getId(); ?>" title="Remove Credit Card" class="delete-new-card-button btn">Delete</a>
                            </td>
                        </tr>
                        <?php if($card->getData('address_id')):?>
                            <?php $address = Mage::getModel('customer/address')->load($card->getData('address_id')); ?>
                            <?php if($address->getFirstname()):?>
                                <tr>
                                    <td width="10%" align="left"></td>
                                    <td width="90%">
                                        <table class="table table-condensed">
                                            <tr>
                                                <td width="141" valign="top">Cardholder Name:</td>
                                                <td width="281"><?php echo $address->getFirstname(); ?> <?php echo $address->getLastname(); ?></td>
                                            </tr>
                                            <tr>
                                                <td valign="top">Billing Address:</td>
                                                <td><?php echo $address->getStreet(1); ?>
                                                    <?php if($address->getStreet(2)): ?>
                                                        <?php echo $address->getStreet(2); ?><br />
                                                    <?php endif ?>
                                                    <?php echo $address->getCity(); ?>, <?php $address->getRegion(); ?> <?php echo $address->getPostcode(); ?>
                                                </td>
                                            </tr>
                                        </table>
                                    </td>
                                </tr>
                            <?php endif; ?>
                        <?php endif; ?>
                    <?php endif; ?>
                </table>
            <?php endforeach; ?>
        </div>
    <?php else: ?>
        <li class="item empty">
            <p><?php echo $this->__('You have no stored credit cards.') ?></p>
        </li>
    <?php endif ?>
</div>
<script type="text/javascript">
    //<![CDATA[
    function deleteCard (cardId) {
        if (confirm('<?php echo $this->__('Are you sure you want to delete this profile?') ?>')) {
            window.location='<?php echo $this->getDeleteUrl() ?>vault_id/' + cardId;
        }
        return false;
    }
    //]]>
</script>
<style type="text/css">
    .info-box { float: left; width: 48%; margin-right: 2%; }
    .info-box:nth-child(even) { float: right; margin-right: 0; }
    .info-box dl { margin: 10px 17px 17px; }
    .info-box dt { float: left; clear: left; width: 30%; margin-right: 5%; font-weight: bold; }
    .info-box dd { float: left; width: 65%; }
    p.actions { clear: both; padding: 10px 17px 17px; }
</style>
