<?php
/**
 * Harapartners
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Harapartners License
 * that is bundled with this package in the file LICENSE_EE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.Harapartners.com/license
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@Harapartners.com so we can send you a copy immediately.
 *
 */
?>
<?php
	$welcomeInfo = '';
	$customer = Mage::getSingleton('customer/session')->getCustomer();
	$customerName = $customer->getFirstname();
	if ( !empty($customerName) ){
		$welcomeInfo = $customerName;
	}else {
		$welcomeInfo = $customer->getEmail();
	}
?>

	<strong><?php echo $this->__( 'Hi, %s ', $welcomeInfo );?></strong>
	<ul class="links">
		<li class="first">
			<a title="Log Out" onclick="logout()" style="cursor:pointer"><?php echo $this->__('Sign Out');?></a>
		</li>
		<li>
			<a title="My Account" href="<?php echo Mage::getUrl('customer/account')?>"><?php echo $this->__('My Account');?></a>
		</li>
	</ul>

	
