<form id="hpcheckout-billing-form" action="">
    <div id="billing-new-address-form">
        <div>
            <input type="text" name="billing[firstname]" title="<?php echo $this->__('First Name') ?>" class="span3 required-entry validate-alpha" value="<?php echo $this->htmlEscape($this->getFirstName()) ?>" placeholder="<?php echo $this->__('First Name') ?>" id="billing:firstname">
            <div class="span3">
                <input type="text" name="billing[lastname]" title="<?php echo $this->__('Last Name') ?>" class="span3 required-entry validate-alpha" value="<?php echo $this->htmlEscape($this->getLastName()) ?>" placeholder="<?php echo $this->__('Last Name') ?>" id="billing:lastname">
            </div>
        </div>
        <div class="controls controls-row">
            <input type="hidden" name="billing[email]" id="billing:email" value="<?php echo $this->getCustomer()->getEmail() ?>"> 
            <input type="hidden" name="billing[selected]" id="billing:selected">
            <input type="text" title="<?php echo $this->__('Street Address Line 1') ?>" name="billing[street][0]" id="billing:street1" value="<?php echo $this->getAddress()->getStreet(1) ?>" class="span6 required-entry" placeholder="<?php echo $this->__('Street Address Line 1') ?>">
        </div>
        <div class="controls controls-row">
            <input type="text" title="<?php echo $this->__('Street Address Line 2') ?>" name="billing[street][1]" id="billing:street2" value="<?php echo $this->getAddress()->getStreet(2) ?>" class="span6" placeholder="<?php echo $this->__('Street Address Line 2') ?>">
        </div>
        <div class="controls controls-row">
            <div class="clearfix">
        	   <input type="text" title="<?php echo $this->__('Zip Code') ?>" name="billing[postcode]" id="billing:postcode" class="span1 validate-zip required-entry" value="<?php echo $this->getAddress()->getPostcode() ?>" placeholder="<?php echo $this->__('Zip') ?>">
               <div id="billing_zip_info_message" class="span5" style="display:none">
                   Enter a ZIP for City and State
               </div>
                <div id="billing_city_and_state">
                    <div class="span3">
                        <input type="text" title="<?php echo $this->__('City') ?>" name="billing[city]" class="span3 required-entry" value="<?php echo $this->getAddress()->getCity() ?>" placeholder="<?php echo $this->__('City') ?>" id="billing:city">
                    </div>
                    <div class="span2">
                        <select id="billing:region_id" name="billing[region_id]" title="<?php echo $this->__('State') ?>" class="span2 validate-select state">
                            <option value="">
                                <?php echo $this->__('Please select state') ?>
                            </option>
                        </select>
                    </div>
                    <script type="text/javascript">
                        $('billing:region_id').setAttribute('defaultValue', "<?php echo $this->getAddress()->getRegionId() ?>");
                    </script> 
                    <input type="text" id="billing:region" name="billing[region]" value="<?php echo $this->htmlEscape($this->getAddress()->getRegion()) ?>" title="<?php echo $this->__('State/Province') ?>" class="span1 hidden-state" style="display:none;">
                </div>
            </div>
        </div>
        <div class="controls controls-row">
                <input type="text" name="billing[telephone]" title="<?php echo $this->__('Telephone') ?>" class="span2 required-entry validate-phoneLax" id="billing:telephone" value="<?php echo $this->htmlEscape($this->getAddress()->getTelephone()) ?>" placeholder="Telephone">
            <?php if(!$this->getQuote()->isVirtual() ): ?>
            <div class="span3">
                <input type="checkbox" id="button_ship_to" class="span1 btn ship-to-billing" onclick="hpcheckout.copyBillingToShipping()">
                <label class="span3">SHIP TO THIS ADDRESS</label>
            </div>
            <?php endif; ?>
            <div style="display:none">
                <?php echo $this->getCountryHtmlSelect('billing') ?>
            </div>
        </div>
    </div>
</form>
<div class="spinner" style="display: none;">
    <img src="<?php echo $this->getSkinUrl( 'images/ajax-loader.gif' ) ?>">
</div>
<script type="text/javascript">
	// @TODO: abstract this out to hpcheckout.js as self-contained method
// need to re-enable billing form controls before trying to send values to shipping form
jQuery(document).ready(function() {
	checkoutPayment.getCityAndStateByZip("billing");
	if (typeof checkoutPayment !== "undefined") {
		if (checkoutPayment.hasProfile == true && checkoutPayment.lastUsedAddressId !== "") {
			jQuery("#billing-address-select").val(checkoutPayment.lastUsedAddressId);
		}
	}
	if (jQuery("#billing-address-select").length > 0) {
		if (checkoutPayment.hasProfile == false && jQuery("#billing-address-select").val() !== "") {
			jQuery("#billing-address-select").attr("disabled", false);
			checkoutPayment.disableAddress(true, 'hpcheckout-billing-form');
		}
	}
	jQuery('#button_ship_to').bind('click', function() {
		var billAddySelect = jQuery("#billing-address-select");
		// re-enable disabled controls
		if (billAddySelect.length > 0) {
			if (billAddySelect.val() !== "") {
				billAddySelect.attr('disabled', false);
				checkoutPayment.disableAddress(false, 'hpcheckout-billing-form');
			}
		}
		// then use hpcheckout.copyBillingToShipping() method
		hpcheckout.copyBillingToShipping();
		checkoutPayment.getCityAndStateByZip("billing");
		if (billAddySelect.length > 0) {
			if (billAddySelect.val() !== "") {
				//if the user has a card on file, disable to ability to edit the billing address
				//NOTE: a user may have a saved billing address and NO card on file, in that case, the address dropdown should be enabled
				if (checkoutPayment.hasProfile == 1) {
					billAddySelect.attr('disabled', true);
				}
				//if there's an address selected in the dropdown, disable the address form
				checkoutPayment.disableAddress(true, 'hpcheckout-billing-form');
			}
		}
		//blank out the shipping address dropdown when it's not blank
		if (jQuery("#shipping-address-select").val() !== "") {
			jQuery("#shipping-address-select").val("");
		}
	});
	if (jQuery('#billing-address-select').length > 0) {
		jQuery('#billing-address-select').bind('change', function() {
			if (jQuery('#billing-address-select').val() == "") {
				checkoutPayment.disableAddress(false, 'hpcheckout-billing-form');
			} else {
				checkoutPayment.disableAddress(true, 'hpcheckout-billing-form');
			}
			hpcheckout.switchAddress(this.id);
		});
	}
});

var billingRegionUpdater = new RegionUpdater('billing:country_id', 'billing:region', 'billing:region_id', countryRegions, undefined, 'billing:postcode');
    <?php if($this->getAddressesJson()) { ?>
              var hpcheckoutAddresses = <?php echo $this->getAddressesJson() ?>;
    <?php }  ?>
</script>