<form id="hpcheckout-billing-form" action="">
	    <div id="billing-new-address-form fields alpha">
	    	    <div > 
	    		    <div class="pull-left field half-of-half">
	    	           <label for="billing:firstname" class="required"><em>*&nbsp;</em><?php echo $this->__('first name') ?></label>
	    	           <input type="text" name="billing[firstname]" title="<?php echo $this->__('First Name') ?>" class="input-text required-entry firstname" value="<?php echo $this->htmlEscape($this->getFirstname()) ?>" id="billing:firstname" />
	    	        </div>
	    	        <div class="field half-of-half">
	    	            <label for="billing:lastname" class="required"><em>*&nbsp;</em><?php echo $this->__('last name') ?></label>
	    	            <input type="text" name="billing[lastname]" title="<?php echo $this->__('Last Name') ?>" class="input-text required-entry lastname" value="<?php echo $this->htmlEscape($this->getLastname()) ?>" id="billing:lastname" />
	    	        </div>
	    	    </div>
	    	    <input type="hidden" name="billing[email]" id="billing:email" value="<?php echo $this->getCustomer()->getEmail() ?>" />
	    	    <input type="hidden" name="billing[selected]" id="billing:selected" />
	    	    <!-- li class="fields">
	    	        <div class="field half-of-half">
			            <span for="billing:email" class="required"><em>*</em><?php echo $this->__('Email Address') ?></span>
			            <input type="text" name="billing[email]" id="billing:email" title="<?php echo $this->__('Email Address') ?>" class="input-text validate-email required-entry" value="<?php echo $this->htmlEscape($this->getAddress()->getEmail()) ?>" />
			        </div>
	    	    </div-->
	    	    <div >
	    	        <div class="pull-left field half-of-half">
	    	            <label for="billing:telephone" class="required"><em>*&nbsp;</em><?php echo $this->__('telephone') ?></label>
	    	            <input type="text" name="billing[telephone]" title="<?php echo $this->__('Telephone') ?>" class="input-text required-entry validate-phoneLax telephone" id="billing:telephone" value="<?php echo $this->htmlEscape($this->getAddress()->getTelephone()) ?>" onkeyup="backspacerUP(this,event);" onkeydown="backspacerDOWN(this,event);"/>
	    	        </div>
	    	     </div> 
	    	     <div >
	    	         <div class="field half-of-half">
			            <label for="billing:street1" class="required"><em>*&nbsp;</em><?php echo $this->__('street address line 1') ?></label>
			            <input type="text" title="<?php echo $this->__('Street Address Line 1') ?>" name="billing[street][0]" id="billing:street1" value="<?php echo $this->htmlEscape($this->getAddress()->getStreet(1)) ?>" class="input-text required-entry streetaddress1" />
	    	        </div>
	    	     </div>
	    	     <div >
	    	         <div class="pull-left field half-of-half">
	                   <label for="billing:street2">&nbsp;<?php echo $this->__('street address line 2') ?></label>
	                   <input type="text" title="<?php echo $this->__('Street Address Line 2') ?>" name="billing[street][1]" id="billing:street2" value="<?php echo $this->htmlEscape($this->getAddress()->getStreet(2)) ?>" class="input-text streetaddress2" />
	                 </div>
	    	     </div>
	    	     <div > 
                     <div class=" pull-left field half-of-half">
	                     <label for="billing:city" class="required"><em>*&nbsp;</em><?php echo $this->__('city') ?></label>
	                     <input type="text" title="<?php echo $this->__('City') ?>" name="billing[city]" class="input-text required-entry city" value="<?php echo $this->htmlEscape($this->getAddress()->getCity()) ?>" id="billing:city" />
	                 </div>	 
	                 <div class="field half-of-half">
	                     <label for="billing:region_id" class="required"><em>*&nbsp;</em><?php echo $this->__('state') ?></label>
		                 <div class="totsy-selective-input-box">
		                     <select id="billing:region_id" name="billing[region_id]" title="<?php echo $this->__('State') ?>" class="validate-select state" style="display:none;" >
		                       <option value=""><?php echo $this->__('Please select state') ?></option>
		                     </select>
		                 </div>
	                     <script type="text/javascript">
                            $('billing:region_id').setAttribute('defadivtValue',  "<?php echo $this->getAddress()->getRegionId() ?>");
                         </script>
                         <input type="text" id="billing:region" name="billing[region]" value="<?php echo $this->htmlEscape($this->getAddress()->getRegion()) ?>"  title="<?php echo $this->__('State/Province') ?>" class="input-text hidden-state" style="display:none;" />
	                  </div>
	              </div>
	              <div >
	                  <div class="pull-left field half-of-half">
	                      <label for="billing:postcode" class="required"><em>*&nbsp;</em><?php echo $this->__('zip/postal code') ?></label>
	                      <input type="text" title="<?php echo $this->__('Zip/Postal Code') ?>" name="billing[postcode]" id="billing:postcode" class="input-text validate-zip required-entry zip" value="<?php echo $this->htmlEscape($this->getAddress()->getPostcode()) ?>" />
	                  </div>
	                 <div class="field half-of-half">
                         <label for="billing:country_id" class="required"><em>*&nbsp;</em><?php echo $this->__('country') ?></label>
			             <div class="totsy-selective-input-box totsy-selective-input-box-billing-country country">
			             	<?php echo $this->getCountryHtmlSelect('billing') ?>
			             </div>
                     </div>
                 </div>
            </div>
</form>

<div class="spinner" style="display: none;"><img src="<?php echo $this->getSkinUrl( 'images/ajax-loader.gif' ) ?>"></div>

<script type="text/javascript">
//<![CDATA[
    var billingRegionUpdater = new RegionUpdater('billing:country_id', 'billing:region', 'billing:region_id', countryRegions, undefined, 'billing:postcode');
//    var billingForm = new VarienForm('hpcheckout-billing-form');
    jQuery( document ).ready( function() {
        jQuery( '#billing-address-select' ).bind( 'change', hpcheckout.switchAddress );
    	//jQuery( '#billing\\:region_id, #billing\\:postcode' ).bind( 'change', hpcheckout.update );
//    	/jQuery( '#billing\\:postcode, #billing\\:country_id' ).bind( 'change', hpcheckout.update );
	});

	var hpcheckoutAddresses = <?php echo $this->getAddressesJson() ?>;
</script>