<form id="hpcheckout-billing-form" action="">
	    <div id="billing-new-address-form fields alpha">
	    	    <div> 
	    		    <div class="pull-left">
	    	           <label for="billing:firstname" class="required"><em>*&nbsp;</em><?php echo $this->__('first name') ?></label>
	    	     <input type="text" name="billing[firstname]" title="<?php echo $this->__('First Name') ?>" class="input-text required-entry firstname validate-alpha"  value="<?php echo $this->htmlEscape($this->getFirstName()) ?>" placeholder="<?php echo $this->__('First Name') ?>" id="billing:firstname" />
	    	        </div>
	    	        <div>
	    	            <label for="billing:lastname" class="required"><em>*&nbsp;</em><?php echo $this->__('last name') ?></label>
	    	            <input type="text" name="billing[lastname]" title="<?php echo $this->__('Last Name') ?>" class="input-text required-entry lastname validate-alpha" value="<?php echo $this->htmlEscape($this->getLastName()) ?>" placeholder="<?php echo $this->__('Last Name') ?>" id="billing:lastname" />
	    	        </div>
	    	    </div>
	    	    <input type="hidden" name="billing[email]" id="billing:email" value="<?php echo $this->getCustomer()->getEmail() ?>" />
	    	    <input type="hidden" name="billing[selected]" id="billing:selected" />
	    	     <div>
	    	         <div>
			            <label for="billing:street1" class="required"><em>*&nbsp;</em><?php echo $this->__('street address line 1') ?></label>
			            <input type="text" title="<?php echo $this->__('Street Address Line 1') ?>" name="billing[street][0]" id="billing:street1" value="<?php echo $this->getAddress()->getStreet(1) ?>" class="input-text required-entry streetaddress1" placeholder="<?php echo $this->__('Street Address Line 1') ?>" />
	    	        </div>
	    	     </div>
	    	     <div>
	    	         <div class="pull-left">
	                   <label for="billing:street2">&nbsp;<?php echo $this->__('street address line 2') ?></label>
	                   <input type="text" title="<?php echo $this->__('Street Address Line 2') ?>" name="billing[street][1]" id="billing:street2" value="<?php echo $this->getAddress()->getStreet(2) ?>" class="input-text streetaddress2" placeholder="<?php echo $this->__('Street Address Line 2') ?>"/>
	                 </div>
	    	     </div>
	    	     <div>
	    	         <div class="pull-left">
	                     <label for="billing:city" class="required"><em>*&nbsp;</em><?php echo $this->__('city') ?></label>
	                     <input type="text" title="<?php echo $this->__('City') ?>" name="billing[city]" class="input-text required-entry city" value="<?php echo $this->getAddress()->getCity() ?>" placeholder="<?php echo $this->__('City') ?>" id="billing:city" />
	                 </div>	 
	    	     	 <div class="pull-left">
	                     <label for="billing:region_id" class="required"><em>*&nbsp;</em><?php echo $this->__('state') ?></label>
		                 <div class="totsy-selective-input-box">
		                     <select id="billing:region_id" name="billing[region_id]" title="<?php echo $this->__('State') ?>" class="validate-select state" >
		                       <option value=""><?php echo $this->__('Please select state') ?></option>
		                     </select>
		                 </div>
	                     <script type="text/javascript">
                            $('billing:region_id').setAttribute('defaultValue',  "<?php echo $this->getAddress()->getRegionId() ?>");
                         </script>
                         <input type="text" id="billing:region" name="billing[region]" value="<?php echo $this->htmlEscape($this->getAddress()->getRegion()) ?>"  title="<?php echo $this->__('State/Province') ?>" class="input-text hidden-state" style="display:none;" />
	                  </div>
	                  <div>
	                      <label for="billing:postcode" class="required"><em>*&nbsp;</em><?php echo $this->__('zip/postal code') ?></label>
	                      <input type="text" title="<?php echo $this->__('Zip Code') ?>" name="billing[postcode]" id="billing:postcode" class="input-text validate-zip required-entry zip" value="<?php echo $this->getAddress()->getPostcode() ?>" placeholder="<?php echo $this->__('Zip/Postal Code') ?>" />
	                  </div>
	              </div>
	              <div class="last-billing-form-row">
	    	          <div class="field pull-left">
	    	        	    <label for="billing:telephone" class="required"><em>*&nbsp;</em><?php echo $this->__('telephone') ?></label>
	    	        	    <input type="text" name="billing[telephone]" title="<?php echo $this->__('Telephone') ?>" class="input-text required-entry validate-phoneLax telephone" id="billing:telephone" value="<?php echo $this->htmlEscape($this->getAddress()->getTelephone()) ?>" placeholder="Telephone"/>
	    	        	</div>
	    	         </div>
	    	         <div>
						<?php if( ! $this->getQuote()->isVirtual() ): ?>
                 		<button type="button" id="button_ship_to" class="button button-exception ship-to-billing btn" onclick="hpcheckout.copyBillingToShipping()">
                 			<div class="totsy-button-white"><?php echo  $this->__('SHIP TO THIS ADDRESS') ?></div>
                 		</button>
						<?php endif; ?>
                 	</div> 
	                 <div>
                         <label for="billing:country_id" class="required"><em>*&nbsp;</em><?php echo $this->__('country') ?></label>
			             <div class="totsy-selective-input-box totsy-selective-input-box-billing-country country">
			             	<?php echo $this->getCountryHtmlSelect('billing') ?>
			             </div>
                     </div>
                 </div>
</form>

<div class="spinner" style="display: none;"><img src="<?php echo $this->getSkinUrl( 'images/ajax-loader.gif' ) ?>"></div>
<script type="text/javascript">
	// @TODO: abstract this out to hpcheckout.js as self-contained method
	// need to re-enable billing form controls before trying to send values to shipping form
	jQuery(document).ready( function() {
        if(typeof checkoutPayment!=="undefined") {
            if(checkoutPayment.hasProfile==true && checkoutPayment.lastUsedAddressId!=="") {
                jQuery("#billing-address-select").val(checkoutPayment.lastUsedAddressId);
            }
            if(jQuery( '#billing-address-select' ).length>0){
                if(checkoutPayment.hasProfile==false) {
                    jQuery("#billing-address-select").attr("disabled", false);
                    checkoutPayment.disableAddress(true, 'hpcheckout-billing-form');
                }
            }
	        jQuery('#button_ship_to').bind('click', function() {
	        	var billAddySelect = jQuery("#billing-address-select");
	        	// re-enable disabled controls
	        	if( billAddySelect.length > 0 ){
	        	    if ( billAddySelect.val()!=="" ) {
	                    billAddySelect.attr('disabled', false);
	                    checkoutPayment.disableAddress(false,'hpcheckout-billing-form');
	        	    }
	        	}
	        	// then use hpcheckout.copyBillingToShipping() method
	        	hpcheckout.copyBillingToShipping();
	        	if(billAddySelect.length > 0 ){
	        	    if (billAddySelect.val() !== "") {
	        	        //if the user has a card on file, disable to ability to edit the billing address
	        	    	//NOTE: a user may have a saved billing address and NO card on file, in that case, the address dropdown should be enabled
	        	    	if(checkoutPayment.hasProfile==1) {
	                        billAddySelect.attr('disabled', true);
	                    }
	                    //if there's an address selected in the dropdown, disable the address form
	                    checkoutPayment.disableAddress(true,'hpcheckout-billing-form');
	        	    }
	        	}
	        	//blank out the shipping address dropdown when it's not blank
	        	if (jQuery("#shipping-address-select").val()!=="") {
	                jQuery("#shipping-address-select").val("");
	        	}
	        });
	        if( jQuery( '#billing-address-select' ).length >0 ) {
	           jQuery( '#billing-address-select' ).bind( 'change', function(){ 
	               if(jQuery( '#billing-address-select' ).val()=="") {
	                   checkoutPayment.disableAddress(false,'hpcheckout-billing-form');
	               } else {
	                   checkoutPayment.disableAddress(true,'hpcheckout-billing-form');
	               }
	               hpcheckout.switchAddress(this.id); 
	           });
	        }
        }
    });
//<![CDATA[
    var billingRegionUpdater = new RegionUpdater('billing:country_id', 'billing:region', 'billing:region_id', countryRegions, undefined, 'billing:postcode');

    <?php if($this->getAddressesJson()) { ?>
              var hpcheckoutAddresses = <?php echo $this->getAddressesJson() ?>;
    <?php }  ?>
    
</script>