<div class="hpcheckout-methods">
    <?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
    <form id="login-form" action="<?php echo $this->getPostAction() ?>" method="post">
    	<!--input type="radio" name="checkout_method" id="login-method" value="login" class="radio" checked="checked" /><label for="login"><?php echo $this->__('Login') ?><span class="seperator">/</span><a href="<?php echo $this->getUrl('customer/account/create')?>">Register</a></label-->
    	<div id="login-method"><span class="login-text"><?php echo $this->__('Login') ?></span><span class="seperator">/</span><a href="<?php echo $this->getUrl('customer/account/create')?>">Register</a></div>
	    <div id="login-form-wrapper" style="display: none;">
		    <label for="login-email" class="required"><em>*</em><?php echo $this->__('Email Address') ?></label>
		    <input type="text" class="input-text required-entry validate-email" id="login-email" name="login[username]" value="<?php echo $this->htmlEscape($this->getUsername()) ?>"/>
		    <label for="login-password" class="required"><em>*</em><?php echo $this->__('Password') ?></label>
		    <input type="password" class="input-text required-entry" id="login-password" name="login[password]" />
	    	<a href="<?php echo $this->getUrl('customer/account/forgotpassword') ?>"><?php echo $this->__('Forgot your password?') ?></a>
	    	<button type="button" onclick="onepageLogin(this)"><?php echo $this->__('Login') ?></button>
	    </div>
        <?php if( false && $this->getQuote()->isAllowedGuestCheckout() ): ?>
        	<div class="guest-checkout-wrapper">
				<!--input type="radio" name="checkout_method" id="guest-method" value="guest" class="radio" /><label for="guest"><?php echo $this->__('Checkout as Guest') ?></label-->
				<span id="guest-method"><?php echo $this->__('Checkout as Guest') ?></span>
			</div>
	 	<?php endif; ?>
    </form>
</div> 
<script type="text/javascript">
//<![CDATA[
    var loginForm = new VarienForm('login-form', true);
    $('login-email').observe('keypress', bindLoginPost);
    $('login-password').observe('keypress', bindLoginPost);
    function bindLoginPost(evt){
        if (evt.keyCode == Event.KEY_RETURN) {
            loginForm.submit();
        }
    }
    function onepageLogin(button)
    {
        if(loginForm.validator && loginForm.validator.validate()){
            button.disabled = true;
            loginForm.submit();
        }
    }
    
    jQuery( document ).ready( function() {
    	jQuery( '#login-method .login-text' ).click( function() {
			jQuery( '#login-form-wrapper' ).toggle();
        });
    });
//]]>
</script>