<form action="" id="hpcheckout-payment-form">
    	<?php //echo $this->getChildChildHtml('methods_additional') ?>
        <?php echo $this->getChildHtml('methods') ?>
        <?php //echo $this->getChildHtml( 'customerbalance' ) ?>
</form>

<div class="spinner" style="display: none;"><img src="<?php echo $this->getSkinUrl( 'images/ajax-loader.gif' ) ?>"></div>

<script type="text/javascript">
	//var paymentForm = new VarienForm( 'hpcheckout-payment-form', true );
	
	jQuery( document ).ready( function() {
		//jQuery( '#payment-select' ).bind( 'change', hpcheckout.update );
		//jQuery( '#hpcheckout-payment-select' ).bind( 'change', hpcheckout.update );
	});
</script>
