    <script src="https://cert01.securepaypage.litle.com/LitlePayPage/litle-api.js"
            type="text/javascript"></script>
    <script>
        $(document).ready(
                function(){
                    function setLitleResponseFields(response) {
                        document.getElementById('response$code').value = response.response;
                        document.getElementById('response$message').value = response.message;
                        document.getElementById('response$responseTime').value = response.responseTime;
                        document.getElementById('response$litleTxnId').value = response.litleTxnId;
                        document.getElementById('response$type').value = response.type;
                    }
                    function submitAfterLitle (response) {
                        setLitleResponseFields(response);
                        document.forms['fCheckout'].submit();
                    }
                    function timeoutOnLitle () {
                        alert("We are experiencing technical difficulties.  Please try again later or call 555-555-1212 (timeout)");
                    }
                    function onErrorAfterLitle (response) {
                        setLitleResponseFields(response);
                        if(response.response == '871') {
                            alert("Invalid card number.  Check and retry. (Not Mod10)");
                        }
                        else if(response.response == '872') {
                            alert("Invalid card number.  Check and retry. (Too short)");
                        }
                        else if(response.response == '873') {
                            alert("Invalid card number.  Check and retry. (Too long)");
                        }
                        else if(response.response == '874') {
                            alert("Invalid card number.  Check and retry. (Not a number)");
                        }
                        else if(response.response == '875') {
                            alert("We are experiencing technical difficulties. Please try again later or call 555-555-1212");
                        }
                        else if(response.response == '876') {
                            alert("Invalid card number.  Check and retry. (Failure from Server)");
                        }
                        else if(response.response == '881') {
                            alert("Invalid card validation code.  Check and retry. (Not a number)");
                        }
                        else if(response.response == '882') {
                            alert("Invalid card validation code.  Check and retry. (Too short)");
                        }
                        else if(response.response == '883') {
                            alert("Invalid card validation code.  Check and retry. (Too long)");
                        }
                        else if(response.response == '889') {
                            alert("We are experiencing technical difficulties. Please try again later or call 555-555-1212");
                        }
                        return false;
                    }
                    var formFields = {
                        "accountNum"   :document.getElementById('ccNum'),
                        "cvv2"   :document.getElementById('cvv2Num'),
                        "paypageRegistrationId":document.getElementById('response$paypageRegistrationId'),
                        "bin"  :document.getElementById('response$bin')
                    };
                    $("submitId").click(
                            function(){
                                alert('test1');
                                setLitleResponseFields({"response":"", "message":""});
                                var litleRequest = {
                                    "paypageId" : document.getElementById("request$paypageId").value,
                                    "reportGroup" : document.getElementById("request$reportGroup").value,
                                    "orderId" : document.getElementById("request$orderId").value,
                                    "id" : document.getElementById("request$merchantTxnId").value,
                                    "url" : "https://cert01.securepaypage.litle.com"
                                };
                                sendToLitle(litleRequest, formFields, submitAfterLitle, onErrorAfterLitle,
                                        timeoutOnLitle, 5000);
                                alert('test2');
                                return false;
                            }
                    );
                }
        );
    </script>
<form method=post id="fCheckout" name="fCheckout"
      action="/merchant101/Merchant101CheckoutServlet">
    <input type="hidden" id="request$paypageId" name="request$paypageId"
           value="Qin4GtDLCeop8bRM"/>
    <input type="hidden" id="request$merchantTxnId" name="request$merchantTxnId"
           value="115300"/>
    <input type="hidden" id="request$orderId" name="request$orderId" value="order_123"/>
    <input type="hidden" id="request$reportGroup" name="request$reportGroup"
           value="*merchant1500"/>
    <table>
        <tr><td>First Name</td><td><input type="text" id="fName" name="fName"
                                          size="20"></td></tr>
        <tr><td>Last Name</td><td><input type="text" id="lName" name="lName"
                                         size="20"></td></tr>
        <tr><td>Credit Card</td><td><input type="text" id="ccNum" name="ccNum"
                                           size="20"></td></tr>
        <tr><td>CVV</td><td><input type="text" id="cvv2num" name="cvv2num"
                                   size="5"></td></tr>
        <tr><td>Exp Date</td><td><input type="text" id="expDate" name="expDate"
                                        size="5"></td></tr>
        <tr><td>&nbsp;</td><td></tr>
        <tr><td></td><td align="right">
            <script>
                document.write('<button type="button" id="submitId" onclick="callLitle()">Checkout with PayPage</button>');
            </script>
            <noscript>
                <button type="button" id="submitId">Enable JavaScript or call us at 555-555-1212</button>
            </noscript>
        </td></tr>
    </table>
    <input type="hidden" id="response$paypageRegistrationId"
           name="response$paypageRegistrationId" readOnly="true" value=""/>
    <input type="hidden" id="response$bin" name="response$bin" readOnly="true"/>
    <input type="hidden" id="response$code" name="response$code" readOnly="true"/>
    <input type="hidden" id="response$message" name="response$message" readOnly="true"/>
    <input type="hidden" id="response$responseTime" name="response$responseTime"
           readOnly="true"/>
    <input type="hidden" id="response$type" name="response$type" readOnly="true"/>
    <input type="hidden" id="response$litleTxnId" name="response$litleTxnId"
           readOnly="true"/>
</form>
<script>
    function callLitle() {
        if(typeof sendToLitle != 'function') {
            alert("We are experiencing technical difficulties.  Please try again later or call 555-555-1212 (API unavailable)" );
        }
    }
</script>
<div class="spinner" style="display: none;"><img src="<?php echo $this->getSkinUrl( 'images/ajax-loader.gif' ) ?>"></div>
