<div class="order-review" id="checkout-review-load">
    <?php echo $this->getChildHtml('info') ?>
    <?php echo $this->getChildHtml('reward.tooltip.checkout') ?>
    <?php echo $this->getChildHtml('reward.tooltip.checkout.salesrule') ?>
</div>
<script>
	jQuery( document ).ready( function() {
	    updateSelectText();
	    jQuery('#hpcheckout-wrapper .totsy-selective-input-box select').bind( 'change', updateSelectText );
	});
</script>