<form id="hpcheckout-shipping-form" action="">
    <div class="row">
	    <div id="shipping-new-address-form fields alpha">
	            <div class="span5"> 
	    		    <div class="pull-left field half-of-half">
	    	           <label for="shipping:firstname" class="required"><em>*&nbsp;</em><?php echo $this->__('first name') ?></label>
	    	           <input type="text" name="shipping[firstname]" title="<?php echo $this->__('First Name') ?>" class="input-text required-entry firstname" value="<?php echo $this->htmlEscape($this->getFirstname()) ?>" id="shipping:firstname" />
	    	        </div>
	    	        <div class="field half-of-half">
	    	            <label for="shipping:lastname" class="required"><em>*&nbsp;</em><?php echo $this->__('last name') ?></label>
	    	            <input type="text" name="shipping[lastname]" title="<?php echo $this->__('Last Name') ?>" class="input-text required-entry lastname" value="<?php echo $this->htmlEscape($this->getLastname()) ?>" id="shipping:lastname" />
	    	        </div>
	    	    </div>
	    	    <input type="hidden" name="shipping[email]" id="shipping:email" value="<?php echo $this->getCustomer()->getEmail() ?>" />
	    	    <input type="hidden" name="shipping[selected]" id="shipping:selected" />
	    	    <!-- li class="fields">
	    	        <div class="field half-of-half">
			            <span for="shipping:email" class="required"><em>*</em><?php echo $this->__('Email Address') ?></span>
			            <input type="text" name="shipping[email]" id="shipping:email" title="<?php echo $this->__('Email Address') ?>" class="input-text validate-email required-entry" value="<?php echo $this->htmlEscape($this->getAddress()->getEmail()) ?>" />
			        </div>
	    	    </div-->
	    	    <div class="span5">
	    	        <div class="pull-left field half-of-half">
	    	            <label for="shipping:telephone" class="required"><em>*&nbsp;</em><?php echo $this->__('telephone') ?></label>
	    	            <input type="text" name="shipping[telephone]" title="<?php echo $this->__('Telephone') ?>" class="input-text required-entry validate-phoneLax telephone" id="shipping:telephone" value="<?php echo $this->htmlEscape($this->getAddress()->getTelephone()) ?>" onkeyup="backspacerUP(this,event);" onkeydown="backspacerDOWN(this,event);"/>
	    	        </div>
	    	     </div> 
	    	     <div class="span5">
	    	         <div class="field half-of-half">
			            <label for="shipping:street1" class="required"><em>*&nbsp;</em><?php echo $this->__('street address line 1') ?></label>
			            <input type="text" title="<?php echo $this->__('Street Address Line 1') ?>" name="shipping[street][0]" id="shipping:street1" value="<?php echo $this->htmlEscape($this->getAddress()->getStreet(1)) ?>" class="input-text required-entry streetaddress1" />
	    	        </div>
	    	     </div>
	    	     <div class="span5">
	    	         <div class="pull-left field half-of-half">
	                   <label for="shipping:street2">&nbsp;<?php echo $this->__('street address line 2') ?></label>
	                   <input type="text" title="<?php echo $this->__('Street Address Line 2') ?>" name="shipping[street][1]" id="shipping:street2" value="<?php echo $this->htmlEscape($this->getAddress()->getStreet(2)) ?>" class="input-text streetaddress2" />
	                 </div>
	    	     </div>
	    	     <div class="span5"> 
                     <div class="pull-left field half-of-half">
	                     <label for="shipping:city" class="required"><em>*&nbsp;</em><?php echo $this->__('city') ?></label>
	                     <input type="text" title="<?php echo $this->__('City') ?>" name="shipping[city]" class="input-text required-entry city" value="<?php echo $this->htmlEscape($this->getAddress()->getCity()) ?>" id="shipping:city" />
	                 </div>	 
	                 <div class="field half-of-half">
	                     <label for="shipping:region_id" class="required"><em>*&nbsp;</em><?php echo $this->__('state') ?></label>
		                 <div class="totsy-selective-input-box">
		                     <select id="shipping:region_id" name="shipping[region_id]" title="<?php echo $this->__('State') ?>" class="validate-select state" style="display:none;" >
		                       <option value=""><?php echo $this->__('Please select state') ?></option>
		                     </select>
		                 </div>
	                     <script type="text/javascript">
                            $('shipping:region_id').setAttribute('defadivtValue',  "<?php echo $this->getAddress()->getRegionId() ?>");
                         </script>
                         <input type="text" id="shipping:region" name="shipping[region]" value="<?php echo $this->htmlEscape($this->getAddress()->getRegion()) ?>"  title="<?php echo $this->__('State/Province') ?>" class="input-text hidden-state" style="display:none;" />
	                  </div>
	              </div>
	              <div class="span5">
	                  <div class="pull-left field half-of-half">
	                      <label for="shipping:postcode" class="required"><em>*&nbsp;</em><?php echo $this->__('zip/postal code') ?></label>
	                      <input type="text" title="<?php echo $this->__('Zip/Postal Code') ?>" name="shipping[postcode]" id="shipping:postcode" class="input-text validate-zip required-entry zip" value="<?php echo $this->htmlEscape($this->getAddress()->getPostcode()) ?>" />
	                  </div>
	                 <div class="field half-of-half">
                         <label for="shipping:country_id" class="required"><em>*&nbsp;</em><?php echo $this->__('country') ?></label>
			             <div class="totsy-selective-input-box totsy-selective-input-box-shipping-country country">
			             	<?php echo $this->getCountryHtmlSelect('shipping') ?>
			             </div>
                     </div>
                 </div>
    </div>
</form>
<div class="spinner" style="display: none;"><img src="<?php echo $this->getSkinUrl( 'images/ajax-loader.gif' ) ?>"></div>

<script type="text/javascript">
//<![CDATA[
    var shippingRegionUpdater = new RegionUpdater('shipping:country_id', 'shipping:region', 'shipping:region_id', countryRegions, undefined, 'shipping:postcode');
//    var billingForm = new VarienForm('hpcheckout-shipping-form');
    jQuery( document ).ready( function() {
        jQuery( '#shipping\\:postcode, #shipping\\:region_id' ).bind( 'change', hpcheckout.update );
        jQuery( '#shipping-address-select' ).bind( 'change', hpcheckout.switchAddress );
        jQuery( '#billing\\:selected' ).val(jQuery( '#billing-address-select' ).val());
    });
    
//]]>
</script>
