<?php

$productIds = "";
$productPrices = "";
$buyerEmail = "";
$buyerName = "";
$couponsUsed = "";
$buyerId = "";

?>
<div class="page-title">
     <h1><?php echo $this->__('Your order has been received') ?></h1>
</div>
<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<h2 class="sub-title"><?php echo $this->__('Thank you for your purchase!') ?></h2>

<!-- Multiple Fulfillment types-->
<?php if($this->hasMultipleOrders()):?>
    <?php $orderIds = $this->getTheOrderIds();?>
    <?php $flag = false;?>
    <p><?php echo $this->__('Your order numbers are ') ?>
    <?php foreach($orderIds as $orderId => $incrementId):?>
        <?php if ($flag): ?>
<?php echo ', ' ?>
        <?php endif; ?>
        <?php $flag = true ?>
        <a href="<?php echo $this->getViewOrderUrl($orderId); ?>"><?php echo $incrementId; ?></a>
    <?php endforeach;?>
.</p>
<p><?php echo $this->__('You will receive an order confirmation email with details of your order and a link to track its progress.') ?></p>
<p><?php echo $this->__('Click <a href="%s">here</a> to continue. ', $this->getBaseUrl().'sales/order/history/');?></p>
<p class="red review-order-detail">
    <?php
$url = $this->getBaseUrl().'sales/order/history/';
?>
    You will redirect to orders review page in 10 seconds. Or <a class="red" href="<?php echo $url?>">click here</a>
</p>
<script language="javascript" type="text/javascript">
    function redirect(){window.location.href="<?php echo $url?>"};
    //setTimeout("redirect()",10000);
</script>
    <?php foreach($orderIds as $orderId => $incrementId):?>
        <?php $order = Mage::getModel('sales/order')->loadByIncrementId($incrementId);
        	  
        ?>
        <script type="text/javascript">

            var _gaq = _gaq || [];
            _gaq.push(['_setAccount', '<?php echo Mage::getStoreConfig("google/analytics/account")?>']);
            _gaq.push(['_trackPageview']);
            _gaq.push(['_addTrans',
                '<?php echo $order->getData('increment_id'); ?>',     // order ID - required
                'Totsy',  // affiliation or store name
                '<?php echo $order->getData('grand_total'); ?>',      // total - required
                '<?php echo $order->getData('tax_amount'); ?>',       // tax
                '<?php echo $order->getData('shipping_amount'); ?>',  // shipping
<?php if ($address = $order->getShippingAddress()): ?>
               ,'<?php echo $address->getData('city') ?>',            // city
                '<?php echo $address->getData('region') ?>',          // state or province
                'USA'          // country
<?php endif; ?>
            ]);
                <?php
$category = array();
// $productid = Mage::getModel('catalog/product')->getData('category_ids');
// $order  = Mage::getModel('catalog/category')->getCollection()->load($productid);
foreach($order->getAllItems() as $item):?>
                    <?php  if( !! $item->getParentItemId() ) {
		continue;
	}
unset($category);
$product = Mage::getModel( 'catalog/product' )->load( $item->getProductId() );
$categoryIds = $product->getCategoryIds();
foreach ($categoryIds as $cateId){
	$category[] = Mage::getModel('catalog/category')->load($cateId)->getData('name');
}
?>
                // add item might be called for every item in the shopping cart
                // where your ecommerce engine loops through each item in the cart and
                // prints out _addItem for each
                _gaq.push(['_addItem',
                    '<?php echo $order->getData('increment_id'); ?>',           // order ID - required
                    '<?php echo $item->getData('sku'); ?>',           // SKU/code - required
                    '<?php echo $item->getData('name')?>',        // product name
                    '<?php foreach($category as $cat){
	echo $cat.',';
} ?>',   // category or variation
                    '<?php echo $item->getPrice() ?>',          // unit price - required
                    '<?php echo $item->getQtyOrdered() ?>'               // quantity - required
                ]);
                //Used with Insparq
                <?php $productPrices .= "|" . $item->getPrice(); 
                $productIds .= "|" . $item->getProductId(); ?>
                    <?php endforeach;?>
            _gaq.push(['_trackTrans']); //submits transaction to the Analytics servers
    </script>
    <script type="text/javascript">
        var aid='9577';
        var oid='<?php echo $orderId; ?>';
        var oamt='<?php echo $order->getData('grand_total'); ?>';
        var additional = '';
        (function(){steelhouse={add:function(a,b,c,d){d=d||false;if(a.addEventListener){a.addEventListener(b,c,d)}else if(a.attachEvent){a.attachEvent("on"+b,c)}},load:function(){var a;if(typeof a=='undefined'){a=Math.random()*10000000000000000}var b=document.createElement('script');var c='px.steelhousemedia.com/st?aid='+aid+'&conv=1&order_id='+oid+'&order_amt='+oamt+'&cb='+a+additional;b.type='text/javascript';b.src=('https:'==document.location.protocol?'https://':'http://')+c;var d=document.getElementsByTagName('script');var e=Number(d.length)-1;var f=document.getElementsByTagName('script')[e];f.parentNode.insertBefore(b,f)}};steelhouse.load();})();
    </script>

    <?php endforeach; // End order loop ?>
<?php endif;?>



<?php if ($this->getOrderId()):?>
<?php
	$orderIncrementId = $this->getOrderId();
$order = Mage::getModel('sales/order')->loadByIncrementId($orderIncrementId);

$buyerId = $order->getData('customer_id');
$customer = Mage::getModel('customer/customer')->load($buyerId);

$buyerName = $customer->getData('firstname')." ".$customer->getData('lastname');
$buyerEmail = $customer->getData('email');
$couponsUsed = "";

$quoteId = $order->getQuoteId();
$quote = Mage::getModel('sales/quote')->load($quoteId);

?>
<?php if ($this->getCanViewOrder()) :?>
    <p><?php echo $this->__('Your order # is: %s.', sprintf('<a href="%s">%s</a>', $this->escapeHtml($this->getViewOrderUrl($order->getId())), $this->escapeHtml($this->getOrderId()))) ?></p>
<?php  else :?>
    <p><?php echo $this->__('Your order # is: %s.', $this->escapeHtml($this->getOrderId())) ?></p>
<?php endif;?>
    <p><?php echo $this->__('You will receive an order confirmation email with details of your order and a link to track its progress.') ?></p>
<?php if ($this->getCanViewOrder() && $this->getCanPrintOrder()) :?>
    <p>
        <?php echo $this->__('Click <a href="%s" onclick="this.target=\'_blank\'">here to print</a> a copy of your order confirmation.', $this->getPrintUrl()) ?>
        <?php echo $this->getChildHtml() ?>
    </p>
    <p class="red review-order-detail">
    	<?php
		$order_id = $order->getId();
	$url = $this->getBaseUrl().'sales/order/history/';
?>
		You will redirect to orders review page in 10 seconds. Or <a class="red" href="<?php echo $url?>">click here</a>
    </p>
    <!-- <div id="rondavu_checkout_container"></div> -->
    <script language="javascript" type="text/javascript">
		function redirect(){window.location.href="<?php echo $url?>"};
		  //setTimeout("redirect()",10000);
	</script>
	<?php endif;?>

<script async="async" data-issw-publisher-id="48fa5885203f6957a1b65fb8a4c3304e" src="https://api.insparq.com/v2.0.0/widget/scripts/issw.js" type="text/javascript"></script>
<script type="text/javascript">

    var _gaq = _gaq || [];
    _gaq.push(['_setAccount', '<?php echo Mage::getStoreConfig("google/analytics/account")?>']);
    _gaq.push(['_trackPageview']);
    _gaq.push(['_addTrans',
        '<?php echo $order->getData('increment_id'); ?>',     // order ID - required
        'Totsy',                                              // affiliation or store name
        '<?php echo $order->getData('grand_total'); ?>',      // total - required
        '<?php echo $order->getData('tax_amount'); ?>',       // tax
        '<?php echo $order->getData('shipping_amount'); ?>'   // shipping
<?php if ($address = $order->getShippingAddress()): ?>
       ,'<?php echo $address->getData('city') ?>',            // city
        '<?php echo $address->getData('region') ?>',          // state or province
        'USA'          // country
<?php endif; ?>
    ]);
        <?php
$category = array();
// $productid = Mage::getModel('catalog/product')->getData('category_ids');
// $order  = Mage::getModel('catalog/category')->getCollection()->load($productid);
foreach($order->getAllItems() as $item):?>
            <?php  if( !! $item->getParentItemId() ) {
		continue;
	}
unset($category);
$product = Mage::getModel( 'catalog/product' )->load( $item->getProductId() );
$categoryIds = $product->getCategoryIds();
foreach ($categoryIds as $cateId){
	$category[] = Mage::getModel('catalog/category')->load($cateId)->getData('name');
}
?>

        // add item might be called for every item in the shopping cart
        // where your ecommerce engine loops through each item in the cart and
        // prints out _addItem for each
        _gaq.push(['_addItem',
            '<?php echo $order->getData('increment_id'); ?>',           // order ID - required
            '<?php echo $item->getData('sku'); ?>',           // SKU/code - required
            '<?php echo $item->getData('name')?>',        // product name
            '<?php foreach($category as $cat){
	echo $cat.',';
} ?>',   // category or variation
            '<?php echo $item->getPrice() ?>',          // unit price - required
            '<?php echo $item->getQtyOrdered() ?>'               // quantity - required
        ]);
        	
            <?php
            	$productPrices .= "|" . $item->getPrice(); 
                $productIds .= "|" . $item->getProductId();
endforeach;
?>
    _gaq.push(['_trackTrans']); //submits transaction to the Analytics servers

    (function() {
        var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
        ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
        var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
    })();

</script>

<div id="issw" style="display:block"
data-issw-type="referral"
data-issw-widget-promotion-display="0"
data-issw-widget-buttons-display="ftp"
data-issw-referral-name="Invitation to Totsy"
data-issw-referral-image-url="https://www.totsy.com/skin/frontend/enterprise/bootstrap/images/logo.png"
data-issw-referral-url="http://www.totsy.com"
data-issw-dialogs-facebook-defaults-personal="I'm inviting my Facebook friends to save on Totsy, the premier private shopping network for moms-to-be and moms on-the-go. Membership is by invitation or request only, and itÕs free!" data-issw-dialogs-twitter-defaults-personal="Inviting my followers to save on @MyTotsy!, the premier private shopping network for moms-to-be and moms-on-the-go!" 
data-issw-dialogs-pinterest-defaults-description="Inviting my friends to save on Totsy!, the premier private shopping network for moms-to-be and moms-on-the-go!">
    <div data-issw-text-dialog-success="" style="display:none"><p>Thanks for sharing! Totsy will credit your account with $15 after your friend's first order ships.</p></div>
</div>

 <img width="0" height="0" src="https://api.insparq.com/api/v20120319/key/48fa5885203f6957a1b65fb8a4c3304e/user?pageType=purcon&cartValue='<?php echo $order->getData('grand_total'); ?>'&cartItemCount='<?php echo count($order->getAllItems()); ?>'&beacon=1&productIds='<?php echo $productIds; ?>'&productPrices='<?php echo $productPrices; ?>'&buyerName='<?php echo $buyerName; ?>'&buyerEmail='<?php echo $buyerEmail; ?>'&couponsUsed='<?php echo $couponsUsed; ?>'&buyerId='<?php echo $buyerId; ?>'" />

<script type="text/javascript">
var aid='9577';
var oid='<?php echo $order_id ?>';
var oamt='<?php echo $order->getData('grand_total'); ?>';
var additional = '';
(function(){steelhouse={add:function(a,b,c,d){d=d||false;if(a.addEventListener){a.addEventListener(b,c,d)}else if(a.attachEvent){a.attachEvent("on"+b,c)}},load:function(){var a;if(typeof a=='undefined'){a=Math.random()*10000000000000000}var b=document.createElement('script');var c='px.steelhousemedia.com/st?aid='+aid+'&conv=1&order_id='+oid+'&order_amt='+oamt+'&cb='+a+additional;b.type='text/javascript';b.src=('https:'==document.location.protocol?'https://':'http://')+c;var d=document.getElementsByTagName('script');var e=Number(d.length)-1;var f=document.getElementsByTagName('script')[e];f.parentNode.insertBefore(b,f)}};steelhouse.load();})();
</script>
<?php endif;?>