 <div id="customertracking_ajax"></div>
<script type="text/javascript">
    Event.observe(window,'load',function() {
        new Ajax.Updater({success: 'customertracking_ajax'}, "<?php echo Mage::getUrl('customertracking/index/ajax',array('_secure' => Mage::app()->getStore()->isCurrentlySecure(), '_query'=>array('pageTag'=>strtolower(Mage::app()->getFrontController()->getAction()->getFullActionName())))); ?>", {method:'get',evalScripts: true});
    });
</script>
