<?php $affiliate = Mage::getSingleton('customer/session')->getAffiliate(); ?>
<script type="text/javascript">
    if(typeof _gaq != "undefined") {
    _gaq.push(['_trackEvent', 'affiliate', '<?php echo $this->getCurrentAffiliateEventName() ?>', '<?php echo $affiliate->getAffiliateCode() ?>']);
    }
</script>
<?php debug("In the pixel template!!"); ?>
<?php echo $this->getCurrentAffiliatePixel() ?>
