<?php
/**
 * Harapartners
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Harapartners License
 * that is bundled with this package in the file LICENSE_EE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.Harapartners.com/license
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@Harapartners.com so we can send you a copy immediately.
 *
 */
?>
<?php $customer = Mage::getSingleton('customer/session')->getCustomer();?>
<?php if ( Mage::helper('inchoo_facebook')->isFacebookCustomer($customer) ):?>
<div class="ui-btn-inner ui-li" aria-hidden="true">
	<div class="ui-btn-text">
		<a class="ui-link-inherit" onclick="logout()" style="cursor:pointer"><?php echo $this->__('Sign Out'); ?></a>
		<span class="ui-icon ui-icon-arrow-r ui-icon-shadow"></span>
	</div>
</div>
<script type="text/javascript">
	function logout(){	
		FB.logout(function(response) {
			window.location = "<?php echo Mage::getUrl('customer/account/logout')?>"// user is now logged out
		});
	}
</script>
<?php else: ?>
<div class="ui-btn-inner ui-li" aria-hidden="true">
	<div class="ui-btn-text">
		<a class="ui-link-inherit" href="<?php echo $this->getUrl('customer/account/logout')?>"><?php echo $this->__('Sign Out'); ?></a>
		<span class="ui-icon ui-icon-arrow-r ui-icon-shadow"></span>
	</div>
</div>
<?php endif;?>
