<?php
/**
 * Harapartners
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Harapartners License
 * that is bundled with this package in the file LICENSE_EE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.Harapartners.com/license
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@Harapartners.com so we can send you a copy immediately.
 *
 */
?>
<?php 
	$isFaceBook =	Mage::getSingleton('customer/session')->getFacebookAccountFirstCreate();
?>
<?php if ( !!$isFaceBook ):?>
	<a id="facebook_pop" href="#facebook_window" class="hidden"></a>
	<div style="display: none;">
		<div id="facebook_window">
			<div class="window_content">	
				<h3><img src="<?php echo $this->getSkinUrl()?>images/facebook_pop.png" width="40px" height="40px"></img>Thanks for Joining Totsy!</h3>
				<p>	Please retrieve your temporary password through your email and update it in your <a  class="needgreen" href="<?php echo $this->getBaseUrl()?>customer/account/edit/">account panel</a></p>
			</div>
		</div>
	</div>
	<script type="text/javascript">
	    jQuery(document).ready(function() {
	    	jQuery("#facebook_pop").fancybox({
				'speedIn'		:	600, 
				'speedOut'		:	200, 
			}).trigger('click');
	    });
	</script>
	<?php Mage::getSingleton('customer/session')->setFacebookAccountFirstCreate(false);?>
<?php elseif( Mage::helper('enterprise_invitation')->isInvitationMessageAllowed() && Mage::helper('service')->isTotsyStore() ):?>
	<a id="invite_pop" href="#invite_window" class="hidden"></a>
	<div style="display: none;">
		<div id="invite_window" >
			<div class="little-title">
			    <h2><?php echo Mage::helper('enterprise_invitation')->__('Send Invitations') ?></h2>
				<hr class="the-hr"/>
				<p class="invite-notes">
				<?php $inviteFriendNotes = "For each friend you invite, Totsy will credit your account with <span class='needgreen'>$15</span> after your friend's place their first order."; ?>
				<?php echo Mage::helper('enterprise_invitation')->__($inviteFriendNotes); ?>
				</p>
			</div>
			<form id="invitationForm" action="<?php echo $this->helper('enterprise_invitation')->getCustomerInvitationFormUrl()?>" method="post">
			    <div class="fieldset">		
			        <ul class="form-list">
			            <?php //$_perRow = ceil($maxPerSend/3); for($_index = 1; $_index <= $maxPerSend; $_index ++): ?>
			            <li class="email-add-box">
							<label for="email"><?php echo Mage::helper('enterprise_invitation')->__('Enter Your Friends Email Addresses:');?> </label>
			                <div class="input-box">
			                    <textarea id="contact_list" tabindex="<?php //echo $_index+1 ?>" name="email" id="inviteemailaddress" title="<?php echo Mage::helper('enterprise_invitation')->__('email') ?>"  class="input-text" rows="3" cols="4"></textarea>
			                </div>
			               
			            </li>
			            <?php //endfor; ?>
			        <?php if (Mage::helper('enterprise_invitation')->isInvitationMessageAllowed()): ?>
			            <li class="email-msg-box">
			                <label for="message"><?php echo Mage::helper('enterprise_invitation')->__('Personalized Message To Friends:');?> </label>
			                <div class="input-box">
			                    <textarea tabindex="<?php //echo $_index+1 ?>" name="message" id="message" title="<?php echo Mage::helper('enterprise_invitation')->__('Message') ?>"  class="input-text" rows="3" cols="4"><?php echo 'Please accept this invitation to join Totsy'; ?></textarea>
			                </div>
			            </li>
			        </ul>
			        <?php endif;?>
			    </div>
			   <!--p class="required"><?php echo Mage::helper('enterprise_invitation')->__('* Required Fields') ?></p-->
			    <div class="buttons-set form-buttons">
			        <!--p class="back-link"><a href="<?php echo Mage::helper('enterprise_invitation')->getCustomerInvitationUrl() ?>"><small>&laquo; </small><?php  echo Mage::helper('enterprise_invitation')->__('Back to Invitations') ?></a></p-->
			        <button class="button" type="submit"><div class="invite-button"><?php echo Mage::helper('enterprise_invitation')->__('Send Invitations') ?></div></button>
			    </div>			
			</form>
			<script type="text/javascript">
			    var contactForm = new VarienForm('invitationForm', false);
			</script>
		</div>
	</div>
	
	<script type="text/javascript">
	    jQuery(document).ready(function() {
	    	jQuery("#invite_pop").fancybox({
				'speedIn'		:	600, 
				'speedOut'		:	200, 
			}).trigger('click');
	    });
	</script>
<?php endif; ?>