<?php
/*
 * NOTICE OF LICENSE
 *
 * This source file is subject to the End User Software Agreement (EULA).
 * It is also available through the world-wide-web at this URL:
 * http://www.harapartners.com/license
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to eula@harapartners.com so we can send you a copy immediately.
 * 
 */
?>

<div class="content-header">
<h3 class="icon-head head-adminhtml-emailcoupon">Add Group Coupon Codes</h3>
</div>
<form action="<?php echo $this->getUrl('promotionfactory/adminhtml_groupcoupon/generate'); ?>" method="post" enctype = "multipart/form-data">
		<input type="hidden" name="form_key" value="<?php echo $this->getFormKey(); ?>"/>
		<input type="hidden" name="id" value="<?php echo $this->getRequest()->getParam('id'); ?>"/>
	<table cellspacing="0" class="form-list">
		<tbody>
			<tr>
				<td class="label"><label for="name">Name</td>
				<td><span ><?php $coupon = Mage::getModel('salesrule/rule')->load($this->getRequest()->getParam('id')); echo $coupon->getName();?> </span></label></td>
				<td class="value"></td>
			</tr>
			<tr>
				<td class="label"><label for="import">Generate Coupon Codes</label></td>
				<td class="value"><input type="text" value="" name="total" id="total" size=8 >&nbsp;<button type="submit"><span>Generate</span></button></td>
			</tr>
		</tbody>
	</table>
</form>

<form action="<?php echo $this->getUrl('promotionfactory/adminhtml_groupcoupon/import'); ?>" method="post" enctype = "multipart/form-data" >
	<input type="hidden" name="form_key" value="<?php echo $this->getFormKey(); ?>"/>
	<input type="hidden" name="id" value="<?php echo $this->getRequest()->getParam('id'); ?>"/>
	<table cellspacing="0" class="form-list">
	<tbody>
		<tr>
			<td class="label"><label for="import">Import Coupon Codes</label></td>
			<td class="value"><input type="file" value="" name="import" id="import">&nbsp;<button type="submit"><span>Import</span></button></td>
		</tr>
	</tbody>
	</table>
</form>
<script type="text/javascript">
    editForm = new varienForm('edit_form', '');
</script></div>
<?php
 echo $this->getGridHtml ();
?>