<!DOCTYPE html>
<html lang="<?php echo $this->getLang() ?>" class="store-<?php echo Mage::app()->getStore()->getCode(); ?>">
<head>
<?php echo $this->getChildHtml('head') ?>
</head>
<body<?php echo $this->getBodyClass()?' class="'.$this->getBodyClass().'"':'' ?>>
<?php echo $this->getChildHtml('after_body_start') ?>
<div class="wrapper">
    <?php echo $this->getChildHtml('global_notices') ?>
    <div class="page">
        <?php echo $this->getChildHtml('header') ?>
<style>

.pinterestform{
	text-align:center;
	font-size:14px;
	padding-top: 25px;
	color:#444444;
}

.pinterestform a{
	color:#000000;
}

.pinterestform input{
	width:400px;
	height:25px;
	border:1px solid #999999;
	margin:5px;
}

.pinterestform select{
	width:200px;
	height:25px;
	border:1px solid #999999;
	margin:5px;
}

.pinterestfooter{
	margin-top:30px;
	padding:20px;
	color:#666666;
	size:12px;

}

</style>


    <div class="page">
        <div class="main pinterestform">


<?php
if($_POST['totsyemail']){

	$to      = 'jwidro@totsy.com';
	$subject = 'pinterest fever';
	$totsyemail = $_POST['totsyemail'];
	$region = $_POST['region'];
	$pinterestuser = $_POST['pinterestuser'];
	
	$message ="
	email - $totsyemail
	
	region - $region
	
	pinterest - $pinterestuser
	";
	
	$headers = 'From: webmaster@example.com' . "\r\n" .
	    'Reply-To: webmaster@example.com' . "\r\n" .
	    'X-Mailer: PHP/' . phpversion();
	
	mail($to, $subject, $message, $headers);
?>
				<img src="/skin/frontend/enterprise/harapartners/images/pinterest/SummerSpiritContest-header2.jpeg">                
				<a href="/a/pinterestsummerspirit"><img src="/skin/frontend/enterprise/harapartners/images/pinterest/PinButton.jpeg" style="cursor:pointer;border:0px;"></a>                
				<br>
				<img src="/skin/frontend/enterprise/harapartners/images/pinterest/PinterestSun.jpeg">        

				<br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br>
<?php } else{ ?>

<script>

function submit(){

	if(document.getElementById("totsyemail").value==""){
		alert("email is required!");	
	}
	else if(document.getElementById("region").value==""){
		alert("region is required!");	
	}
	else if(document.getElementById("pinterestuser").value==""){
		alert("pinterest url is required!");	
	}
	else{
		document.forms["pinterestform"].submit();
	}
	

}

</script>
				<img src="/skin/frontend/enterprise/harapartners/images/pinterest/SummerSpiritContest-header.jpeg">                
				<img src="/skin/frontend/enterprise/harapartners/images/pinterest/PinterestMap.jpeg">                
				<img src="/skin/frontend/enterprise/harapartners/images/pinterest/PinterestPrizeInfo.jpeg">                
                
                <form method="post" id="pinterestform" name="pinterestform">
                	<input type="text" id="totsyemail" name="totsyemail">
                	<br>
                	<b>ENTER TOTSY EMAIL</b>
                	<br>
                	Not a member? <a href="/customer/account/create/">Join Here!</a>
                	<br><br>
                	<select id="region" name="region">
                		<option value="">-- choose region --</option>
                		<option value="totsywest">#totsywest</option>
                		<option value="totsymidwest">#totsymidwest</option>
                		<option value="totsyeast">#totsyeast</option>
                		<option value="totsysouth">#totsysouth</option>
                	</select>
                	<br>
                	<b>REGION BASED ON MAP</b>
                	<br>
                	i.e. if you live in Chicago choose Midwest
                	<br><br>
                	<input type="text" id="pinterestuser" name="pinterestuser">
                	<br>
                	<b>PINTEREST USER/URL</b>
                	<br>
                	i.e. pinterest.com/user
                	<input type="hidden" id="pinterestsubmit" name="pinterestsubmit">
                	<br><br>
                	
                	
				<img src="/skin/frontend/enterprise/harapartners/images/pinterest/PinterestSubmitButton.jpeg" style="cursor:pointer;" onclick="submit(); return false;">                
				<br>
				<img src="/skin/frontend/enterprise/harapartners/images/pinterest/PinterestSun.jpeg">        

                </form>

<?php
}
?>
			<div class="pinterestfooter">
			<b>RULES</b><br>
			
			<li>Follow Totsy on Pinterest <a href="http://pinterest.com/totsyfan">http://pinterest.com/totsyfan</a> </li>
			<li>Join your team based on the map above</li>
			<li>Pin a picture to the designated board, located on Totsy's Pinterest page, with the specified hashtag (up to 3 pins per participant)</li>
			<li>The most repinned board wins! We will pick one lucky winner from the winning board, good luck!</li>
			
			<br><br>
			<b>TERMS & CONDITIONS</b><br>
			No purchase necessary. Must be 18+ to enter and must be U.S. resident to be eligible. Contest valid until 11:59pm EST 07/25/12
			</div>



		</div>
	</div>








        <?php echo $this->getChildHtml('footer_before') ?>
        <?php echo $this->getChildHtml('footer') ?>
        <?php echo $this->getChildHtml('before_body_end') ?>
    </div>
</div>
<?php echo $this->getAbsoluteFooter() ?>
</body>
</html>
