<?php $_code=$this->getMethodCode() ?>
<script type="text/javascript">
//<![CDATA[
    Validation.creditCartTypes.set('JCB', [new RegExp('^(35[0-9]{14}|(2131|1800)[0-9]{11})$'), new RegExp('^([0-9]{3})?$'), true]);
    Validation.creditCartTypes.set('LASER', [new RegExp('^((6304|6706|6771|6709)[0-9]{12}([0-9]{3}))$'), new RegExp('^([0-9]{3})?$'), false]);
    Validation.creditCartTypes.set('UATP', [false, new RegExp('^[0-9]{3}([0-9]{1})?$'), false]);
    Validation.creditCartTypes.set('MCI', [false, new RegExp('^[0-9]{3}([0-9]{1})?$'), false]);
//]]>
</script>


<ul class="form-list" id="payment_form_<?php echo $_code ?>" style="display:none;">
    <?php /*<li>
        <label for="<?php echo $_code ?>_cc_owner" class="required"><em>*</em><?php echo $this->__('Name on Card') ?></label>
        <div class="input-box">
            <input type="text" title="<?php echo $this->__('Name on Card') ?>" class="input-text required-entry" id="<?php echo $_code ?>_cc_owner" name="payment[cc_owner]" value="<?php echo $this->htmlEscape($this->getInfoData('cc_owner')) ?>" />
        </div>
    </li>*/ ?>
    <?php $customerId = Mage::getSingleton('customer/session')->getCustomerId() ?>
    <?php $profiles = $this->getProfilesByCustomerId( $customerId ) ?>
    <?php
        $profilesCounter = 0;
        foreach( $profiles as $profile ) {
            if($profile->getSubscriptionId() && $profile->getData('saved_by_customer')) {
                $profilesCounter++;
            }
        }
    ?>
    <?php if( $customerId && $profiles && ($profilesCounter>0) ): ?>
        <li class="switch-card-control">
            <label for="use-card-method">Choose a credit/debit card:</label>
            <div class="totsy-selective-input-box middle-length" id="use-card-method">
                <span>New Credit/Debit Card</span>
                <select id="cybersource-use-card-method" name="payment[cybersource_subid]">
                    <option value="" class="use-new-card-control">New Credit/Debit Card</option>
                <?php foreach( $profiles as $profile ): ?>
                    <?php if(!$profile->getSubscriptionId() || $profile->getIsDefault()== 1 || !$profile->getData('saved_by_customer')) { continue; } ?>
                    <option class="use-saved-card-control" value="<?php echo $profile->getEncryptedSubscriptionId() ?>"><?php echo $this->getFullCcCardType( $profile->getData( 'card_type' ) ) ?> ends with <?php echo $profile->getData( 'last4no' ) ?></option>
                <?php endforeach ?>
                </select>
            </div>
            <div>
                 <?php foreach( $profiles as $profile ): ?>
                    <?php if( !$profile->getSubscriptionId() || $profile->getIsDefault()== 1 ) { continue; } ?>
                    <input type="hidden" id="address_<?php echo $profile->getEncryptedSubscriptionId() ?>" value="<?php echo $profile->getData('address_id') ?>" />
                <?php endforeach ?>
            </div>
        </li>
    <?php endif ?>
    <div class="use-new-card-wrapper">
        <li>
            <label for="<?php echo $_code ?>_cc_type" class="required"><em>*</em><?php echo $this->__('Credit Card Type') ?></label>
            <div class="input-box">
                <div class="totsy-selective-input-box middle-length">
                <span><?php echo $this->__('--Please Select--') ?></span>
                <select id="<?php echo $_code ?>_cc_type" name="payment[cc_type]" class="required-entry validate-cybsersource-cc-type-select">
                <?php $_ccType = $this->getInfoData('cc_type') ?>
                <?php foreach ($this->getCcAvailableTypes() as $_typeCode => $_typeName): ?>
                    <option value="<?php echo $_typeCode ?>" <?php if($_typeCode==$_ccType): ?>selected="selected"<?php endif ?>><?php echo $_typeName ?></option>
                <?php endforeach ?>
                </select>
                </div>
            </div>
        </li>
        <li>
            <label for="<?php echo $_code ?>_cc_number" class="required"><em>*</em><?php echo $this->__('Credit Card Number') ?></label>
            <div class="input-box">
                <input type="text" id="<?php echo $_code ?>_cc_number" name="payment[cc_number]" title="<?php echo $this->__('Credit Card Number') ?>" class="input-text validate-cc-number validate-cc-type" value="" />
            </div>
        </li>
        <li>
            <label for="<?php echo $_code ?>_expiration" class="required"><em>*</em><?php echo $this->__('Expiration Date') ?></label>
            <div class="input-box">
                <div class="v-fix right-margin">
                    <div class="totsy-selective-input-box short-length">
                    <span><?php echo $this->__('Month') ?></span>
                        <select id="<?php echo $_code ?>_expiration" name="payment[cc_exp_month]" class="month validate-cc-exp required-entry">
                        <?php $_ccExpMonth = $this->getInfoData('cc_exp_month') ?>
                        <?php foreach ($this->getCcMonths() as $k=>$v): ?>
                            <option value="<?php echo $k?$k:'' ?>" <?php if($k==$_ccExpMonth): ?>selected="selected"<?php endif ?>><?php echo $v ?></option>
                        <?php endforeach ?>
                        </select>
                    </div>
                </div>
                <div class="v-fix">
                    <div class="totsy-selective-input-box short-length">
                    <span><?php echo $this->__('Year') ?></span>
                        <?php $_ccExpYear = $this->getInfoData('cc_exp_year') ?>
                        <select id="<?php echo $_code ?>_expiration_yr" name="payment[cc_exp_year]" class="year required-entry">
                        <?php foreach ($this->getCcYears() as $k=>$v): ?>
                            <option value="<?php echo $k?$k:'' ?>" <?php if($k==$_ccExpYear): ?>selected="selected"<?php endif ?>><?php echo $v ?></option>
                        <?php endforeach ?>
                        </select>
                    </div>
                </div>
            </div>
        </li>
        <?php if($this->hasVerification()): ?>
        <li>
            <label for="<?php echo $_code ?>_cc_cid" class="required"><em>*</em><?php echo $this->__('Card Verification Number') ?></label>
            <div class="input-box">
                <div class="v-fix">
                    <input type="text" title="<?php echo $this->__('Card Verification Number') ?>" class="input-text cvv required-entry validate-cc-cvn" id="<?php echo $_code ?>_cc_cid" name="payment[cc_cid]" value="" />
                </div>
            </div>
        </li>
        <li>
            <label for="<?php echo $_code ?>_cc_save"><?php echo $this->__(' Save this Credit Card ?') ?></label>
            <div class="check-box">
                <div class="v-fix">
                    <input type="checkbox" value="1" name="payment[saved_by_customer]" id="<?php echo $_code ?>_saved" />
                </div>
            </div>
        </li>
        <?php endif; ?>
        <?php if ($this->hasSsCardType()): ?>
        <li id="<?php echo $_code ?>_cc_type_ss_div">
            <ul class="inner-form">
                <li class="form-alt">
                    <label for="<?php echo $_code ?>_issue" class="required"><em>*</em><?php echo $this->__('Switch/Solo/Maestro(UK Domestic) Only') ?></label>
                </li>
                <li>
                    <label for="<?php echo $_code ?>_cc_issue"><?php echo $this->__('Issue Number') ?></label>
                    <div class="input-box">
                        <input type="text" title="<?php echo $this->__('Issue Number') ?>" class="input-text cvv validate-cc-ukss" id="<?php echo $_code ?>_cc_issue" name="payment[cc_ss_issue]" value="" />
                    </div>
                </li>
                <li>
                    <label for="<?php echo $_code ?>_start_month"><?php echo $this->__('Start Date') ?></label>
                    <div class="input-box">
                        <div class="v-fix">
                            <div class="totsy-selective-input-box short-length">
                            <span><?php echo $this->__('Month') ?></span>
                            <select id="<?php echo $_code ?>_start_month" name="payment[cc_ss_start_month]" class="month validate-cc-ukss">
                            <?php $_ccStartMonth = $this->getInfoData('cc_ss_start_month') ?>
                            <?php foreach ($this->getCcMonths() as $k=>$v): ?>
                                <option value="<?php echo $k?$k:'' ?>" <?php if($k==$_ccStartMonth): ?>selected="selected"<?php endif ?>><?php echo $v ?></option>
                            <?php endforeach ?>
                            </select>
                            </div>
                        </div>
                        <div class="v-fix">
                            <div class="totsy-selective-input-box short-length">
                            <span><?php echo $this->__('Year') ?></span>
                            <select id="<?php echo $_code ?>_start_year" name="payment[cc_ss_start_year]" class="year validate-cc-ukss">
                            <?php $_ccStartYear = $this->getInfoData('cc_ss_start_year') ?>
                            <?php foreach ($this->getSsStartYears() as $k=>$v): ?>
                                <option value="<?php echo $k?$k:'' ?>" <?php if($k==$_ccStartYear): ?>selected="selected"<?php endif ?>><?php echo $v ?></option>
                            <?php endforeach ?>
                            </select>
                            </div>
                         </div>
                    </div>
                </li>
                <li class="adv-container"></li>
            </ul>
            <script type="text/javascript">
            var SSChecked<?php echo $_code ?> = function() {
                var elm = $('<?php echo $_code ?>_cc_type');
                if (elm.value=='SO' || elm.value=='SM') {
                    $('<?php echo $_code ?>_cc_type_ss_div').show();
                } else {
                    $('<?php echo $_code ?>_cc_type_ss_div').hide();
                }
            };
            Event.observe($('<?php echo $_code ?>_cc_type'), 'change', SSChecked<?php echo $_code ?>);
            SSChecked<?php echo $_code ?>();
            </script>
        </li>
        <?php endif; ?>
    </div>
</ul>
<script type="text/javascript">
// @TODO: should abstract this out to hpcheckout.js
// disable billing address form controls for saved credit card
jQuery( document ).ready( function($) {
	// cache jQuery objects
	var $billAddySelect = $("#billing-address-select");
	var $newCardWrap = $('.use-new-card-wrapper');
	var $newCardCtrls = $( 'input, select', '.use-new-card-wrapper' );
	var $selectUIWraps = $('.totsy-selective-input-box', '#hpcheckout-billing-wrapper');
	var $billFormInputs = $('#hpcheckout-billing-form :input');
    $( 'select#cybersource-use-card-method' ).change( function(){
        if( $( this ).val() == '' ) {
            $newCardWrap.show();
            $newCardCtrls.removeAttr( 'disabled' );
            $selectUIWraps.removeClass('disabled');
            $billAddySelect.removeAttr('disabled');
            //Enable Billing Inputs if credit card not selected
            $billFormInputs.each(function(i) {
                $(this).removeAttr('disabled');
            });
        } else {
			$newCardWrap.hide();
			$newCardCtrls.attr( 'disabled', 'disabled' ); // disable new card controls
			$selectUIWraps.addClass('disabled'); // 'disable' select UI wrappers
			
			if($("#address_" + $( this ).val()).val()) {
			    $billAddySelect.val($("#address_" + $( this ).val()).val()).change();
			    //Block Billing Inputs if credit card selected
			    $billFormInputs.each(function(i) {
			        if($(this).attr('id') != 'button_ship_to') {
			            $(this).attr('disabled','disabled');
			        }
			    });
			    $billAddySelect.attr('disabled','disabled');
			} else {
			    $billAddySelect.removeAttr('disabled');
			    $billFormInputs.each(function(i) {
			        $(this).removeAttr('disabled');
			    });
			}
        }
    });
});
</script>