<?php 
	$customer = Mage::getSingleton('customer/session')->getCustomer();
	$id = $customer->getId(); 
	$paymentCollection = Mage::getModel('paymentfactory/profile')->loadByCustomerId($id);
	$counter = 0;
?>

<div class="page-title">
	<h1>My Credit Cards</h1>
	<div class="add-new-card">
		<p class="add-new-card-button">Add a new credit card</p>
		<script type="text/javascript">
			jQuery(document).ready(function(){
				jQuery(".add-new-card-button").click( function() {
					jQuery(".add-new-card-form").fadeIn();
					jQuery(this).hide();
				});
				jQuery(".add-new-card-close").click( function() {
					jQuery(".add-new-card-form").fadeOut();
					jQuery(".add-new-card-button").show();
				});
			})
		</script>
		<div class="add-new-card-form" style="display:none;">
			<?php echo $this->getChildHtml('credit_cards_form');?>
			<p class="add-new-card-close" >Close</p>
		</div>
	</div>
</div>

<div class="cards-info">
	<h2></h2>
	<?php if(count($paymentCollection)!=0):?>
	<ul>
	<?php foreach($paymentCollection as $payment):
			$type = $payment->getData('card_type');
			switch ($type) {
		    case "SO":
		       $cardType = 'Solo';
		       break;
		    case "SM":
		        $cardType = 'Maestro/Switch';
		        break;
		    case "VI":
		       $cardType = 'Visa';
		       break;
		    case "MC":
		       $cardType = 'Master Card';
		       break;       
		    case "AE":
		       $cardType = 'American Express';
		       break;	
		    case "DI":
		       $cardType = 'Discovery';
		       break;	
		    case "JCB":
		       $cardType = 'JCB';
		       break;	
		    case "LASER":
		       $cardType = 'LASER';
		       break;	}
		   	$counter++;
		    
	?>
	<li>
		<ul class="cards_item">
		<form action="<?php echo $this->getBaseUrl();?>paymentfactory/index/delete/" method="post" id="payment_edit_form">
			<li class="card_type"><?php echo $counter;?>.<?php echo $cardType ?></li>
			<li>xxxxxxxxxxxx<?php echo $payment->getData('last4no')?></li>
			<li><?php echo $payment->getData('expire_year').'-'.$payment->getData('expire_month')?></li>
			<input type="hidden" name="entity_id" id="id" value="<?php echo $payment->getData('entity_id') ?>"  class="input-text hidden" /></td>
			<li><button class="button general top" type="submit"><span><span>Delete</span></span></button></li>
		</form>
		</ul>
	</li>
	<?php endforeach;?>
	</ul>
	<?php else:?>
	<h2>You don't have a saved credit card with your account.</h2>
	<?php endif;?>
</div>