<?php 
    $customer = Mage::getSingleton('customer/session')->getCustomer();
    $id = $customer->getId(); 
    $paymentCollection = Mage::getModel('paymentfactory/profile')->loadByCustomerId($id);
?>
<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<div class="page-title">
    <h1>My Credit Cards</h1>
    <div class="add-new-card">
        <p class="add-new-card-button">Add a new credit card</p>
        <script type="text/javascript">
            jQuery(document).ready(function(){
                jQuery(".add-new-card-button").click( function() {
                    jQuery(".add-new-card-form").fadeIn();
                    jQuery(this).hide();
                });
                jQuery(".add-new-card-close").click( function() {
                    jQuery(".add-new-card-form").fadeOut();
                    jQuery(".add-new-card-button").show();
                });
            })
        </script>
        <div class="add-new-card-form" style="display:none;">
            <?php echo $this->getChildHtml('credit_cards_form');?>
            <p class="add-new-card-close" >Close</p>
        </div>
    </div>
</div>

<div class="cards-info">
<?php if(count($paymentCollection)!=0):?>
        <?php foreach($paymentCollection as $payment):
                        $type = $payment->getData('card_type');
                        switch ($type) {
                            case "VI":
                                $creditCardImage = 'cc_visa.gif';
                                $cardType = 'Visa';
                                break;
                            case "MC":
                                $creditCardImage = 'cc_mastercard.gif';
                                $cardType = 'Master Card';
                                break;
                            case "AE":
                                $creditCardImage = 'cc_amex.gif';
                                $cardType = 'American Express';
                                break;
                        }
        ?>
        <?php if($payment->getIsDefault()== 0):?>
        <div style='border:1px solid #DDD'>
        <table width="650" border="0" cellspacing="0" cellpadding="0" style="margin: 10px;">
            <tr>
                <td width="9%" align="left">
                <img src="<?php echo $this->getSkinUrl('images/' . $creditCardImage)?>"> 
                </td>            
                <td width="71%">
                    <?php echo $cardType?> ending in <strong><?php echo $payment->getData('last4no')?></strong>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                    expires <strong><?php echo $payment->getData('expire_month');?>/<?php echo $payment->getData('expire_year');?></strong>
                </td>
                <td width="2%" align="right">
                    <a href="<?php echo $this->getBaseUrl();?>paymentfactory/index/delete/?entity_id=<?php echo $payment->getData('entity_id');?>" id="remove_<?php echo $payment->getData('entity_id');?>" title="Remove Credit Card" class="delete-new-card-button">Delete</a>
                </td>
            </tr>
        <?php if($payment->getData('address_id')):?>
             <tr>
                <td width="10%" align="left"></td>
            <?php $address_id = $payment->getData('address_id'); ?>
            <td width="90%">
            <table width="100%" cellpadding="0" cellspacing="0">
                <tr>
                    <td width="141" valign="top">Cardholder Name:</td>
                    <td width="281"><?php echo $this->htmlEscape($this->getAddress($address_id)->getFirstname()); ?> <?php echo $this->htmlEscape($this->getAddress($address_id)->getLastname()); ?></td>
                </tr>
                <tr>
                    <td valign="top">Billing Address:</td>
                    <td><?php echo $this->htmlEscape($this->getAddress($address_id)->getStreet(1)); ?>
                        <?php if($this->getAddress($address_id)->getStreet(1)): ?>
                            <?php echo $this->htmlEscape($this->getAddress($address_id)->getStreet(2)); ?><br />
                        <?php endif ?>
                        <?php echo $this->htmlEscape($this->getAddress($address_id)->getCity()); ?>, <?php echo $this->htmlEscape($this->getAddress($address_id)->getRegion()); ?> <?php echo $this->htmlEscape($this->getAddress($address_id)->getPostcode()); ?>
                    </td>
                </tr>
            </table>
            </td>
            </tr>
        <?php endif; ?>
     </table>
     </div>
    <?php endif;?>
    <?php endforeach;?>
<?php else:?>
    <h2>You don't have a saved credit card with your account.</h2>
<?php endif;?>
</div>