<?php

$order = Mage::registry('current_order');

require("dev/sociablelabs/sociable_signer.php");

$items_for_socialable_page_key = array();
$items_for_socialable_mos_keys = array();

$items = $order->getAllVisibleItems();

foreach ( $items as $itemId => $item ) {

    $product = Mage::getModel('catalog/product')->load($item->getProductId());

    $purchase_key = array();
    $mos_key = array();

    $purchase_key['id'] = array("id"=>$item->getId(), "type"=>"product", "price"=>array("actual_paid"=>$item->getPrice(), "currency"=>"USD"));

    $mos_key['id'] = array(array("id"=>$item->getId(), "type"=>"product"));
    $mos_key['name'] = array(array("name"=> $item->getName()));
    $mos_key['primary_tag'] = $product->getCategory()->name;
    $mos_key['tags'] = array("ordered_item",$product->getId(),$product->getName());
    $mos_key['url'] = array("detail"=>$product->getProductUrl(), "picture"=>array("primary"=>$product->getProductUrl(), "primary_secure"=>str_replace("http", "https", $product->getProductUrl())));

    array_push($items_for_socialable_purchase_key,$purchase_key);
    array_push($items_for_socialable_mos_keys,$mos_key);
}

$rondavu_data =array("config"=>array("version"=>"1.2") ,
    "user"=>array("id"=>array(array("id"=> Mage::getSingleton('customer/session')->getCustomerId(),"type"=>"totsy")),
        "tracking" =>array(array("name" =>"refId","
           value" =>"refrerral_code"))),
    "page" =>array("tags" =>array("order_confirmation"),
        "actions" =>array("purchase" =>array("order_id" =>$this->getOrderId(),"total"=>$order->getData('grand_total'),"currency" =>"USD","items"=> $items_for_socialable_purchase_keys,
                "price" =>array("actual_paid" =>$order->getData('grand_total'),"currency"=>"USD")))),
    "primary_mo"=>array("id" =>array(array("id"=>"order_confirmation","type"=>"page")) ,
        "name" =>array(array("name" =>"Totsy")) ,
        "url" =>array("detail" =>"http//www.totsy.com","picture"=>array("primary"=>"http//www.totsy.com/img/logo-125x77.png","primary_secure" =>
                "https://www.totsy.com/img/logo-125x77.png"))),
    "mos" => $items_for_socialable_mos_keys
);

// declare a path to the key
$key_path = "dev/sociablelabs/sign_private_key";
$socialable_labs_output = rondavu_sign($rondavu_data, $key_path);

?>
<script type="text/javascript">
    socialableLabsOutput = <?php echo $socialable_labs_output ?>;
</script>

<?php echo $this->getChildHtml('sociable.footer.pixel'); ?>