<?php
/**
 * Harapartners
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Harapartners License
 * that is bundled with this package in the file LICENSE_EE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.Harapartners.com/license
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@Harapartners.com so we can send you a copy immediately.
 *
 */
?>
<div class="validation-form-container">
	<?php $customer = Mage::getSingleton('customer/session')->getCustomer();?>
	<form id="auto-form" name="validation-check-form" method="post" action="<?php echo $this->getBaseUrl() . 'customer/revalidate/validationcheckpost'?>">
		<div class="fieldset">
			<h2>Require Validation</h2>
			<p><?php echo $this->__("Sorry, for the interruption! You have been inactive for 15 minutes. Please sign in again to continue shopping. If you need help with your password, please click ")?><a href="<?php echo $this->getUrl('customer/account/forgotpassword')?>"><?php echo $this->__("Here")?></a><?php echo $this->__(" to forgot password page.")?></p>
			<ul class="form-list emailpassword">
				<li>
					<label for="email" class="required">Email <em>*</em></label>
					<div class="input-box">
						<input name="login[username]" id="email" type="text" class="input-text ui-input-text ui-body-c ui-corner-all ui-shadow-inset required-entry validate-email" title="Email Address" value="<?php echo $customer->getEmail();?>"/>
					</div>
				</li>
				<li>
					<label for="password" class="required">Password <em>*</em></label>
					<div class="input-box">
						<input name="login[password]" id="password" autocomplete="off" type="password" class="input-text ui-input-text ui-body-c ui-corner-all ui-shadow-inset required-entry validate-password" title="Password" value=""/>
						<input name="mobile" id="mobile" style="display: none;" value="1"/>
					</div>
				</li>
			</ul>
			<div class="buttons-set form-buttons btn-only">
				<button type="submit" class="button" name="send" id="send2">
					<div class="sign-in-button">Submit</div>
				</button>
			</div>
		</div>
	</form>
	<script type="text/javascript">
		jQuery(document).ready(function(){
			jQuery("#auto-form").submit();
		})
	</script>
</div>