<?php
	$defaultTimezone = date_default_timezone_get();
	$mageTimezone = Mage::getStoreConfig(Mage_Core_Model_Locale::XML_PATH_DEFAULT_TIMEZONE);
	date_default_timezone_set($mageTimezone);
	$sortDate = now("Y-m-d");
	date_default_timezone_set($defaultTimezone);
	$storeId = Mage::app()->getStore()->getId();
	$sortentryLive = Mage::getModel('categoryevent/sortentry')->loadByDate($sortDate, $storeId, false)->getLiveQueue();
	$liveCategoryInfoArray = json_decode($sortentryLive, true);
	$i = 1;
?>
	
<?php  foreach ($liveCategoryInfoArray as $liveCategory): ?>
	<?php 
	
		if(isset($liveCategory['image'])){
			//$containerProductInfo['small_image'] = $mediaBaseDir . str_ireplace('/', DS, $productInfo['small_image']);    //it call from file system like F:\www\totsy\media\catalog\product\n\e\newborn_tiered_dots_top_2pc_diaper_set.jpg
			if ($liveCategory['image'] != 'no_selection'){
				$smallImage = Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).'catalog/category/'.$liveCategory['image'];
			}else {
				$smallImage['image'] = Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).'catalog/product/placeholder/small_image.jpg';
			}
		}
	?>
	<div class="big-div-not-found">
	<a href="<?php echo $this->getBaseUrl().$liveCategory['url_path']?>">
		
			<img width="108px" height="125px" src="<?php echo $smallImage; ?>" />
			<span class="not-found-names"><?php echo $liveCategory['name'] ?></span>
		
	</a>
	</div>
	<?php
		if ($i >= 4){
			break;
		}
		$i++;
	?>
	<?php endforeach; ?>
	

			