<?php
/**
 * Harapartners
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Harapartners License
 * that is bundled with this package in the file LICENSE_EE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.Harapartners.com/license
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@Harapartners.com so we can send you a copy immediately.
 *
 */
?>
<style>
/* Temporary Eric */
h4 {
    color:#000;
    /*text-transform: uppercase;*/
}

</style>
<?php
/**
 * Catalog index list template
 * Load Top, Live, Upcoming events
 * 
 */
?>
<?php    
    $indexDataObj 	= 	$this->getIndexDataObject();
    $baseUrl 		= 	Mage::getBaseUrl();
    $maxPerSend 	= 	0;
    $timer 			= 	0;
    $topArray 		= 	'';
    $liveArray 		= 	'';
    $upcomingArray  = 	'';	
    if ( $indexDataObj->hasData('toplive') ){
        $topArray = $indexDataObj->getData('toplive');
        $topArray = array(); //Harapartners, yang: "temporarily" block the top events
    }
    if ( $indexDataObj->hasData('live_queue') ){
        $liveArray = json_decode($indexDataObj->getData('live_queue'), true);
    }
    if ( $indexDataObj->hasData('upcoming_queue') ){
        $upcomingArray = json_decode($indexDataObj->getData('upcoming_queue'), true);
    }
?>

<div class="catalog-events-container">
    <div class="live-events-container">

    <?php // Live Events ?>
    <?php if (!!$liveArray && !empty($liveArray)) : ?>
        <section id="events-live" class="events-grid">
            <ul class="thumbnails">
            <?php foreach ($liveArray as $live): ?>
                <?php
                    $endcountRaw = strtotime($live['event_end_date']);
                    $endcount = date("F j, Y, G:i:s", $endcountRaw);
                    $hasProduct = $this->countCategoryProducts($live['entity_id']);
                    $eventDepts = $live['department_label'];
                    $eventAges = $live['age_label'];
                    $maxDiscount = $live['max_discount_pct'];
                    if(!($url = Mage::getModel('core/url_rewrite')->setStoreId(Mage::app()->getStore()->getId())->loadByIdPath('category/'.$live['entity_id'])->getRequestPath())) {
                        $url = 'catalog/category/view/id/'.$live['entity_id'];
                    }
                    $url = Mage::getBaseUrl().$url;
                ?>
                <?php if ($hasProduct): ?>
                    <li class="span4 catalog-event event-counter-<?php echo $timer;?>">
                        <a href="<?php echo $url; ?>" class="thumbnail">
                            <hgroup>
                                <h4 class="ellipsis"><?php echo $live['name'];?></h4>
                                <div class="maxDiscount"><em>up to <span><strong><?php echo $maxDiscount; ?>%</strong> off</span></em></div>
                                <!-- <h6><?php //echo $live['short_description'];?></h6> -->
                            </hgroup>
                            <div class="more">
                                <div class="more-content">
                                    <p id="time1-<?php echo $timer ?>" class="counter" data-enddate="<?php echo $endcount?>" data-status="live" data-id="<?php echo $timer ?>" data-countertype="event-counter"></p>
                                    <span class="btn btn-primary">Shop Now!</span>
                                </div>
                            </div>
                            <?php
                                $imgFile = (isset($live['small_image']))
                                ? BP . DS . 'media' . DS . 'catalog' . DS . 'category' . DS . $live['small_image']
                                : BP . DS . 'skin' . DS . 'frontend' . DS . 'enterprise ' . DS . 'bootstrap' . DS . 'images' . DS . 'catalog' . DS . 'product' . DS . 'placeholder' . DS . 'small_image.jpg';
                            ?>
                            <span class="event-link">
                                <img src="<?php echo Mage::helper('service/image')->loadImageFile($imgFile)->resize(310)->keepFrame(FALSE); ?>" width="310" height="310" alt="<?php echo $live['name'];?>" />
                            </span>
                            
                            <?php $timer++; ?>
                        </a>
                    </li>
                <?php endif; ?>
            <?php endforeach; ?>
            </ul>
        </section><!-- /#events-live -->
    <?php endif; ?>
    
    <?php // ENDING SOON - not functioning, no $endingArray exists - just a placeholder var and code for now ?>
    
    <?php // include banner if it is enabled
    $bannerActive = Mage::getModel('cms/block')->load('home_banner')->getIsActive();
    if ($bannerActive) {
        echo '<div class="banner">';
        echo $this->getLayout()->createBlock('cms/block')->setBlockId('home_banner')->toHtml();
        echo '</div>';
    }
?>
    <?php if (!$bannerActive) : ?>
<!--
            <header class="page-header">
                <h2><img src="/skin/frontend/enterprise/bootstrap/images/iconmonstr-time-8-icon.png" width="50" /> Today's Sales</h2>
            </header>
-->
        <?php endif; ?>
    <?php $endingArray = '1'; ?>
    <?php if (!!$endingArray && !empty($endingArray)): ?>
        <section id="events-ending" class="events-grid">
            <header class="page-header">
                <h2>Sales Ending Soon...</h2>
            </header>
            <ul>
            <?php // foreach block here ?>
            </ul>
        </section><!-- /#events-ending -->
    <?php endif; ?>

    <?php // Upcoming Events ?>
    <?php if (!!$upcomingArray && !empty($upcomingArray)): ?>
        <section id="events-upcoming" class="events-grid">
            <header class="page-header">
                <h2>Upcoming Sales</h2>
            </header>
            <ul class="thumbnails">
            <?php foreach ($upcomingArray as $up): ?>
                <?php
                    $endcountRaw = strtotime($up['event_start_date']);
                    $endcount = date("F j, Y, G:i:s", $endcountRaw);
                    if(!($url = Mage::getModel('core/url_rewrite')->setStoreId(Mage::app()->getStore()->getId())->loadByIdPath('category/'.$up['entity_id'])->getRequestPath())) {
                        $url = 'catalog/category/view/id/'.$up['entity_id'];
                    }
                    $url = Mage::getBaseUrl().$url;
                ?>
                <li class="span2 alpha catalog-event up-event-counter-<?php echo $timer;?>">
                    <div class="thumbnail">
                        <hgroup>
                            <h5><a href="<?php echo $url; ?>"><?php echo $up['name'];?></a></h5>
                        </hgroup>
                        <?php
                            $imgFile = (isset($up['small_image']))
                            ? BP . DS . 'media' . DS . 'catalog' . DS . 'category' . DS .
                            $up['small_image']
                            : BP . DS . 'skin' . DS . 'frontend' . DS . 'enterprise ' . DS . 'bootstrap' . DS . 'images' . DS . 'catalog' . DS . 'product' . DS . 'placeholder' . DS . 'small_image.jpg';
                        ?>
                        <a class="event-link" href="<?php echo $url; ?>">
                            <img src="<?php echo Mage::helper('service/image')->loadImageFile($imgFile)->resize(165)->keepFrame(FALSE); ?>" width="165px" height="171" alt="<?php echo $up['name'];?>" />
                        </a>
                        <?php $timer++; ?>
                        <p class="opens_in counter" id="time2-<?php echo $timer ?>" data-enddate="<?php echo $endcount?>" data-status="upcoming" data-countertype="up-event-counter"  data-id="<?php echo $timer ?>"></p>
                    </div>
                </li>
            <?php endforeach; ?>
            </ul>
        </section><!-- /#events-upcoming -->
    <?php endif; ?>

    </div><!-- /.live-events-container -->
</div><!-- /.catalog-events-container -->

<script type="text/javascript">
    jQuery(".counter").each(function(){
        var saleTime = new Date(jQuery(this).data('enddate'));
        var id = jQuery(this).data('id');
        jQuery(this).countdown({
            date: saleTime,
            htmlTemplate: getTimerHtml(jQuery(this).data('status'), jQuery(this).data('enddate')),
            leadingZero: true,
            direction: 'down',
            onComplete: function( event ){
                jQuery(this).html("Completed");
                elem_class = "." + jQuery(this).data('countertype') + '-' + id;
               jQuery(elem_class).remove();
            }

        });
    });
</script>
