<?php
/**
 * Harapartners
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Harapartners License
 * that is bundled with this package in the file LICENSE_EE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.Harapartners.com/license
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@Harapartners.com so we can send you a copy immediately.
 *
 */
?>

<?php
/**
 * Catalog index list template
 * Load Top, Live, Upcoming events
 * 
 */
?>
<?php
    $indexDataObj 	= 	$this->getIndexDataObject();
    $baseUrl 		= 	Mage::getBaseUrl();
    $maxPerSend 	= 	0;
    $timer 			= 	0;
    $topArray 		= 	'';
    $liveArray 		= 	'';
    $upcomingArray  = 	'';	
    if ( $indexDataObj->hasData('top_live_queue') ){
        $topArray = json_decode($indexDataObj->getData('top_live_queue'),true);
    } 
    if ( $indexDataObj->hasData('live_queue') ){
        $liveArray = json_decode($indexDataObj->getData('live_queue'), true);
    }
    if ( $indexDataObj->hasData('upcoming_queue') ){
        $upcomingArray = json_decode($indexDataObj->getData('upcoming_queue'), true);
    }
?>
<?php // include banner if it is enabled
    $bannerActive = Mage::getModel('cms/block')->load('home_banner')->getIsActive();
    if ($bannerActive) { ?>
    
<!-- Carousel
    ================================================== -->
    <div id="myCarousel" class="carousel slide">
      <div class="carousel-inner">
        <div class="item active">
          <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('home_banner')->toHtml(); ?>
          <div class="container">
            <div class="carousel-caption">
              <h1>Example headline.</h1>
            </div>
          </div>
        </div>
        <div class="item">
          <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('home_banner')->toHtml(); ?>
          <div class="container">
            <div class="carousel-caption">
              <h1>Another example headline.</h1>
            </div>
          </div>
        </div>
        <div class="item">
          <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('home_banner')->toHtml(); ?>
          <div class="container">
            <div class="carousel-caption">
              <h1>One more for good measure.</h1>
            </div>
          </div>
        </div>
      </div>
      <a class="left carousel-control" href="#myCarousel" data-slide="prev">&lsaquo;</a>
      <a class="right carousel-control" href="#myCarousel" data-slide="next">&rsaquo;</a>
    </div><!-- /.carousel -->
<?php } ?>
<h2>Default thumbnails</h2>
          <p>By default, Bootstrap's thumbnails are designed to showcase linked images with minimal required markup.</p>
          <div class="container">
            <ul class="thumbnails">
              <li class="span3">
                <a href="#" class="thumbnail">
                  <img data-src="holder.js/260x180" alt="">
                </a>
              </li>
              <li class="span3">
                <a href="#" class="thumbnail">
                  <img data-src="holder.js/260x180" alt="">
                </a>
              </li>
              <li class="span3">
                <a href="#" class="thumbnail">
                  <img data-src="holder.js/260x180" alt="">
                </a>
              </li>
              <li class="span3">
                <a href="#" class="thumbnail">
                  <img data-src="holder.js/260x180" alt="">
                </a>
              </li>
              <li class="span3">
                <a href="#" class="thumbnail">
                  <img data-src="holder.js/260x180" alt="">
                </a>
              </li>
              <li class="span3">
                <a href="#" class="thumbnail">
                  <img data-src="holder.js/260x180" alt="">
                </a>
              </li>
              <li class="span3">
                <a href="#" class="thumbnail">
                  <img data-src="holder.js/260x180" alt="">
                </a>
              </li>
              <li class="span3">
                <a href="#" class="thumbnail">
                  <img data-src="holder.js/260x180" alt="">
                </a>
              </li>
              <li class="span3">
                <a href="#" class="thumbnail">
                  <img data-src="holder.js/260x180" alt="">
                </a>
              </li>
              <li class="span3">
                <a href="#" class="thumbnail">
                  <img data-src="holder.js/260x180" alt="">
                </a>
              </li>
            </ul>
          </div>
<div class="catalog-events-container container">
    <div class="live-events-container">
    <?php // Live Events ?>
    <?php if (!!$topArray && !empty($topArray)) : ?>
        <section id="events-live" class="tedhack events-grid">
        <?php if (!$bannerActive) : ?>
<!--
            <header class="page-header">
                <h2><img src="/skin/frontend/enterprise/bootstrap/images/iconmonstr-time-8-icon.png" width="50" /> Today's Sales</h2>
            </header>
-->
        <?php endif; ?>
            <ul class="thumbnails">
            <?php foreach ($topArray as $top): ?>
                <?php if(!isset($top['club_only_event']) || !$top['club_only_event']) : ?>
                <?php
                    $endcountRaw = strtotime($top['event_end_date']);
                    $endcount = date("F j, Y, G:i:s", $endcountRaw);
                    $hasProduct = $this->countCategoryProducts($top['entity_id']);
                    $eventDepts = $top['department_label'];
                    $eventAges = $top['age_label'];
                    $maxDiscount = $top['max_discount_pct'];
                    if(!($url = Mage::getModel('core/url_rewrite')->setStoreId(Mage::app()->getStore()->getId())->loadByIdPath('category/'.$top['entity_id'])->getRequestPath())) {
                        $url = 'catalog/category/view/id/'.$top['entity_id'];
                    }
                    $url = Mage::getBaseUrl().$url;
                ?>
                <?php if ($hasProduct && $endcountRaw > Mage::getSingleton('core/date')->timestamp()): ?>
                    <li class="span4 catalog-event event-counter-<?php echo $timer;?>">
                        <a href="<?php echo $url; ?>" class="thumbnail">
                            <div class="more">
                                <div class="more-content">
                                    <p id="time1-<?php echo $timer ?>" class="counter" data-enddate="<?php echo $endcount?>" data-status="live" data-id="<?php echo $timer ?>" data-countertype="event-counter"></p>
                                    <span class="btn btn-primary">SHOP NOW</span>
                                </div>
                            </div>
                            <?php
                                $imgFile = (isset($top['small_image']))
                                ? BP . DS . 'media' . DS . 'catalog' . DS . 'category' . DS . $top['small_image']
                                : BP . DS . 'skin' . DS . 'frontend' . DS . 'enterprise ' . DS . 'bootstrap' . DS . 'images' . DS . 'catalog' . DS . 'product' . DS . 'placeholder' . DS . 'small_image.jpg';
                            ?>
                            <span class="event-link">
                                <img src="<?php echo Mage::helper('service/image')->loadImageFile($imgFile)->constrainOnly(false)->keepAspectRatio(TRUE)->keepFrame(FALSE)->resize(550,550) ?>" alt="<?php echo $top['name'];?>" />
                            </span>
                            
                            <?php $timer++; ?>
                        </a>
                  <div class="caption">
                    <h3 class="ellipsis"><?php echo $top['name'];?></h3>
                    <p class="up-to">up to <span><?php echo $maxDiscount; ?>% Off!</span></p>
                  </div>
                  
                    </li>
                <?php endif; ?>
                <?php endif; ?>
            <?php endforeach; ?>
            </ul>
        </section><!-- /#events-live -->
    <?php endif; ?>
    
    <?php // ENDING SOON - not functioning, no $endingArray exists - just a placeholder var and code for now ?>
    <?php if (!!$liveArray && !empty($liveArray)) : ?>
    <section id="events-ending" class="tedhack events-grid anchorHack">
        <header class="page-header">
                <h2>Hurry, Ending Soon</h2>
            </header>
            <ul class="thumbnails">
            <?php foreach ($liveArray as $live): ?>
                <?php if(!isset($live['club_only_event']) || !$live['club_only_event']) : ?>
                <?php
                    $endcountRaw = strtotime($live['event_end_date']);
                    $endcount = date("F j, Y, G:i:s", $endcountRaw);
                    $hasProduct = $this->countCategoryProducts($live['entity_id']);
                    $eventDepts = $live['department_label'];
                    $eventAges = $live['age_label'];
                    $maxDiscount = $live['max_discount_pct'];
                    if(!($url = Mage::getModel('core/url_rewrite')->setStoreId(Mage::app()->getStore()->getId())->loadByIdPath('category/'.$live['entity_id'])->getRequestPath())) {
                        $url = 'catalog/category/view/id/'.$live['entity_id'];
                    }
                    $url = Mage::getBaseUrl().$url;
                ?>
                <?php if ($hasProduct && $endcountRaw > Mage::getSingleton('core/date')->timestamp()): ?>
                    <li class="span3 catalog-event event-counter-<?php echo $timer;?>">
                        <a href="<?php echo $url; ?>" class="thumbnail">
                            <div class="more">
                                <div class="more-content">
                                    <p id="time1-<?php echo $timer ?>" class="counter" data-enddate="<?php echo $endcount?>" data-status="live" data-id="<?php echo $timer ?>" data-countertype="event-counter"></p>
                                    <span class="btn btn-primary">SHOP NOW</span>
                                </div>
                            </div>
                            <?php
                                $imgFile = (isset($live['small_image']))
                                ? BP . DS . 'media' . DS . 'catalog' . DS . 'category' . DS . $live['small_image']
                                : BP . DS . 'skin' . DS . 'frontend' . DS . 'enterprise ' . DS . 'bootstrap' . DS . 'images' . DS . 'catalog' . DS . 'product' . DS . 'placeholder' . DS . 'small_image.jpg';
                            ?>
                            <span class="event-link">
                                <img src="<?php echo Mage::helper('service/image')->loadImageFile($imgFile)->constrainOnly(false)->keepAspectRatio(TRUE)->keepFrame(FALSE)->resize(550,550) ?>" alt="<?php echo $live['name'];?>" />
                            </span>
                            
                            <?php $timer++; ?>
                        </a>
                        <div class="caption">
                    <h3 class="ellipsis"><?php echo $live['name'];?></h3>
                    <p class="up-to">up to <span><?php echo $maxDiscount; ?>% Off!</span></p>
                  </div>
                    </li>
                <?php endif; ?>
                <?php endif; ?>
            <?php endforeach; ?>
            </ul>
        </section><!-- /#events-live -->
    <?php endif; ?>

    <?php // Upcoming Events ?>
    <?php if (!!$upcomingArray && !empty($upcomingArray)): ?>
        <section id="events-upcoming" class="tedhack events-grid anchorHack">
            <header class="page-header">
                <h2>Upcoming Sales</h2>
            </header>
            <ul class="thumbnails">
            <?php foreach ($upcomingArray as $up): ?>
                <?php if(!isset($live['club_only_event']) || !$up['club_only_event']) : ?>
                <?php
                    $endcountRaw = strtotime($up['event_start_date']);
                    $endcount = date("F j, Y, G:i:s", $endcountRaw);
                    if(!($url = Mage::getModel('core/url_rewrite')->setStoreId(Mage::app()->getStore()->getId())->loadByIdPath('category/'.$up['entity_id'])->getRequestPath())) {
                        $url = 'catalog/category/view/id/'.$up['entity_id'];
                    }
                    $url = Mage::getBaseUrl().$url;
                ?>
                <li class="span2 catalog-event up-event-counter-<?php echo $timer;?>">
                    <div class="thumbnail">
                        <hgroup>
                            <h5><a href="<?php echo $url; ?>"><?php echo $up['name'];?></a></h5>
                        </hgroup>
                        <?php
                            $imgFile = (isset($up['small_image']))
                            ? BP . DS . 'media' . DS . 'catalog' . DS . 'category' . DS .
                            $up['small_image']
                            : BP . DS . 'skin' . DS . 'frontend' . DS . 'enterprise ' . DS . 'bootstrap' . DS . 'images' . DS . 'catalog' . DS . 'product' . DS . 'placeholder' . DS . 'small_image.jpg';
                        ?>
                        <a class="event-link" href="<?php echo $url; ?>">
                            <img src="<?php echo Mage::helper('service/image')->loadImageFile($imgFile)->resize(165)->keepFrame(FALSE); ?>" width="165px" height="171" alt="<?php echo $up['name'];?>" />
                        </a>
                        <?php $timer++; ?>
                        <p class="opens_in counter" id="time2-<?php echo $timer ?>" data-enddate="<?php echo $endcount?>" data-status="upcoming" data-countertype="up-event-counter"  data-id="<?php echo $timer ?>"></p>
                    </div>
                </li>
            <?php endif; ?>
            <?php endforeach; ?>
            </ul>
        </section><!-- /#events-upcoming -->
    <?php endif; ?>

    </div><!-- /.live-events-container -->
</div><!-- /.catalog-events-container -->
<div class="modal hide fade" id="myModal">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
    <h3>Marketing Greeting Could Go Here</h3>
  </div>
  <div class="modal-body">
    <p>invite your friends, do something else. </p>
  </div>
  <div class="modal-footer">
    <a href="#" class="btn">Close</a>
    <a href="#" class="btn btn-primary">Save changes</a>
  </div>
</div>
<script>
jQuery(window).load(function(){
        jQuery('#myModal').modal('show');
    });
</script>
<script type="text/javascript">
    jQuery(".counter").each(function(){
        var saleTime = new Date(jQuery(this).data('enddate'));
        var server_now = retrieveServertime();
        var timezone = -server_now.getTimezoneOffset()/60;
        var server_now = server_now.toString();
        var id = jQuery(this).data('id');
        jQuery(this).countdown({
            until: saleTime,
            layout: getTimerHtml(jQuery(this).data('status'), jQuery(this).data('enddate'), server_now),
            serverSync:retrieveServertime,
            tickInterval: 1, 
            alwaysExpire: true,
            timezone: timezone,
            onExpiry: function( event ){
                jQuery(this).html("Completed");
                elem_class = "." + jQuery(this).data('countertype') + '-' + id;
               jQuery(elem_class).remove();
            }
        });
    });

    function retrieveServertime() {
        var time = null;
        jQuery.ajax({
            url:"<?php echo Mage::getUrl('ajax/servertime/servertime', array('format' => 'string', '_query' => time())); ?>",
            async: false,
            cache: false,
            success: function(servertime) {
                servertime = jQuery.parseJSON(servertime);
                time =  servertime.time;
            },
            error:function () {
                time = "<?php echo date('F j, Y, G:i:s' , Mage::app()->getLocale()->storeTimeStamp(Mage::app()->getStore()->getId())); ?>";
            }
        });
        date = new Date(time);
        return date;
    }

</script>
