<?php
/**
 * Harapartners
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Harapartners License
 * that is bundled with this package in the file LICENSE_EE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.Harapartners.com/license
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@Harapartners.com so we can send you a copy immediately.
 * 
 */
?>

<?php
/**
 * Catalog index list template
 * Load Top, Live, Upcoming events
 *
 */
?>
<?php
    $indexDataObj 	= 	$this->getIndexDataObject();
    $baseUrl 		= 	Mage::getBaseUrl();
    $maxPerSend 	= 	0;
    $timer 			= 	0;
    $topArray 		= 	'';
    $liveArray 		= 	'';
    $upcomingArray  = 	'';
    if ( $indexDataObj->hasData('top_live_queue') ){
        $topArray = json_decode($indexDataObj->getData('top_live_queue'),true);
    }
    if ( $indexDataObj->hasData('live_queue') ){
        $liveArray = json_decode($indexDataObj->getData('live_queue'), true);
    }
    if ( $indexDataObj->hasData('upcoming_queue') ){
        $upcomingArray = json_decode($indexDataObj->getData('upcoming_queue'), true);
    }

    $liveArray = array_merge($topArray, $liveArray);
?>
<?php // include banner if it is enabled
    $bannerActive = Mage::getModel('cms/block')->load('home_banner')->getIsActive();
        echo '<div class="banner">';
        $banners = $this->getLayout()->createBlock('promotions/block')
                  ->setBlockId('promotions_banner_view')
                  ->setBlockPageName('home')
                  ->toHtml();
        echo $banners;
        echo '</div>';
?>

<div class="catalog-events-container">
    <div class="live-events-container">
        <section id="events-ending" class="tedhack events-grid anchorHack">
            <ul class="thumbnails">
<?php

foreach ($liveArray as $top):
    if(!isset($top['club_only_event']) || !$top['club_only_event']):
        $endcountRaw = strtotime($top['event_end_date']);
        $endcount = date("F j, Y, G:i:s", $endcountRaw);
        $eventDepts = $top['department_label'];
        $eventAges = $top['age_label'];
        $maxDiscount = $top['max_discount_pct'];
        if(!($url = Mage::getModel('core/url_rewrite')->setStoreId(Mage::app()->getStore()->getId())->loadByIdPath('category/'.$top['entity_id'])->getRequestPath())) {
            $url = 'catalog/category/view/id/'.$top['entity_id'];
        }
        $url = Mage::getBaseUrl().$url;

        if (($endcountRaw > Mage::getSingleton('core/date')->timestamp()) && $this->countCategoryProducts($top['entity_id'])):
?>
                <li class="span4 catalog-event event-counter-<?php echo $timer;?>">
                    <a href="<?php echo $url; ?>" class="thumbnail">
                        <div class="more">
                            <div class="more-content">
                                <p id="time1-<?php echo $timer ?>" class="counter" data-enddate="<?php echo $endcount?>" data-status="live" data-id="<?php echo $timer ?>" data-countertype="event-counter"></p>
                                <span class="btn btn-primary">SHOP NOW</span>
                            </div>
                        </div>
                        <?php
                        $imgFile = (isset($top['small_image']))
                            ? BP . DS . 'media' . DS . 'catalog' . DS . 'category' . DS . $top['small_image']
                            : BP . DS . 'skin' . DS . 'frontend' . DS . 'enterprise ' . DS . 'bootstrap' . DS . 'images' . DS . 'catalog' . DS . 'product' . DS . 'placeholder' . DS . 'small_image.jpg';
                        ?>
                        <span class="event-link">
                    <img src="<?php echo Mage::helper('service/image')->loadImageFile($imgFile)->constrainOnly(false)->keepAspectRatio(TRUE)->keepFrame(FALSE)->resize(550,550) ?>" alt="<?php echo $top['name'];?>" />
                </span>

                        <?php $timer++; ?>
                    </a>
                    <div class="caption">
                        <h3 class="ellipsis"><?php echo $top['name'];?></h3>
                    </div>
                </li>
<?php
        endif;
    endif;
endforeach;
?>
            </ul>
        </section><!-- /#events-ending -->
    </div><!-- /.live-events-container -->
</div><!-- /.catalog-events-container -->

<script type="text/javascript">
    jQuery(".counter").each(function(){
        var saleTime = new Date(jQuery(this).data('enddate'));
        var server_now = "<?php echo date('F j, Y, G:i:s' , Mage::app()->getLocale()->storeTimeStamp(Mage::app()->getStore()->getId())); ?>";
        var id = jQuery(this).data('id');
        jQuery(this).countdown({
            until: saleTime,
            layout: getTimerHtml(jQuery(this).data('status'), jQuery(this).data('enddate'), server_now),
            serverSync:retrieveServertime,
            tickInterval: 1,
            alwaysExpire: true,
            onExpiry: function( event ){
                jQuery(this).html("Completed");
                elem_class = "." + jQuery(this).data('countertype') + '-' + id;
               jQuery(elem_class).remove();
            }

        });
    });

    function retrieveServertime() {
        var time = null;
        jQuery.ajax({
            url:"<?php echo Mage::getUrl('ajax/servertime/servertime', array('format' => 'string')); ?>",
            async: false,
            success: function(servertime) {
                servertime = jQuery.parseJSON(servertime);
                time =  servertime.time;
            }, 
            error:function () {
                time = "<?php Mage::getModel('core/date')->timestamp(time()); ?>";
            }
        });
        date = new Date(time);
        return date;
    }
    <?php if(!empty($banners)){ ?>
        jQuery(document).ready(function() {
            jQuery('.carousel').carousel();
        });
    <?php } ?>
</script>
