<?php
/**
 * Harapartners
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Harapartners License
 * that is bundled with this package in the file LICENSE_EE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.Harapartners.com/license
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@Harapartners.com so we can send you a copy immediately.
 *
 */

$topNavDataObject = $this->getTopNavDataObject();
$categoryDataArray = $topNavDataObject->getData('category_product_complete_data'); 
$howMany = count($categoryDataArray);
?>

<div class="page-header">
    <h2><?php echo $topNavDataObject->getData('attr_text_label'); ?><small class="pull-right"><?php echo ' '.$howMany.' Sales Found';?></small></h2>
</div>

<script type="text/javascript">
shpn='<?php echo $topNavDataObject->getData('attr_text_label'); ?>'
</script>

<?php foreach($categoryDataArray as $category):?>
<?php if(!isset($category['club_only_event']) || !$category['club_only_event']) : ?>


    <div class="events-div">

<?php 
    $timerParam = $category['prepare_timer'];
    $endcount_lc = $timerParam['endcount_lc'];
    $timer = $timerParam['timer'];
?>
<div class="well">
    <h3 class="category-name"><?php echo $category['category_info']['name']; ?> <a href="<?php echo Mage::getBaseUrl().$category['category_info']['url_path']; ?>">View All</a> <small class="pull-right"><p class="the-topnav-timer counter" id="time-layer-<?php echo $timer ?>" data-enddate="<?php echo $endcount_lc?>" data-status="live" data-id="<?php echo $timer ?>" data-countertype="events-div"></p></small>
    </h3>
    <hr />
    <div class="category-products">
    <ul class="products-grid thumbnails">
        <?php $j=0; ?>
        <?php $nonSalableArray = array();?>        
        
        <?php $i=0; foreach ($category['product_list'] as $_product): ?>
        <?php $_description = array_key_exists('description',$_product) ? $_product['description'] : '';  ?>
        <?php $_is_salable = array_key_exists('is_salable',$_product) ? $_product['is_salable'] : 0;  ?>
        <?php if (empty($_product['url_path']) || !preg_match('/sales/',$_product['url_path'])){
            $_product['url_path'] = $_product['request_path'];
        }
//        $product = Mage::getModel('catalog/product')->load($_product['entity_id']);
        ?>
        <?php if ($_is_salable): ?>
        <li class="span2" style="width:146px;">
        <div class="thumbnail">
        <a href="<?php echo Mage::getBaseUrl().$_product['url_path']; ?>" title="<?php echo $_product['name']; ?>" class="product-image"><img src="<?php echo Mage::helper('catalog/image')->init(Mage::getModel('catalog/product'),'small_image',$_product['small_image'])->resize(148); ?>" width="148" alt="<?php echo $_product['name']; ?>" /></a>
        <h5 class="product-name ellipsis">
            <?php echo $_product['name']; ?>
        </h5>
        <?php //echo $this->getPriceHtml($_product, true) ?>
        <div class="price-box">
        <span class="regular-price" id="product-price-<?php echo $_product['entity_id']; ?>">
        <?php $price = (isset($_product['special_price']))?$_product['special_price']:$_product['price']?>
        <span class="price">$<?php echo number_format($price,2,'.',''); ?></span>
        </span>
        </div>
        
        </div>
        </li>
        </li>
        <?php 
            $i++; 
            $j = $i;
                if ($i==6){
            break;
            }
        ?>
        <?php else: ?>
        <?php $nonSalableArray[] = $_product;?>
        <?php endif; ?>
        <?php endforeach; ?>
        <!--
        <li class="item last btn viewAllEvents">
        <a href="<?php echo Mage::getBaseUrl().$category['category_info']['url_path']; ?>">
        <img src="<?php echo $this->getSkinUrl()?>images/btn-viewevents-bug.png" />
        </a>
    </li>
    -->
    </div>
    
</ul>
<script type="text/javascript">decorateGeneric($$('ul.products-grid'), ['odd','even','first','last'])</script>
 <?php echo $this->stripTags($category['category_info']['description']) ?> 
<div class="clear"></div>
</div>
</div>
<?php endif; ?>
<?php endforeach ?>


<script type="text/javascript">
        jQuery(".counter").each(function(){
        var saleTime = new Date(jQuery(this).data('enddate'));
        var id = jQuery(this).data('id');
        var thisElem = jQuery(this);
        jQuery(this).countdown({
            until: saleTime, //Counting TO a date
            layout: "<span>Ends in</span><span class='italic'> {dn} <span class=\"cd-time\">Days</span> {hnn} <span class=\"cd-time\">:</span>{mnn}<span class=\"cd-time\">:</span>{snn}<span class=\"cd-time\"></span></span>",
            serverSync: retrieveServertime,
            expiryText: 'Completed',
            alwaysExpire: true,
            onExpiry: function( event ){
                thisElem.parents('.events-div').hide();
            },
        });
    });
    function retrieveServertime() {
        var time = null;
        jQuery.ajax({
            url:"<?php echo Mage::getUrl('ajax/servertime/servertime', array('format' => 'string')); ?>",
            async: false,
            success: function(servertime) {
                servertime = jQuery.parseJSON(servertime);
                time =  servertime.time;
            }, 
            error:function () {
                time = "<?php Mage::getModel('core/date')->timestamp(time()); ?>";
            }
        });
        date = new Date(time);
        return date;
    }
</script>
