<div id="userinfo">
    <?php // echo $this->getChildHtml('customertracking.headermsg');?>
</div>
<div id="usercart" class="span2 alpha">
    <?php //Place holder for session check, may be remove later?>
    <?php if ( true ): ?>
    <?php echo $this->getChildHtml('topCart') ?>
    <?php //echo $this->getChildHtml('checkoutLinks') ?>
    <?php else :?>
    <?php echo 'JS here'?>
    <?php endif;?>
</div>
<div class="span1">
        <a class="btn checkout btn-primary btn-large" title="Checkout" href="<?php echo Mage::getUrl('checkout/cart')?>">Checkout</a>
    </div>