<div id="usercart">
    <?php //Place holder for session check, may be remove later?>
    <?php if ( true ): ?>
    <?php echo $this->getChildHtml('topCart') ?>
    <?php //echo $this->getChildHtml('checkoutLinks') ?>
    <?php else :?>
    <?php echo 'JS here'?>
    <?php endif;?>
</div>
<div id="header-checkoutBtn">
    <a class="btn checkout btn-primary" title="Checkout" href="<?php echo Mage::getUrl('checkout/cart')?>"><strong>Checkout</strong></a>
</div>