    <meta charset="utf-8" />
    <title><?php echo $this->getTitle() ?></title>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=0">
    <!--[if IE 8]>
      <meta http-equiv="x-ua-compatible" content="IE=8">
    <![endif]-->
    <meta name="description" content="<?php echo strip_tags(html_entity_decode($this->getDescription())) ?>" />
    <meta name="keywords" content="<?php echo htmlspecialchars($this->getKeywords()) ?>" />
    <meta name="sailthru.date" content="<?php echo date("r");?>" />
    <meta name="sailthru.title" content="<?php echo ($this->getSailthruTitle()=='')?htmlspecialchars($this->getKeywords()):htmlspecialchars($this->getSailthruTitle()) ?>" />
    <meta name="sailthru.tags" content="<?php echo ($this->getSailthruTags()=='')?htmlspecialchars($this->getKeywords()):htmlspecialchars($this->getSailthruTags()) ?>" />
    <link rel="icon" href="<?php echo $this->getFaviconFile(); ?>" type="image/x-icon" />
    <link rel="shortcut icon" href="<?php echo $this->getFaviconFile(); ?>" type="image/x-icon" />
    
    <!--[if lt IE 7]>
    <script type="text/javascript">
    //<![CDATA[
        var BLANK_URL = '<?php echo $this->helper('core/js')->getJsUrl('blank.html') ?>';
        var BLANK_IMG = '<?php echo $this->helper('core/js')->getJsUrl('spacer.gif') ?>';
    //]]>
    </script>
    <![endif]-->

<link href="http://david.totsy.com/skin/frontend/enterprise/bootstrap/lib/tbs/docs/assets/css/bootstrap.css" rel="stylesheet">
<link href="http://david.totsy.com/skin/frontend/enterprise/bootstrap/lib/tbs/docs/assets/css/bootstrap-responsive.css" rel="stylesheet">
      
    <?php // Load external CDN-hosted JS dependencies that ABSOLUTELY require placement in the head ?>
    <script src="//cdn.optimizely.com/js/168465700.js"></script>
    <script src="http://david.totsy.com/js/jquery/jquery-1.9.1.min.js"></script>
    <?php echo $this->getCssJsHtml(); ?>