<style>

.pinterestform{
	text-align:center;
	font-size:14px;
	padding-top: 25px;
	color:#444444;
	margin-left:-20px;
}

.pinterestform a{
	color:#000000;
}

.pinterestform input{
	width:400px;
	height:25px;
	border:1px solid #999999;
	margin:5px;
}

.pinterestform select{
	width:200px;
	height:25px;
	border:1px solid #999999;
	margin:5px;
}

.pinterestfooter{
	margin-top:30px;
	padding:20px;
	color:#666666;
	size:12px;

}

</style>
        <div class="pinterestform">

				<img src="/skin/frontend/enterprise/harapartners/images/pinterest/SummerSpiritContest-header2.jpeg">                
				<a href="http://pinterest.com/totsyfan"><img src="/skin/frontend/enterprise/harapartners/images/pinterest/PinButton.jpeg" style="cursor:pointer;border:0px;"></a>                
				<br>
				<img src="/skin/frontend/enterprise/harapartners/images/pinterest/PinterestSun.jpeg">        

				<br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br>

			<div class="pinterestfooter">
			<b>RULES</b><br>
			
			<li>Follow Totsy on Pinterest <a href="http://pinterest.com/totsyfan">http://pinterest.com/totsyfan</a> </li>
			<li>Join your team based on the map above</li>
			<li>Pin a picture to the designated board, located on Totsy's Pinterest page, with the specified hashtag (up to 3 pins per participant)</li>
			<li>The most repinned board wins! We will pick one lucky winner from the winning board, good luck!</li>
			
			<br><br>
			<b>TERMS & CONDITIONS</b><br>
			No purchase necessary. Must be 18+ to enter and must be U.S. resident to be eligible. Contest valid until 11:59pm EST 07/25/12
			</div>



		</div>

