<style>

.pinterestform{
	text-align:center;
	font-size:14px;
	padding-top: 25px;
	color:#444444;
	margin-left:-20px;
}

.pinterestform a{
	color:#000000;
}

.pinterestform input{
	width:400px;
	height:25px;
	border:1px solid #999999;
	margin:5px;
}

.pinterestform select{
	width:200px;
	height:25px;
	border:1px solid #999999;
	margin:5px;
}

.pinterestfooter{
	margin-top:30px;
	padding:20px;
	color:#666666;
	size:12px;

}

</style>
        <div class="pinterestform">

				<img src="/skin/frontend/enterprise/harapartners/images/pinterest/SummerSpiritContest-header2.jpeg">                
				<a href="http://pinterest.com/"><img src="/skin/frontend/enterprise/harapartners/images/pinterest/PinButton.jpeg" style="cursor:pointer;border:0px;"></a>                
				<br>
				<img src="/skin/frontend/enterprise/harapartners/images/pinterest/PinterestSun.jpeg">        

				<br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br>

			<div class="pinterestfooter">
			<b>RULES</b><br>
			<ol>Follow Totsy on <a href="http://pinterest.com/totsyfan">Pinterest</a></ol>
			<ol>Create your own Pinterest board titled "Totsy Summer Spirit"</ol>
			<ol>Pin up to 10 pictures that captures the essence of summer in your Hometown</ol>
			<ol>Be sure to comment under every image with your specific hasthtag (Chicago = #totsymidwest, etc)</ol>
			<ol>One lucky winner will win a digital Polaroid camera</ol>
			
			<br><br>
			<b>TERMS & CONDITIONS</b><br>
			No purchase necessary. Must be 18+ to enter and must be U.S. resident to be eligible. Contest valid until 11:59 pm EST 07/30/12
			</div>



		</div>

