<button id="placeOrderBtn" type="button" title="<?php echo $this->__('Place Order') ?>" class="button"><div class="totsy-button"><?php echo $this->__('Place Order') ?></div></button>
<br>
<br>
<br>
<span style="float:right;">Please do not refresh while your order is being placed</span>

<script>
// @TODO: abstract this out to hpcheckout.js
// don't use inline onclick="hpcheckout.submit()"
jQuery(document).ready(function($) {
    $('#placeOrderBtn').bind('click', function(e) {
    	// set form controls back to enabled so POST will work
    	$('input[disabled], select[disabled]', '#hpcheckout-billing-form').removeAttr('disabled');
        // ...then submit form using hpcheckout method
        hpcheckout.submit();
    });
});
</script>
