<?php
/*
* rushcheckout.phtml overwrite original template form cart/item/default.phtml
* by Harapartners
*/
?>

<?php
$_item = $this->getItem();
$isVirtual = $_item->getProduct()->isVirtual();
$isVisibleProduct = $_item->getProduct()->isVisibleInSiteVisibility();
$canApplyMsrp = Mage::helper('catalog')->canApplyMsrp($_item->getProduct(), Mage_Catalog_Model_Product_Attribute_Source_Msrp_Type::TYPE_BEFORE_ORDER_CONFIRM);
$configKey = 'limit_timer';
$countdownTime = Mage::getStoreConfig('config/rushcheckout_timer/'.$configKey);

if ( !Mage::getSingleton('checkout/session')->hasData('countdown_timer') ) {
	$timer = 0;
	Mage::getSingleton('checkout/session')->setData('countdown_timer', $timer++);
	$timer = Mage::getSingleton('checkout/session')->getData('countdown_timer');
} else {	
	$timer = Mage::getSingleton('checkout/session')->getData('countdown_timer');
	Mage::getSingleton('checkout/session')->setData('countdown_timer', ++$timer);
}

//hack for thumbnail
//points to storeid 4 for mobile, but we have thumbs in 1
//fixes it for now suckassssss - jonathan dinkers
$badthumbnailurl = $this->getProductThumbnail()->resize(60,60);
$thumbnailurl = str_replace("cache/4/", "cache/1/", $badthumbnailurl);
?>
<tr>

    <td class="first">
    	<?php if ($this->hasProductUrl()):?><a href="<?php echo $this->getProductUrl() ?>" title="<?php echo $this->htmlEscape($this->getProductName()) ?>" class="product-image"><?php endif;?><img src="<?php echo $thumbnailurl; ?>" width="30" height="30" alt="<?php echo $this->htmlEscape($this->getProductName()) ?>" /><?php if ($this->hasProductUrl()):?></a><?php endif;?>

    </td>
    <td>
        <h2 class="product-name">
        <?php if ($this->hasProductUrl()):?>
            <a href="<?php echo $this->getProductUrl() ?>"><?php echo $this->htmlEscape($this->getProductName()) ?></a>
        <?php else: ?>
            <?php echo $this->htmlEscape($this->getProductName()) ?>
        <?php endif; ?>
        </h2>
        <?php if ($_options = $this->getOptionList()):?>
        <div class="item-options">
            <ul>
            <?php foreach ($_options as $_option) : ?>
            <?php $_formatedOptionValue = $this->getFormatedOptionValue($_option) ?> 
            <li>
            	<label><?php echo $this->htmlEscape($_option['label']) ?> :</label>
	            <div <?php if (isset($_formatedOptionValue['full_view'])): ?> class="truncated"<?php endif; ?>><?php echo $_formatedOptionValue['value'] ?>
	                <?php if (isset($_formatedOptionValue['full_view'])): ?>
	                <div class="truncated_full_value">
	                    <div class="item-options">
	                        <label><?php echo $this->htmlEscape($_option['label']) ?></label>
	                        <div><?php echo $_formatedOptionValue['full_view'] ?></div>
	                    </div>
	                </div>
	                <?php endif; ?>
	            </div>
            </li>          
            <?php endforeach; ?>
            </ul>
        </div>
        <?php endif;?>
        <?php if ($messages = $this->getMessages()): ?>
        <?php foreach ($messages as $message): ?>
            <p class="item-msg <?php echo $message['type'] ?>">* <?php echo $message['text'] ?></p>
        <?php endforeach; ?>
        <?php endif; ?>
        <?php if ($addtInfoBlock = $this->getProductAdditionalInformationBlock()):?>
            <?php echo $addtInfoBlock->setItem($_item)->toHtml() ?>
        <?php endif;?>
    </td>
	<td class="rush-price-box">
		<div class="rush-price-container">
			<?php if ($canApplyMsrp): ?>
				<div class="single-price" <?php if ($this->helper('tax')->displayCartBothPrices()): ?> colspan="2" <?php endif; ?> >
					<span class="cart-price">
						<span class="cart-msrp-unit"><?php echo $this->__('See price before order confirmation.'); ?></span>
						<?php $helpLinkId = 'cart-msrp-help-' . $_item->getId(); ?>
						<a id="<?php echo $helpLinkId ?>" href="#" class="map-help-link"><?php echo $this->__("What's this?"); ?></a>
						<script type="text/javascript">
							Catalog.Map.addHelpLink($('<?php echo $helpLinkId ?>'), "<?php echo $this->__("What's this?") ?>");
						</script>
					</span>
				</div>
			<?php else: ?>
				<?php if ($this->helper('tax')->displayCartPriceExclTax() || $this->helper('tax')->displayCartBothPrices()): ?>
					<div class="single-price">
						<?php if (Mage::helper('weee')->typeOfDisplay($_item, array(1, 4), 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
							<span class="cart-tax-total" onclick="taxToggle('eunit-item-tax-details<?php echo $_item->getId(); ?>', this, 'cart-tax-total-expanded');">
						<?php else: ?>
							<span class="cart-price">
						<?php endif; ?>
								<?php if (Mage::helper('weee')->typeOfDisplay($_item, array(0, 1, 4), 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
									<?php echo $this->helper('checkout')->formatPrice($_item->getCalculationPrice()+$_item->getWeeeTaxAppliedAmount()+$_item->getWeeeTaxDisposition()); ?>
								<?php else: ?>
									<?php echo $this->helper('checkout')->formatPrice($_item->getCalculationPrice()) ?>
								<?php endif; ?>
							</span>

						<?php if (Mage::helper('weee')->getApplied($_item)): ?>
							<div class="cart-tax-info" id="eunit-item-tax-details<?php echo $_item->getId(); ?>" style="display:none;">
								<?php if (Mage::helper('weee')->typeOfDisplay($_item, 1, 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
									<?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>
										<span class="weee"><?php echo $tax['title']; ?>: <?php echo Mage::helper('checkout')->formatPrice($tax['amount'],true,true); ?></span>
									<?php endforeach; ?>
								<?php elseif (Mage::helper('weee')->typeOfDisplay($_item, 2, 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
									<?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>
										<span class="weee"><?php echo $tax['title']; ?>: <?php echo Mage::helper('checkout')->formatPrice($tax['amount_incl_tax'],true,true); ?></span>
									<?php endforeach; ?>
								<?php elseif (Mage::helper('weee')->typeOfDisplay($_item, 4, 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
									<?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>
										<span class="weee"><?php echo $tax['title']; ?>: <?php echo Mage::helper('checkout')->formatPrice($tax['amount_incl_tax'],true,true); ?></span>
									<?php endforeach; ?>
								<?php endif; ?>
							</div>
							<?php if (Mage::helper('weee')->typeOfDisplay($_item, 2, 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
								<div class="cart-tax-total" onclick="taxToggle('eunit-item-tax-details<?php echo $_item->getId(); ?>', this, 'cart-tax-total-expanded');">
									<span class="weee"><?php echo Mage::helper('weee')->__('Total'); ?>: <?php echo $this->helper('checkout')->formatPrice($_item->getCalculationPrice()+$_item->getWeeeTaxAppliedAmount()+$_item->getWeeeTaxDisposition()); ?></span>
								</div>
							<?php endif; ?>
						<?php endif; ?>
					</div>
				<?php endif; ?>
				<?php if ($this->helper('tax')->displayCartPriceInclTax() || $this->helper('tax')->displayCartBothPrices()): ?>
				<div class="single-price">
					<?php $_incl = $this->helper('checkout')->getPriceInclTax($_item); ?>
					<?php if (Mage::helper('weee')->typeOfDisplay($_item, array(1, 4), 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
						<span class="cart-tax-total" onclick="taxToggle('unit-item-tax-details<?php echo $_item->getId(); ?>', this, 'cart-tax-total-expanded');">
					<?php else: ?>
						<span class="cart-price">
					<?php endif; ?>

						<?php if (Mage::helper('weee')->typeOfDisplay($_item, array(0, 1, 4), 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
							<?php echo $this->helper('checkout')->formatPrice($_incl+$_item->getWeeeTaxAppliedAmount()); ?>
						<?php else: ?>
							<?php echo $this->helper('checkout')->formatPrice($_incl-$_item->getWeeeTaxDisposition()) ?>
						<?php endif; ?>

					</span>
					<?php if (Mage::helper('weee')->getApplied($_item)): ?>

						<div class="cart-tax-info" id="unit-item-tax-details<?php echo $_item->getId(); ?>" style="display:none;">
							<?php if (Mage::helper('weee')->typeOfDisplay($_item, 1, 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
								<?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>
									<span class="weee"><?php echo $tax['title']; ?>: <?php echo Mage::helper('checkout')->formatPrice($tax['amount'],true,true); ?></span>
								<?php endforeach; ?>
							<?php elseif (Mage::helper('weee')->typeOfDisplay($_item, 2, 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
								<?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>
									<span class="weee"><?php echo $tax['title']; ?>: <?php echo Mage::helper('checkout')->formatPrice($tax['amount_incl_tax'],true,true); ?></span>
								<?php endforeach; ?>
							<?php elseif (Mage::helper('weee')->typeOfDisplay($_item, 4, 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
								<?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>
									<span class="weee"><?php echo $tax['title']; ?>: <?php echo Mage::helper('checkout')->formatPrice($tax['amount_incl_tax'],true,true); ?></span>
								<?php endforeach; ?>
							<?php endif; ?>
						</div>

						<?php if (Mage::helper('weee')->typeOfDisplay($_item, 2, 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
							<div class="cart-tax-total" onclick="taxToggle('unit-item-tax-details<?php echo $_item->getId(); ?>', this, 'cart-tax-total-expanded');">
								<span class="weee"><?php echo Mage::helper('weee')->__('Total incl. tax'); ?>: <?php echo $this->helper('checkout')->formatPrice($_incl+$_item->getWeeeTaxAppliedAmount()); ?></span>
							</div>
						<?php endif; ?>
					<?php endif; ?>
				</div>
				<?php endif; ?>
			<?php endif; ?>
		</div>
	</td>
		
		
		
		
	<td class="qty-box">
		<?php if( $isVirtual ): ?>
			<input type="text" name="cart[<?php echo $_item->getId() ?>][qty]" value="<?php echo $this->getQty() ?>" size="4" title="<?php echo $this->__('Qty') ?>" disabled="disabled" class="input-text qty" maxlength="12" />
		<?php else: ?>
		<div id="qty-<?php echo $timer ?>"	/>
			<div class="updown">
				<div class="updown-left rush-qty"><input name="cart[<?php echo $_item->getId() ?>][qty]" value="<?php echo $this->getQty() ?>" size="4" title="<?php echo $this->__('Qty') ?>" class="input-text qty" maxlength="12" /></div>
				<div class="updown-right">	
					<div class="updown-top">
					</div>
					<div class="updown-bottom">
					</div>
				</div>
			</div>
		</div>
		<script>
			jQuery('#qty-<?php echo $timer ?> .updown-top').click(function(){
				jQuery('#qty-<?php echo $timer ?> .updown-left input').val(parseFloat(jQuery('#qty-<?php echo $timer ?> .updown-left input').val())+1);
			});
			jQuery('#qty-<?php echo $timer ?> .updown-bottom').click(function(){
				if (parseFloat(jQuery('#qty-<?php echo $timer ?> .updown-left input').val())>1){
					jQuery('#qty-<?php echo $timer ?> .updown-left input').val(parseFloat(jQuery('#qty-<?php echo $timer ?> .updown-left input').val())-1);
				}
			});
		</script>
		<?php endif ?>
	</td>
		
	<td class="subtotal-box">
		<?php if ($this->helper('tax')->displayCartPriceExclTax() || $this->helper('tax')->displayCartBothPrices()): ?>
		<div class="rush-cart-price">
			<?php if (Mage::helper('weee')->typeOfDisplay($_item, array(1, 4), 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
				<span class="cart-tax-total" onclick="taxToggle('esubtotal-item-tax-details<?php echo $_item->getId(); ?>', this, 'cart-tax-total-expanded');">
			<?php else: ?>
				<span class="cart-price">
			<?php endif; ?>

				<?php if ($canApplyMsrp): ?>
					<span class="cart-msrp-subtotal">--</span>
				<?php else: ?>
					<?php if (Mage::helper('weee')->typeOfDisplay($_item, array(0, 1, 4), 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
						<?php echo $this->helper('checkout')->formatPrice($_item->getRowTotal()+$_item->getWeeeTaxAppliedRowAmount()+$_item->getWeeeTaxRowDisposition()); ?>
					<?php else: ?>
						<?php echo $this->helper('checkout')->formatPrice($_item->getRowTotal()) ?>
					<?php endif; ?>
				<?php endif; ?>

			</span>
			<?php if (Mage::helper('weee')->getApplied($_item)): ?>

				<div class="cart-tax-info" id="esubtotal-item-tax-details<?php echo $_item->getId(); ?>" style="display:none;">
					<?php if (Mage::helper('weee')->typeOfDisplay($_item, 1, 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
						<?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>
							<span class="weee"><?php echo $tax['title']; ?>: <?php echo Mage::helper('checkout')->formatPrice($tax['row_amount'],true,true); ?></span>
						<?php endforeach; ?>
					<?php elseif (Mage::helper('weee')->typeOfDisplay($_item, 2, 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
						<?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>
							<span class="weee"><?php echo $tax['title']; ?>: <?php echo Mage::helper('checkout')->formatPrice($tax['row_amount_incl_tax'],true,true); ?></span>
						<?php endforeach; ?>
					<?php elseif (Mage::helper('weee')->typeOfDisplay($_item, 4, 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
						<?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>
							<span class="weee"><?php echo $tax['title']; ?>: <?php echo Mage::helper('checkout')->formatPrice($tax['row_amount_incl_tax'],true,true); ?></span>
						<?php endforeach; ?>
					<?php endif; ?>
				</div>

				<?php if (Mage::helper('weee')->typeOfDisplay($_item, 2, 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
					<div class="cart-tax-total" onclick="taxToggle('esubtotal-item-tax-details<?php echo $_item->getId(); ?>', this, 'cart-tax-total-expanded');">
						<span class="weee"><?php echo Mage::helper('weee')->__('Total'); ?>: <?php echo $this->helper('checkout')->formatPrice($_item->getRowTotal()+$_item->getWeeeTaxAppliedRowAmount()+$_item->getWeeeTaxRowDisposition()); ?></span>
					</div>
				<?php endif; ?>
			<?php endif; ?>
		</div>
		<?php endif; ?>
		<?php if ($this->helper('tax')->displayCartPriceInclTax() || $this->helper('tax')->displayCartBothPrices()): ?>
		<div class="rush-cart-price">
			<?php $_incl = $this->helper('checkout')->getSubtotalInclTax($_item); ?>
			<?php if (Mage::helper('weee')->typeOfDisplay($_item, array(1, 4), 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
				<span class="cart-tax-total" onclick="taxToggle('subtotal-item-tax-details<?php echo $_item->getId(); ?>', this, 'cart-tax-total-expanded');">
			<?php else: ?>
				<span class="cart-price">
			<?php endif; ?>

				<?php if ($canApplyMsrp): ?>
					<span class="cart-msrp-subtotal">--</span>
				<?php else: ?>
					<?php if (Mage::helper('weee')->typeOfDisplay($_item, array(0, 1, 4), 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
						<?php echo $this->helper('checkout')->formatPrice($_incl+$_item->getWeeeTaxAppliedRowAmount()); ?>
					<?php else: ?>
						<?php echo $this->helper('checkout')->formatPrice($_incl-$_item->getWeeeTaxRowDisposition()) ?>
					<?php endif; ?>
				<?php endif; ?>

			</span>


			<?php if (Mage::helper('weee')->getApplied($_item)): ?>
				<div class="cart-tax-info" id="subtotal-item-tax-details<?php echo $_item->getId(); ?>" style="display:none;">
					<?php if (Mage::helper('weee')->typeOfDisplay($_item, 1, 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
						<?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>
							<span class="weee"><?php echo $tax['title']; ?>: <?php echo Mage::helper('checkout')->formatPrice($tax['row_amount'],true,true); ?></span>
						<?php endforeach; ?>
					<?php elseif (Mage::helper('weee')->typeOfDisplay($_item, 2, 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
						<?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>
							<span class="weee"><?php echo $tax['title']; ?>: <?php echo Mage::helper('checkout')->formatPrice($tax['row_amount_incl_tax'],true,true); ?></span>
						<?php endforeach; ?>
					<?php elseif (Mage::helper('weee')->typeOfDisplay($_item, 4, 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
						<?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>
							<span class="weee"><?php echo $tax['title']; ?>: <?php echo Mage::helper('checkout')->formatPrice($tax['row_amount_incl_tax'],true,true); ?></span>
						<?php endforeach; ?>
					<?php endif; ?>
				</div>

				<?php if (Mage::helper('weee')->typeOfDisplay($_item, 2, 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
					<div class="cart-tax-total" onclick="taxToggle('subtotal-item-tax-details<?php echo $_item->getId(); ?>', this, 'cart-tax-total-expanded');">
						<span class="weee"><?php echo Mage::helper('weee')->__('Total incl. tax'); ?>: <?php echo $this->helper('checkout')->formatPrice($_incl+$_item->getWeeeTaxAppliedRowAmount()); ?></span>
					</div>
				<?php endif; ?>
			<?php endif; ?>
		</div>
		<?php endif; ?>
	</td>
</tr>

