<?php $_code=$this->getMethodCode();
$hasVirtual = false;
// Check to see if there are multiple fulfillment types
$_quote = Mage::getSingleton('checkout/session')->getQuote();

foreach($_quote->getAllItems() as $item) {
    if($item->getParentItemId()) {
        continue;
    }
    $product = Mage::getModel ( 'catalog/product' )->load ( $item->getProductId () );
    if($product->getIsVirtual() && $product->getFulfillmentType() !== 'nominal') {
        $_fulfillmentType = 'virtual';
        $hasVirtual = true;
    } else {
        $_fulfillmentType = $product->getFulfillmentType();
    }
    $fulfillmentTypes [$_fulfillmentType] [] = $item->getId ();
}

$multiShipping = FALSE;
if(count($fulfillmentTypes) > 1) {
    $multiShipping = TRUE;
}

$_reportGroup = $this->getReportGroup();
$_paypageId = Mage::getModel('Litle_CreditCard_Model_PaymentLogic')->getConfigData("paypage_id");
$_paypageUrl = Mage::getModel('Litle_CreditCard_Model_PaymentLogic')->getConfigData("paypage_url");
$_isLoggedIn = Mage::helper('customer')->isLoggedIn();

$_time =  date('ymdHis');
$_session =  Mage::getModel("core/session")->getEncryptedSessionId();
$_id = $_time . substr($_session,13);
$hasProfile = false;
$customerId = Mage::getSingleton('customer/session')->getCustomerId(); 

if($this->getVaultEnabled()) {
  	if($this->hasStoredCards()) {
    	$hasProfile = true;
    }
} 

?>

<script type="text/javascript">
jQuery(document).ready( function() {
    checkoutPayment.hasProfile = "<?php echo $hasProfile; ?>";
    
    jQuery("[id='payment[cybersource_subid]']").change(function() {
        checkoutPayment.setPaymentType();
    });
    
    jQuery("[name='payment[cc_number]']").keyup(function() {
        checkoutPayment.autoDetectCard(this);
    });
    jQuery("#add_payment_toggle").click(function() {
        checkoutPayment.paymentToggle();
    });
    jQuery('#paypal').click(function() {
        checkoutPayment.setPaypal();
    });
    jQuery(".use-saved-card-control").click(function() {
        checkoutPayment.useSavedCard();
    });
});
</script>
<!-- INCLUDE YOUR BLOCK HERE -->
<div class="form-list one-page-payment row span12" id="payment_form_<?php echo $_code ?>">
<div class="hpcheckout-payment-title">
            <h4 class="legend">Your payment methods</h4>
        </div>
    <div id="new-card" class="<?php if($hasProfile){ echo "span6"; } else { echo "span12"; } ?>" />
        <div class="controls controls-row row">
        	<div class="cc_types">
        		<?php $_ccType = $this->getInfoData('cc_type') ?>
        		<?php $_cssClassNamesForCardTypes = Array(
                    'vi'=>'vb',
                    'di'=>'db',
                    'mc'=>'mb',
                    'ae'=>'ab'
        		); ?>
        		 <div class="cc_types" id="<?php echo $_code ?>_cc_type">
        		 <?php $i=0; ?>
        		 <?php foreach ($this->getCcAvailableTypes() as $_typeCode => $_typeName): ?>
        		    <span class="cc cards">
        		 	    <span id="<?php echo strtolower($_typeCode); ?>" title="<?php echo $_typeName; ?>" class="<?php echo $_cssClassNamesForCardTypes[strtolower($_typeCode)]; ?>" data-active="<?php echo strtolower($_typeCode); ?>" data-inactive="<?php echo $_cssClassNamesForCardTypes[strtolower($_typeCode)]; ?>">
        		 	    </span>
        		 	</span> 
        		 <?php $i++; ?>
        		 <?php endforeach ?>
                 </div>
        	</div>
        </div>
        <div class="controls controls-row use-new-card-wrapper">
            <div class="<?php if($hasProfile){ echo "row"; } ?>" id="card-number">
                <input type="text" id="<?php echo $_code ?>_cc_number" name="payment[cc_number]" title="<?php echo $this->__('Credit Card Number') ?>" class="span5" value="<?php echo (($this->__('Credit Card Number')!=='Credit Card Number') ? $this->__('Credit Card Number') : "") ?>" placeholder="<?php echo $this->__('Credit Card Number') ?>" />
                <div class="validation-advice" id="cc-num-error-message" style="display:none">Credit card number does not match credit card type</div>
            </div>
            <div class="row" id="card-details">
                <select id="<?php echo $_code ?>_expiration" name="payment[cc_exp_month]" class="span2 validate-cc-exp">
                <?php $_ccExpMonth = $this->getInfoData('cc_exp_month') ?>
                <?php foreach ($this->getCcMonths() as $k=>$v): ?>
                        <option value="<?php echo $k?$k:'' ?>" <?php if($k==$_ccExpMonth): ?> selected="selected"<?php endif ?>><?php echo $v ?></option>
                <?php endforeach ?>
                </select>
                <select id="<?php echo $_code ?>_expiration_yr" name="payment[cc_exp_year]" class="span2">
                <?php $_ccExpYear = $this->getInfoData('cc_exp_year') ?>
                <?php foreach ($this->getCcYears() as $k=>$v): ?>
                    <option value="<?php echo $k?$k:'' ?>" <?php if($k==$_ccExpYear): ?> selected="selected"<?php endif ?>><?php echo $v ?>
                    </option>
                <?php endforeach ?>
                </select>
                <?php if ($this->hasVerification()): ?>
                <input type="text" title="<?php echo $this->__('Card Verification Number') ?>" class="span1 validate-cc-cvn-radio" id="<?php echo $_code ?>_cc_cid" name="payment[cc_cid]" value="<?php echo (($this->__('Card Verification Number')!=="Card Verification Number") ? $this->__('Card Verification Number') : "") ?>" placeholder="<?php echo $this->__('CVN#') ?>" />
                <?php endif; ?>
                <div id="credits_and_card_save" class="span1">
                <?php if($_isLoggedIn && $this->getVaultEnabled()):?>
                    <div id="<?php echo $_code ?>_cc_type_should_save_div" class="new-card">
                         <?php echo $this->__('Save') ?>
                        <span>
                            <input type="checkbox" title="<?php echo $this->__('Save Card') ?>" class="input-checkbox" id="<?php echo $_code ?>_cc_should_save" checked='checked' name="payment[cc_should_save]" />
                        </span>
                    </div>
                <?php endif; ?>
            </div>
        </div>
    </div>
</div>
<?php if($hasProfile) { ?>
        <div class="span5" id="use-card-method">
            <div id="cybersource-use-card-method">
            <table class="saved_card">
            	<tr>
                	<th></th>
                	<th></th>
                	<th></th>
                	<th></th>
                	<th></th>
                </tr>
                    <?php foreach ($this->getStoredCards() as $card): ?>
                        <?php
                            $customerId = $card->getData('customer_id');
                            $lastCardUsed = Mage::helper('palorus')->getLastCardUsed();
                            $customerObj = Mage::getSingleton('customer/customer')->load($customerId);
                            $customerAddress = Mage::getModel('customer/address')->load($card->getData('address_id'));
                            $customerName = $customerAddress->getFirstname() ." ". $customerAddress->getLastname();
                            $customerStreet = $customerAddress['street'];
                        ?>
                        <tr>
                            <td>
                                <div>
                   		            <input type="radio" data-billing-address-id="<?php echo $card->address_id; ?>" id="payment" name="payment[cc_vaulted]" value="<?php echo $card->getVaultId() ?>"
                                    <?php if($lastCardUsed && ($lastCardUsed->getId() == $card->getVaultId()) && (!$lastCardUsed->getSubscriptionId()))  echo 'checked="yes"'; ?> class="use-saved-card-control pull-left" >
                                    <span class="cc">
		 	                            <span title="<?php echo strtolower($card->type); ?>" class="<?php echo strtolower($card->type); ?>" >
		 	                            </span>
		 	                       </span>
		 	                       <strong><?php $card->getTypeName(); ?></strong>
		 	                    </div>
		 	                </td>
		 	                <td class="card-type"> ending in <?php echo $card->getData('last4'); ?></td>
                            <td class="card-name"><?php echo $customerName; ?></td>
                            <td class="billing-address"><?php echo $customerStreet; ?></td>
                            <td class="card-expdate"><?php echo $card->getData('expiration_month')."/".$card->getData('expiration_year'); ?></td>
                        </tr>
                    <?php endforeach ?>
                       <script type="text/javascript">
                       	   Event.observe($("<?php echo $_code ?>_cc_vaulted"), 'change', function() {
                       	   	   if ($F(this) != '0') {
                       	   	   	   $$('.new-card').invoke('hide');
                       	   	   	   $('<?php echo $_code ?>_cc_cid').value="";
                       	   	   	   $$('.cid-class').invoke('show');
                       	   	   } else {
                       	   	   	   $$('.new-card').invoke('show');
                       	   	   	   $('<?php echo $_code ?>_cc_cid').value="";
                       	   	   	   $('<?php echo $_code ?>_cc_type').value = "";
                       	   	   	   $('<?php echo $_code ?>_expiration').value = "";
                       	   	   	   $('<?php echo $_code ?>_expiration_yr').value = "";
                       	   	   	   $('<?php echo $_code ?>_cc_should_save').setValue(false);
                       	   	   	   $$('.cid-class').invoke('show');
                       	   	   }
                       	   });
                       </script>
    			</table>
                </div>
            </div>
         <?php } ?>
</div>
<div class="row">
    <div class="controls controls-row span12">
        <div class="span4">
    <?php $methods = $this->getLayout()->getBlock('hpcheckout.payment.methods')->getMethods();  ?>
    <?php if(count($methods)): ?>
    	<?php if(!$multiShipping && !$hasVirtual && Mage::getModel('paypal/config')->isMethodActive('paypal_express')): ?>
               <input type="radio" value="paypal_express" id="paypal_payment" name="paypal_payment">
               <span>
                   <span title="Paypal Express" class="paypal"></span>
                   <a class="what-is-paypal-link" href="https://www.paypal.com/cgi-bin/webscr?cmd=xpt/Marketing/popup/OLCWhatIsPayPal-outside" target="_blank">What is<br /> PayPal?</a>
               </span>
       <?php endif; ?>
    <?php endif; ?>
        </div>
        <div class="span3">
            <div id="rewards_points">
                <?php echo $this->getLayout()->getBlock('hpcheckout.reward.points')->toHtml(); ?>
            </div>
        </div>
        <div class="span5">
            <div class="cc_security pull-right">
                <div class="cc_secure_text pull-left">Totsy ensures your information is<br> private and secure!</div>
                <span class="cc_secure_icon">
                    <img src="/skin/frontend/enterprise/bootstrap/images/iconmonstr-lock-7-icon.png" width="40" height="40">
                </span>
            </div>
        </div>
    </div>
	<?php if($this->getPaypageEnabled()):?>
   		<input type="hidden" id="<?php echo $_code ?>_paypage_id" name="payment[paypage_id]" value="<?php echo $_paypageId; ?>"/>
        <input type="hidden" id="<?php echo $_code ?>_merchant_txn_id" name="payment[merchant_txn_id]" value="<?php echo $_id; ?>"/>
		<input type="hidden" id="<?php echo $_code ?>_paypage_url" name="payment[paypage_url]" value="<?php echo $_paypageUrl; ?>"/>
        <input type="hidden" id="<?php echo $_code ?>_order_id" name="payment[order_id]" value="<?php echo $_id; ?>"/>
        <input type="hidden" id="<?php echo $_code ?>_report_group" name="payment[report_group]" value="<?php echo $_reportGroup; ?>"/>
 		<input type="hidden" id="<?php echo $_code ?>_paypage_enabled" name="payment[paypage_enabled]" value="<?php echo $this->getPaypageEnabled(); ?>"/>
       	<input type="hidden" id="<?php echo $_code ?>_paypage_registration_id" name="payment[paypage_registration_id]" value=""/>
        <input type="hidden" id="<?php echo $_code ?>_bin" name="payment[bin]"/>
        <input type="hidden" id="<?php echo $_code ?>_code" name="payment[code]"/>
        <input type="hidden" id="<?php echo $_code ?>_message" name="payment[message]"/>
        <input type="hidden" id="<?php echo $_code ?>_response_time" name="payment[response_time]"/>
        <input type="hidden" id="<?php echo $_code ?>_type" name="payment[type]"/>
        <input type="hidden" id="<?php echo $_code ?>_litle_txn_id" name="payment[litle_txn_id]"/>
		<input type="hidden" id="<?php echo $_code ?>_vault_id" name="payment[vault_id]" value="<?php echo $purchase['token']; ?>"/>
        <input type="hidden" id="<?php echo $_code ?>_method" name="payment[method]" value="creditcard">
	<?php endif; ?>
</div>
<?php if($this->getPaypageEnabled()):?>

<script type="text/javascript">

    var litlePayment = new Payment($("payment_form_<?php echo $this->getMethodCode(); ?>"),
            "<?php echo $this->getUrl('checkout/onepage/');?>");
    var formId = "payment_form_<?php echo $this->getMethodCode(); ?>";
    var litlePaymentForm = new paymentForm(formId);

    document.observe("dom:loaded", function() {
	Payment.prototype.save = function() {
		var _saveUrl = this.saveUrl;
		var _onComplete = this.onComplete;
		var _onSave = this.onSave;
		var _currentMethod = "<?php echo $_code ?>";
		var _form = this.form;

		// Litle Page Stuff//
		function setLitleResponseFields(response) {	
		    $('<?php echo $_code ?>_code').value = response.response;
		    $('<?php echo $_code ?>_message').value = response.message;
		    $('<?php echo $_code ?>_response_time').value = response.responseTime;
		    $('<?php echo $_code ?>_litle_txn_id').value = response.litleTxnId;
		    $('<?php echo $_code ?>_type').value = response.type;					
            hpcheckout.submit();
		}

		function submitAfterLitle() {
		    var request = new Ajax.Request(
		    	_saveUrl,
		    	{
		    		method:'post',
		    		onComplete: _onComplete,
		    		onSuccess: _onSave,
		    		//onFailure: checkout.ajaxFailure.bind(checkout),
		    		parameters: Form.serialize(_form)
		    	}
		    );
		}

		function timeoutOnLitle() {
		    setLitleResponseFields();
		    alert('timeout error');
		    return false;
		}

		function onErrorAfterLitle(response) {
		    setLitleResponseFields(response);
		    //alert('There was an error. Re-enter your payment information, or contact us for further assistance.');
		    return false;
		}

		var formFields = {
		    "accountNum" : $('<?php echo $_code ?>_cc_number'),
		    "paypageRegistrationId" : $('<?php echo $_code ?>_paypage_registration_id'),
		    "bin" : $('<?php echo $_code ?>_bin'),
		    "cvv2" : $('<?php echo $_code ?>_cc_cid')
		};

		var litleRequest = {
		    "paypageId" : $('<?php echo $_code ?>_paypage_id').value,
		    "reportGroup" : $('<?php echo $_code ?>_report_group').value,
		    "orderId" : $('<?php echo $_code ?>_order_id').value,
		    "id" : $('<?php echo $_code ?>_merchant_txn_id').value,
		    "url" : ($('<?php echo $_code ?>_paypage_url').value)
		};

        if(!hpcheckout.validate()) {
            return;
        }
        
        if(typeof checkoutPayment!=="undefined" && !checkoutPayment.validateCardType()) {
            return;
        }
        //this becomes a set of radio buttons instead    
        var selectmenu = $("<?php echo $_code ?>_cc_vaulted");
		if(selectmenu){
		    var chosenoption=selectmenu.options[selectmenu.selectedIndex]
		    if (chosenoption.value == 0){
		    	if( _currentMethod == "creditcard" ){
		    		sendToLitle(litleRequest, formFields, setLitleResponseFields, onErrorAfterLitle);
                    submitAfterLitle();
                }
		    } else {
                submitAfterLitle();
                hpcheckout.submit();
            }
		} else {
		    if( _currentMethod == "creditcard" ){
		    	sendToLitle(litleRequest, formFields, setLitleResponseFields, onErrorAfterLitle);
            }
            submitAfterLitle();
		}
	};	
});

    
</script>
<?php endif; ?>
</div>