<?php $_code=$this->getMethodCode();
$hasVirtual = false;
// Check to see if there are multiple fulfillment types

$_quote = Mage::getSingleton('checkout/session')->getQuote();

//print_r(get_class_methods(get_class($_quote)));

foreach($_quote->getAllItems() as $item) {
    if($item->getParentItemId()) {
        continue;
    }
    $product = Mage::getModel ( 'catalog/product' )->load ( $item->getProductId () );
    if($product->getIsVirtual() && $product->getFulfillmentType() !== 'nominal') {
        $_fulfillmentType = 'virtual';
        $hasVirtual = true;
    } else {
        $_fulfillmentType = $product->getFulfillmentType();
    }
    $fulfillmentTypes [$_fulfillmentType] [] = $item->getId ();
}

$multiShipping = FALSE;
if(count($fulfillmentTypes) > 1) {
    $multiShipping = TRUE;
}
?>

<?php
$_reportGroup = $this->getReportGroup();
$_paypageId = Mage::getModel('Litle_CreditCard_Model_PaymentLogic')->getConfigData("paypage_id");
$_paypageUrl = Mage::getModel('Litle_CreditCard_Model_PaymentLogic')->getConfigData("paypage_url");
$_isLoggedIn = Mage::helper('customer')->isLoggedIn();

$_time =  date('ymdHis');
$_session =  Mage::getModel("core/session")->getEncryptedSessionId();
$_id = $_time . substr($_session,13);

?>

<div class="form-list .one-page-payment" id="payment_form_<?php echo $_code ?>">
<?php $customerId = Mage::getSingleton('customer/session')->getCustomerId(); ?>
<?php if ($this->getProfilesByCustomerId( $customerId )) { ?>
<?php $profiles = $this->getProfilesByCustomerId( $customerId ) ?>
<?php
    $profilesCounter = 0;
    foreach( $profiles as $profile ) {
        if($profile->getSubscriptionId() && $profile->getIsDefault()==0 && $profile->getData('saved_by_customer')) {
            $profilesCounter++;
        }
    }

    $hasProfile = false;

    if ($profilesCounter > 0 ) {
        $hasProfile = true;
    } else {
        $hasProfile = false;
    }
?>
<?php } ?>
<script type="text/javascript">

jQuery(document).ready(function() {
    checkoutPayment.hasProfile = "<?php echo $hasProfile; ?>";
    checkoutPayment.toggleViews();

    jQuery("[id='payment[cybersource_subid]']").change(function() {
        checkoutPayment.setPaymentUI(this);
    });
    jQuery(".use-saved-card-control").click(function() {
        checkoutPayment.useSavedCard();
    });
    jQuery("#paymentfactory_tokenize_cc_type input").click(function() {
        checkoutPayment.setPaymentType(this);
    });
});

</script>

<div>
    <div>
    	<div>
        	<div class="hpcheckout-payment-title">
        	    <h4 class="legend">Your payment methods</h4>
        	</div>
        	<!-- part A of a hack for the radio button error message-->
        	<div>
        	</div>
        	<div class="cc_types use-new-card-wrapper input-box validation-error pull-left">
        		<?php $_ccType = $this->getInfoData('cc_type') ?>
        		 <div id="<?php echo $_code ?>_cc_type">
        		 <?php $i=0; ?>
        		 <?php foreach ($this->getCcAvailableTypes() as $_typeCode => $_typeName): ?>
        		  <input type="radio" class="validate-cybsersource-cc-type <?php if($i==3) { /*echo "validate-one-required"*/; } ?>" name="payment[cc_type]" value="<?php echo $_typeCode ?>" <?php if ($_typeCode==$_ccType) { echo "checked"; } ?> >
        		 <?php $i++; ?>
        		 	<span class="cc">
        		 	    <span title="<?php echo $_typeName; ?>"  class="<?php echo strtolower($_typeCode); ?>" >
        		 	    </span>
        		 	</span>
        		 <?php endforeach ?>
        		 <?php $methods = $this->getLayout()->getBlock('hpcheckout.payment.methods')->getMethods();  ?>
                 <?php if(count($methods)): ?>
                 	<?php if(!$multiShipping && !$hasVirtual && Mage::getModel('paypal/config')->isMethodActive('paypal_express')): ?>
			    	    <input type="radio" value="paypal_express" id="paypal_payment" name="paypal_payment">
			    	    <div>
        		 	    <span title="Paypal Express" class="paypal"></span>
        		 	    <a class="what-is-paypal-link" href="https://www.paypal.com/cgi-bin/webscr?cmd=xpt/Marketing/popup/OLCWhatIsPayPal-outside" target="_blank">What is<br /> PayPal?</a>
        		 	    </div>
        		 	<?php endif; ?>
                 <?php endif; ?>
        		 <div style="clear:both; height:10px"></div>
        	    </div>
        	</div>
        </div>
        <div>
            <?php if( $customerId  ): ?>
            <div>
                <div class="cc_security pull-right">
                    <div class="cc_secure_text pull-left">Totsy ensures your information is<br> private and secure!</div>
                    <div class="cc_secure_icon">
                        <img src="/skin/frontend/enterprise/bootstrap/images/iconmonstr-lock-7-icon.png" width="40" height="40">
                    </div>
                </div>
            </div>
            <?php endif ?>
        </div>
        <div style="clear:both"></div>
        <?php if(($profiles && $profilesCounter > 0) || ($this->getVaultEnabled())) { ?>
                <div class="pull-left" id="use-card-method">
                    <div id="cybersource-use-card-method ">
                    <table class="saved_card">
                    	<tr>
                        	<th></th>
                        	<th></th>
                        	<th>Name on card</th>
                        	<th>Billing address</th>
                        	<th>Expires</th>
                        </tr>
                    <?php if($profiles) { ?>
                    <?php foreach( $profiles as $profile ): ?>
                        <?php
                            $checked = '';
                            $customerObj = Mage::getSingleton('customer/customer')->load($profile->getCustomerId());
                            $customerAddress = Mage::getSingleton('customer/address')->load($profile->getAddressId());
                            
                            $customerName = $customerAddress->getFirstname() ." ". $customerAddress->getLastname();
                            
                            //reset gets the first item from the array passed in
                            $customerStreetArray = $customerAddress->getStreet();
                            $customerStreet = reset($customerStreetArray);
                            
                            $orders = Mage::getResourceModel('sales/order_collection')->addFieldToSelect('*')
                            ->addFieldToFilter('customer_id', $profile->getCustomerId())->addAttributeToSort('created_at', 'DESC')->setPageSize(1);
                            
                            //checking the users last used, saved to expedite checkout
                            //comparing cybersource profile id to id of card used in last order placed
                            if($orders->getFirstItem()->getPayment()) {
                                if($orders->getFirstItem()->getPayment()->getData('cybersource_subid')==$profile->getSubscriptionId()) {
                                    $checked = 'checked';
                                }
                            }
                        ?>
                        <script type="text/javascript">
                            jQuery(document).ready( function() {
                                checkoutPayment.lastUsedAddressId = "<?php echo $profile->getAddressId(); ?>";
                            });
                        </script>
                        <?php if(!$profile->getSubscriptionId() || $profile->getIsDefault()== 1 || !$profile->getData('saved_by_customer')) { continue; } ?>
                        <tr>
                        	<td>
                                <input type="radio" checked="<?php echo $checked; ?>" name="payment[cybersource_subid]" id="payment[cybersource_subid]" class="use-saved-card-control pull-left" value="<?php echo $profile->getEncryptedSubscriptionId() ?>">
                                    <span class="cc">
        		 	                    <span title="<?php echo $this->getFullCcCardType( $profile->getData( 'card_type' )); ?>" class="<?php echo strtolower($profile->getData('card_type')); ?>" >
        		 	                    </span>
        		 	                </span>
        		 	         </td>
                            <td class="card-type">
                            <strong><?php echo $this->getFullCcCardType( $profile->getData( 'card_type' )); ?></strong> ending in <?php echo $profile->getLast4no() ?></td>
                            <td class="card-name"><?php echo $customerName ?></td>
                            <td class="billing-address"><?php echo $customerStreet; ?></td>
                            <td class="card-expdate"><?php echo $profile->getExpireMonth()."/".$profile->getExpireYear() ?>
                            </td>
                        </tr>
                    <?php endforeach ?>
                    <?php } elseif($this->getVaultEnabled()) { ?>
                        <?php if ($this->hasStoredCards()){ ?>
                            <?php foreach ($this->getStoredCards() as $card): ?>
                                <tr>
	                                <td>
	                       		        <input type="radio" name="payment[cc_vaulted]" value="<?php echo $card->getVaultId() ?>"><?php echo 'Stored ' . $card->getTypeName() . ' Ending in: ' . $card->getLast4() ?>
                                            <span class="cc">
        		 	                            <span title="<?php //echo $this->getFullCcCardType( $profile->getData( 'card_type' )); ?>" class="<?php //echo strtolower($profile->getData('card_type')); ?>" >
        		 	                            </span>
        		 	                       </span>
        		 	                </td>
        		 	                <td class="card-type"><strong><?php $card->getTypeName(); ?></strong> ending in <?php echo $card->getLast4() ?></td>
                                    <td class="card-name"><?php echo "Dude Name"; //$customerName ?></td>
                                    <td class="billing-address"><?php echo "Dude Address #32"; //$customerStreet; ?></td>
                                    <td class="card-expdate"><?php echo "10/13"; /* echo $profile->getExpireMonth()."/".$profile->getExpireYear();*/ ?></td>
                                </tr>
	                        <?php endforeach ?>
	                       	</div>
	                   </li>
	                   <script type="text/javascript">
	                   Event.observe($("<?php echo $_code ?>_cc_vaulted"), 'change', function() {
	                   	if ($F(this) != '0') {
	                   		$$('.new-card').invoke('hide');
	                   		$('<?php echo $_code ?>_cc_cid').value="";
	                   		$$('.cid-class').invoke('show');
	                   	} else {
	                   		$$('.new-card').invoke('show');
	                   		$('<?php echo $_code ?>_cc_cid').value="";
	                   		$('<?php echo $_code ?>_cc_type').value = "";
	                   		$('<?php echo $_code ?>_expiration').value = "";
	                   		$('<?php echo $_code ?>_expiration_yr').value = "";
	                   		$('<?php echo $_code ?>_cc_should_save').setValue(false);
	                   		$$('.cid-class').invoke('show');
	                   	}
	                   });
	                   </script>
	                   <?php } ?>
                    <?php } ?>
						</table>
                    </div>
                </div>
                <?php } ?>
                <div>
                    <?php if($profiles) { ?>
                     <?php foreach( $profiles as $profile ): ?>
                        <?php if( !$profile->getSubscriptionId() || $profile->getIsDefault()== 1 ) { continue; } ?>
                        <input type="hidden" id="address_<?php echo $profile->getEncryptedSubscriptionId() ?>" value="<?php echo $profile->getData('address_id') ?>" />
                    <?php endforeach ?>
                    <?php } ?>
                </div>
    </div>
    <div id="credits_and_card_save">
        <div class="cc_save_card use-new-card-wrapper cc_info">
            <div>
                <input type="checkbox" value="1" name="payment[saved_by_customer]" checked="checked" id="<?php echo $_code ?>_saved" />
            </div>
            <div id="cc_save_text" for="<?php echo $_code ?>_cc_save"><?php echo $this->__(' Save this method for quick <br> shopping on future visits!'); ?>
            </div>
        </div>
        <div id="rewards_points">
            <?php echo $this->getLayout()->getBlock('hpcheckout.reward.points')->toHtml(); ?>
        </div>
    </div>
<div id="cc_data">
    <div class="pull-left">
        <div>
            <div class="pull-left cc_num use-new-card-wrapper cc_info">
                <div class="input-box">
                    <input type="text" id="<?php echo $_code ?>_cc_number" name="payment[cc_number]" title="<?php echo $this->__('Credit Card Number') ?>" class="input-text validate-cc-number validate-cc-type-radio" value="<?php echo (($this->__('Credit Card Number')!=='Credit Card Number') ? $this->__('Credit Card Number') : "") ?>" placeholder="<?php echo $this->__('Credit Card Number') ?>" />
                </div>
            </div>
        </div>
        <div style="clear:both"></div>
        <div>
            <?php if ($this->hasVerification()): ?>
            <div class="cc_cvn pull-left use-new-card-wrapper cc_info">
                <label for="<?php echo $_code ?>_cc_cid" class="required"><em>*</em><?php echo $this->__('CVN#') ?></label>
                <div class="input-box">
                    <div class="v-fix">
                        <input type="text" title="<?php echo $this->__('Card Verification Number') ?>" class="input-text cvv validate-cc-cvn-radio" id="<?php echo $_code ?>_cc_cid" name="payment[cc_cid]" value="<?php echo (($this->__('Card Verification Number')!=="Card Verification Number") ? $this->__('Card Verification Number') : "") ?>" placeholder="<?php echo $this->__('CVN#') ?>" />
                    </div>
                </div>
            </div>
            <?php endif; ?>
            <div id="add_payment_save_card">
            </div>
            <div class="cc_exp pull-right use-new-card-wrapper cc_info">
                <div class="pull-left">
                    <div for="<?php echo $_code ?>_expiration" class="lbl"><em>*</em><?php echo $this->__('Exp.') ?></div>
                    <div class="pull-left">
                        <div class="pull-left">
                            <select id="<?php echo $_code ?>_expiration" name="payment[cc_exp_month]" class="month validate-cc-exp">
                            <?php $_ccExpMonth = $this->getInfoData('cc_exp_month') ?>
                            <?php foreach ($this->getCcMonths() as $k=>$v): ?>
                                <option value="<?php echo $k?$k:'' ?>" <?php if($k==$_ccExpMonth): ?>selected="selected"<?php endif ?>><?php echo $v ?></option>
                            <?php endforeach ?>
                            </select>
                        </div>
                        <div class="pull-right">
                            <select id="<?php echo $_code ?>_expiration_yr" name="payment[cc_exp_year]" class="year">
                            <?php $_ccExpYear = $this->getInfoData('cc_exp_year') ?>
                            <?php foreach ($this->getCcYears() as $k=>$v): ?>
                                <option value="<?php echo $k?$k:'' ?>" <?php if($k==$_ccExpYear): ?>selected="selected"<?php endif ?>><?php echo $v ?></option>
                            <?php endforeach ?>
                            </select>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    	</div>
    </div>
<div style="clear:both"></div>
<div id="add_payment">
	<hr />
	<div id="hpcheckout-payment-add-title">
		<h4 class="legend">Add a payment method</h4>
	</div>
	<div style="clear:both"></div>
	<div>
		<div class="pull-left" id="add_cc_types">
		</div>
		<div id="add_cc_data"></div>
	</div>
	<div style="clear:both"></div>
	</div>
</div>
       <?php if($_isLoggedIn && $this->getVaultEnabled()):?>
   <li id="<?php echo $_code ?>_cc_type_should_save_div" class="new-card">
        <?php echo $this->__('Save Card In My Account') ?>
       <div class="input-box">
           <div class="v-fix">
               <input type="checkbox" title="<?php echo $this->__('Save Card In My Account') ?>" class="input-checkbox" id="<?php echo $_code ?>_cc_should_save" name="payment[cc_should_save]" />
           </div>
       </div>
   </li>
<?php endif; ?>

	<?php if($this->getPaypageEnabled()):?>
   		<input type="hidden" id="<?php echo $_code ?>_paypage_id" name="payment[paypage_id]" value="<?php echo $_paypageId; ?>"/>
        <input type="hidden" id="<?php echo $_code ?>_merchant_txn_id" name="payment[merchant_txn_id]" value="<?php echo $_id; ?>"/>
		<input type="hidden" id="<?php echo $_code ?>_paypage_url" name="payment[paypage_url]" value="<?php echo $_paypageUrl; ?>"/>
        <input type="hidden" id="<?php echo $_code ?>_order_id" name="payment[order_id]" value="<?php echo $_id; ?>"/>
        <input type="hidden" id="<?php echo $_code ?>_report_group" name="payment[report_group]" value="<?php echo $_reportGroup; ?>"/>
 		<input type="hidden" id="<?php echo $_code ?>_paypage_enabled" name="payment[paypage_enabled]" value="<?php echo $this->getPaypageEnabled(); ?>"/>
       	<input type="hidden" id="<?php echo $_code ?>_paypage_registration_id" name="payment[paypage_registration_id]" value=""/>
        <input type="hidden" id="<?php echo $_code ?>_bin" name="payment[bin]"/>
        <input type="hidden" id="<?php echo $_code ?>_code" name="payment[code]"/>
        <input type="hidden" id="<?php echo $_code ?>_message" name="payment[message]"/>
        <input type="hidden" id="<?php echo $_code ?>_response_time" name="payment[response_time]"/>
        <input type="hidden" id="<?php echo $_code ?>_type" name="payment[type]"/>
        <input type="hidden" id="<?php echo $_code ?>_litle_txn_id" name="payment[litle_txn_id]"/>
		<input type="hidden" id="<?php echo $_code ?>_vault_id" name="payment[paypage_id]" value="<?php echo $purchase['token']; ?>"/>
	<?php endif; ?>
</ul>

<?php if($this->getPaypageEnabled()):?>

<script type="text/javascript">

    var litlePayment = new Payment($("payment_form_<?php echo $this->getMethodCode(); ?>"),
            "<?php echo $this->getUrl('checkout/onepage/');?>");
    var formId = "payment_form_<?php echo $this->getMethodCode(); ?>";
    var litlePaymentForm = new paymentForm(formId);

    document.observe("dom:loaded", function() {
	Payment.prototype.save = function() {
		var _saveUrl = this.saveUrl;
		var _onComplete = this.onComplete;
		var _onSave = this.onSave;
		var _currentMethod = "<?php echo $_code ?>";
		var _form = this.form;

		//if (checkout.loadWaiting!=false) return;
		//var validator = new Validation(this.form);
		//if (this.validate() && validator.validate()) {
			//checkout.setLoadWaiting('payment');

			// Litle Page Stuff//
			function setLitleResponseFields(response) {
				$('<?php echo $_code ?>_code').value = response.response;
				$('<?php echo $_code ?>_message').value = response.message;
				$('<?php echo $_code ?>_response_time').value = response.responseTime;
				$('<?php echo $_code ?>_litle_txn_id').value = response.litleTxnId;
				$('<?php echo $_code ?>_type').value = response.type;
                hpcheckout.submit();
			}

			function submitAfterLitle() {
				var request = new Ajax.Request(
					_saveUrl,
					{
						method:'post',
						onComplete: _onComplete,
						onSuccess: _onSave,
						//onFailure: checkout.ajaxFailure.bind(checkout),
						parameters: Form.serialize(_form)
					}
				);
			}

			function timeoutOnLitle() {
				setLitleResponseFields();
				alert('timeout error');
				return false;
			}

			function onErrorAfterLitle(response) {
				setLitleResponseFields(response);
				alert('There was an error. Re-enter your payment information, or contact us for further assistance.');
				return false;
			}

			var formFields = {
				"accountNum" : $('<?php echo $_code ?>_cc_number'),
				"paypageRegistrationId" : $('<?php echo $_code ?>_paypage_registration_id'),
				"bin" : $('<?php echo $_code ?>_bin'),
				"cvv2" : $('<?php echo $_code ?>_cc_cid')
			};

			var litleRequest = {
				"paypageId" : $('<?php echo $_code ?>_paypage_id').value,
				"reportGroup" : $('<?php echo $_code ?>_report_group').value,
				"orderId" : $('<?php echo $_code ?>_order_id').value,
				"id" : $('<?php echo $_code ?>_merchant_txn_id').value,
				"url" : ($('<?php echo $_code ?>_paypage_url').value)
			};

            if(!hpcheckout.validate()) {
                return;
            }
            
            //this becomes a set of radio buttons instead    
            var selectmenu = $("<?php echo $_code ?>_cc_vaulted");
			if(selectmenu){
				var chosenoption=selectmenu.options[selectmenu.selectedIndex]
				if (chosenoption.value == 0){
					if( _currentMethod == "creditcard" ){
						sendToLitle(litleRequest, formFields, setLitleResponseFields, onErrorAfterLitle);
                        submitAfterLitle();
                    }
				} else {
                    submitAfterLitle();
                    hpcheckout.submit();
                }
			} else{
				if( _currentMethod == "creditcard" ){
					sendToLitle(litleRequest, formFields, setLitleResponseFields, onErrorAfterLitle);
                }
                submitAfterLitle();
			}
	    //}
	};
});
</script>
<?php endif; ?>
    </div>
</div>