<?php 
	$reportCollection = $this->getPreparedCollection();
	$poObj = $this->getPoObject();
	$vendorObj = $this->getVendorObj();
?>
<div id="report-container">
	<div id="report-header-container">
		<div id="logo-box" class="block">
			<img src="<?php echo $this->getSkinUrl('images/report_logo.png');?>"/>
			<p id="addresss"><?php echo Mage::getStoreConfig('general/store_information/address');?></p>
		</div>
		<div id="order-info" class="block">
			<h2 id="op-title"><?php echo $this->__('PURCHASE ORDER');?></h2>
			<label class="sigle-line"><?php echo $this->__('PO Number:');?></label>
			<p><?php echo $this->getPoNumber(); ?></p>
			<label class="sigle-line"><?php echo $this->__('PO Date:');?></label>
			<p><?php echo $this->getPoDate(); ?></p>
			<label class="sigle-line"><?php echo $this->__('Event Name:');?></label>
			<p><?php echo $this->getPoCategoryName(); ?></p>
			<div id="billing-info">
				<label><?php echo $this->__('BILL TO:');?></label>
				<p>TOTSY <br>10 West 18th Street <br>Fourth Floor <br>New York, New York 10011 <br>payment@totsy.com</p>
			</div>
		</div>
		<div id="vendor-info" class="block">
			<label><?php echo $this->__('VENDOR:'); ?></label>
			<p><?php echo $this->getVendorName(); ?></p>
			<p><?php echo $this->getVendorAddress(); ?></p>
			<p><?php echo $this->getContactPerson(); ?></p>
			<p><?php echo $this->getVendorEmailList(); ?></p>
			<p><?php echo $this->getTelephone(); ?></p>
		</div>	
		<div id="shipping-info" class="block">
			<label><?php echo $this->__('SHIP TO:');?></label>
			<p>TOTSY <br>c/o Dotcom Distribution <br>400 Nixon Lane <br>Edison, NJ 08837</p>
		</div>
		<div id="payment-terms" class="block">
			<label><?php echo $this->__('PAYMENT TERMS:'); ?></label>
			<p><?php echo $this->getPaymentTerms(); ?></p>
		</div>
		<table id="date-info" border="1">
			<colgroup>
				<col width="400">
				<col width="400">
			</colgroup>
			<tr>
				<td>SHIP BY DATE: <?php echo $this->getShipByDate(); ?></td>
				<td>IN HOUSE DATE: <?php echo $this->getInHouseDate(); ?></td>
			</tr>
		</table>	
	</div>
	<div id="report-table-container">
		<table id="report-table" class="data" border="1">
			<colgroup>
				<col width="100">
				<col width="100">
				<col width="450">
				<col width="100">
				<col width="100">
				<col width="100">
				<col width="100">
				<col width="100">
			</colgroup>
			<thead>
				<tr class="headings">
					<th>
						<span class="nobr">
							<a class="not-sort" title="asc" name="vendor_style" href="#">
								<span class="sort-title">Vendor Style</span>
							</a>
						</span>
					</th>
					<th>
						<span class="nobr">
							<a class="not-sort" title="asc" name="sku" href="#">
								<span class="sort-title">SKU</span>
							</a>
						</span>
					</th>
					<th>
						<span class="nobr">
							<a class="not-sort" title="asc" name="product_name" href="#">
								<span class="sort-title">Product Name</span>
							</a>
						</span>
					</th>
					<th>
						<span class="nobr">
							<a class="not-sort" title="asc" name="color" href="#">
								<span class="sort-title">Color</span>
							</a>
						</span>
					</th>
					<th>
						<span class="nobr">
							<a class="not-sort" title="asc" name="size" href="#">
								<span class="sort-title">Size</span>
							</a>
						</span>
					</th>
					<th>
						<span class="nobr">
							<a class="not-sort" title="asc" name="qty_stock" href="#">
								<span class="sort-title">Total Qty</span>
							</a>
						</span>
					</th>
					<th>
						<span class="nobr">
							<a class="not-sort" title="asc" name="average_cost" href="#">
								<span class="sort-title">Unit Cost</span>
							</a>
						</span>
					</th>
					<th class=" last">
						<span class="nobr">
							<a class="not-sort" title="asc" name="total_cost" href="#">
								<span class="sort-title">Total Cost</span>
							</a>
						</span>
					</th>
				</tr>
			</thead>
			<?php 
				$totalCost = 0;
			?>
			<tbody>
				<?php foreach ( $reportCollection as $item ):?>
					<?php
						/* Mai 2012-05-23 */
						if($item->getData('is_master_pack') == "No" && $item->getData('qty_sold') == 0) {
							continue;
						}
						
						$qty = $item->getData('qty_sold');
						
						if($item->getData('is_master_pack') == "Yes") {
							$qty = $item->getData('qty_total');
						}
						
						$cost = $qty * $item->getData('unit_cost');
					
						$totalCost += $cost;
						
					?>
					<tr>
						<td><?php echo $item->getData('vendor_style');?></td>
						<td><?php echo $item->getData('sku');?></td>
						<td><?php echo $item->getData('product_name');?></td>
						<td><?php echo $item->getData('color');?></td>
						<td><?php echo $item->getData('size');?></td>
						<td><?php echo $qty?></td>
						<td>$<?php echo number_format($item->getData('unit_cost'), 2);?></td>
						<td>$<?php echo number_format($cost, 2);?></td>
					</tr>
				<?php endforeach;?>
				
				<tr>
					<td colspan=7 style="text-align:right; padding-right:15px;">
						<strong>Total: </strong>
					</td>
					<td>$<?php echo number_format($totalCost, 2)?></td>
				</tr>
			</tbody>
		</table>
	</div>	
	<div id="report-footer-container">
		<table id="footer-table" border="1">
			<colgroup>
				<col width="400">
				<col width="400">
			</colgroup>
			<thead>
				<tr>
					<th>Banking Info</th>
					<th>AUTHORIZATION</th>
				</tr>
			</thead>
			<tbody>
				<tr>
					<td>
						<p><?php echo $this->getBankingInfo(); ?></p>
					</td>
					<td>
						<p><?php echo $this->getAuthorizationName(); ?></p>
					</td>
				<tr>
			</tbody>
		</table>
	</div>
</div>
