<?php
/**
 * Harapartners
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Harapartners License
 * that is bundled with this package in the file LICENSE_EE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.Harapartners.com/license
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@Harapartners.com so we can send you a copy immediately.
 *
 */
?>

<?php
/**
 * Catalog index list template
 * Load Top, Live, Upcoming events
 * 
 */
?>
<?php 
	$cdsDataObj 	= 	$this->getIndexDataObject();
	$baseUrl 		= 	Mage::getBaseUrl();
	$maxPerSend 	= 	0;
	$timer 			= 	0;
	$topArray 		= 	'';
	$liveArray 		= 	'';
	$upcomingArray  = 	'';	
	
	if( $cdsDataObj->hasData('toplive') ){
		$topArray = $cdsDataObj->getData('toplive');
	}
	if( $cdsDataObj->hasData('live') ){
		$liveArray = $cdsDataObj->getData('live');
	}
	if( $cdsDataObj->hasData('upcoming') ){
		$upcomingArray = $cdsDataObj->getData('upcoming');
	}
?>
<div class="catalog-events-container">
	<div class="live-events-container">
		<h1 class="event-collection-title">Today's Sales</h1>
		<div class="top-events">
			<?php foreach ($topArray as $top):?>
			<?php
				$endcountRaw = strtotime($top['event_end_date']);
				$endcount = date("F j, Y, G:i:s", $endcountRaw);
			?>
			<div class="catalog-top-event event-counter-<?php echo $timer;?>">
				<?php $imgFile = BP.DS.'media'.DS.'catalog'.DS.'category'.DS.$top['thumbnail'];?>	
				<a class="event-link" href="<?php echo Mage::getBaseUrl().$top['url_path']; ?>"><img src="<?php echo Mage::helper('service/image')->loadImageFile($imgFile)->resize(349,403); ?>" width="349px" height="403px" alt="" /></a>
				<div class="splash-details">
					<div class="table-cell-left">	
						<p class="event-name"><?php echo $top['name'];?></p>
						<p id="time1-top-<?php echo $timer ?>"></p>					 
						<script type="text/javascript">
							jQuery("#time1-top-<?php echo $timer ?>").countdown({
								//date: "12 10, 2011 16:11", //Counting TO a date
								date: "<?php echo $endcount; ?>", //Counting TO a date
								htmlTemplate: "<span>Ends in</span> %{d} <span class=\"cd-time\">Days</span> %{h}<span class=\"cd-time\">:</span>%{m}<span class=\"cd-time\">:</span>%{s}<span class=\"cd-time\"></span>",
				
								onChange: function( event, timer ){
								},
								onComplete: function( event ){										
									jQuery(this).html("Completed");
									jQuery("div.event-counter-<?php echo $timer;?>").hide();
								},
								leadingZero: true,
								direction: "down"
							});
						</script>
					</div>
					<div class="table-cell-right">
						<a class="shop-button" href="<?php echo Mage::getBaseUrl().$top['url_path']; ?>">Shop</a>
					</div>
				</div>	
			</div>	
			<?php $timer++;?>		
			<?php endforeach;?>
			<div class="catalog-top-event">
				<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('topcms')->toHtml()?>
			</div>
		</div>	
		<?php foreach ($liveArray as $live):?>
			<?php
				$endcountRaw = strtotime($live['event_end_date']);
				$endcount = date("m j, Y, G:i:s", $endcountRaw);
			?>
			<div class="catalog-event event-counter-<?php echo $timer;?>">
				<?php $imgFile = BP.DS.'media'.DS.'catalog'.DS.'category'.DS.$live['thumbnail'];?>	
				<a class="event-link" href="<?php echo Mage::getBaseUrl().$live['url_path']; ?>"><img src="<?php echo Mage::helper('service/image')->loadImageFile($imgFile)->resize(228,263); ?>" width="228px" height="263px" alt="" /></a>
				<div class="splash-details">
					<div class="table-cell-left">	
						<p class="event-name"><?php echo $live['name'];?></p>
						<p id="time1-<?php echo $timer ?>"></p>					 
						<script type="text/javascript">
							jQuery("#time1-<?php echo $timer ?>").countdown({
								//date: "12 10, 2011 16:11", //Counting TO a date
								date: "<?php echo $endcount; ?>", //Counting TO a date
								htmlTemplate: "<span>Ends in</span> %{d} <span class=\"cd-time\">Days</span> %{h}<span class=\"cd-time\">:</span>%{m}<span class=\"cd-time\">:</span>%{s}<span class=\"cd-time\"></span>",								
								onChange: function( event, timer ){
								},
								onComplete: function( event ){										
									jQuery(this).html("Completed");
									jQuery("div.event-counter-<?php echo $timer;?>").hide();
								},
								leadingZero: false,
								direction: "down"
							});
						</script>
					</div>
					<div class="table-cell-right">
						<a class="shop-button" href="<?php echo Mage::getBaseUrl().$live['url_path']; ?>">Shop</a>
					</div>
				</div>	
			</div>
			<?php $timer++;?>
		<?php endforeach;?>
	</div>

	<?php if (!!$upcomingArray && !empty($upcomingArray)):?>	
	<div class="upcoming-events-container">
		<h1 class="event-collection-title" id="event-upcoming">Upcoming Sales</h1>
		<?php foreach ($upcomingArray as $up):?>
			<?php
				$endcountRaw = strtotime($up['event_start_date']);
				$endcount = date("F j, Y, G:i:s", $endcountRaw);
			?>
			<div class="catalog-event">
				<?php $imgFile = BP.DS.'media'.DS.'catalog'.DS.'category'.DS.$up['thumbnail'];?>	
				<a class="event-link" href="<?php echo Mage::getBaseUrl().$up['url_path']; ?>"><img src="<?php echo Mage::helper('service/image')->loadImageFile($imgFile)->resize(228,263); ?>" width="228px" height="263px" alt="" /></a>
				<div class="splash-details">
					<div class="table-cell-left">	
						<p class="event-name"><?php echo $up['name'];?></p>
						<p id="time2-<?php echo $timer ?>"></p> 
						<script type="text/javascript">
							jQuery("#time2-<?php echo $timer ?>").countdown({
								//date: "12 10, 2011 16:11", //Counting TO a date
								date: "<?php echo $endcount; ?>", //Counting TO a date
								htmlTemplate: "<span>Opens in</span> %{d} <span class=\"cd-time\">Days</span> %{h}<span class=\"cd-time\">:</span>%{m}<span class=\"cd-time\">:</span>%{s}<span class=\"cd-time\"></span>",
				
								onChange: function( event, timer ){
								},
								onComplete: function( event ){										
									jQuery(this).html("Completed");
								},
								leadingZero: false,
								direction: "down"
							});
						</script>
					</div>
					<div class="table-cell-right">
						<a class="shop-button" href="<?php echo Mage::getBaseUrl().$up['url_path']; ?>">View</a>
					</div>
				</div>	
			</div>
			<?php $timer++;?>
		<?php endforeach;?>		
	</div>
	<?php endif;?>	
</div>