<?php
/**
 * Harapartners
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Harapartners License
 * that is bundled with this package in the file LICENSE_EE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.Harapartners.com/license
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@Harapartners.com so we can send you a copy immediately.
 *
 */

$topNavDataObject = $this->getTopNavDataObject();
$categoryDataArray = $topNavDataObject->getData('category_product_complete_data'); 
$howMany = count($categoryDataArray);
?>

<script type="text/javascript">
   // Code that uses jQuery's $ can follow here.
var shver= "2.8.6";
var shpb= "<?php echo $topNavDataObject->getData('attr_text_label'); ?>";
var shpn= "";
var shpc= "";
var shpp= "";
var shpb= "";
var shpi= "";
var shps= "";
var shcv= "";
var shcq= "";
var shcp= "";
var additional= "";
var aid='9577';var tdr='';if (top.document.referrer != ''){tdr = encodeURIComponent(top.document.referrer);}var plh='';if (parent.location.href != ''){plh = encodeURIComponent(parent.location.href);}shpi = encodeURIComponent(shpi);(function(){steelhouse={add:function(a,b,c,d){d=d||false;if(a.addEventListener){a.addEventListener(b,c,d)}else if(a.attachEvent){a.attachEvent("on"+b,c)}},load:function(){var a;if(typeof a=='undefined'){a=Math.random()*100000000000000000}var b=document.createElement('script');var c='px.steelhousemedia.com/st?aid='+aid+'&cb='+a+'&shcv='+shcv+'&shcq='+shcq+'&shcp='+shcp+'&shpn='+shpn+'&shpc='+shpc+'&shpp='+shpp+'&shpb='+shpb+'&shpi='+shpi+'&shps='+shps+'&tdr='+tdr+'&plh='+plh+additional;b.type='text/javascript';b.src=('https:'==document.location.protocol?'https://':'http://')+c;var d=document.getElementsByTagName('script');var e=Number(d.length)-1;var f=document.getElementsByTagName('script')[e];f.parentNode.insertBefore(b,f)}};steelhouse.load();})();

</script>

<h2><?php echo $topNavDataObject->getData('attr_text_label'); ?><span><?php echo ' ( '.$howMany.' Sales Found )';?></span></h2>

<?php foreach($categoryDataArray as $category):?>

<div class="events-div">

<?php 
	$timerParam = $category['prepare_timer'];
	$endcount_lc = $timerParam['endcount_lc'];
	$timer = $timerParam['timer'];
?>
	<a href="<?php echo Mage::getBaseUrl().$category['category_info']['url_path']; ?>"><h3 class="category-name"><?php echo $category['category_info']['name']; ?></h3></a>
	<div class="layer-timer">
		<p class="the-topnav-timer" id="time-layer-<?php echo $timer ?>"></p>					 
		<script type="text/javascript">
			jQuery("#time-layer-<?php echo $timer ?>").countdown({
				date: "<?php echo $endcount_lc; ?>", //Counting TO a date
				htmlTemplate: "<span>Ends in</span><span class='italic'> %{d} <span class=\"cd-time\">Days</span> %{h}<span class=\"cd-time\">:</span>%{m}<span class=\"cd-time\">:</span>%{s}<span class=\"cd-time\"></span></span>",

				onChange: function( event, timer ){
				},
				onComplete: function( event ){										
					jQuery(this).html("Completed");
					jQuery(this).parents('.events-div').hide();
				},
				leadingZero: true,
				direction: "down"
			});
		</script>
	</div>
	<p class="layer-description"><?php echo $category['category_info']['description']; ?></p>


		<div class="category-products">
		<ul class="products-grid">
			<?php $j=0; ?>
			<?php $nonSalableArray = array();?>
			<?php $i=0; foreach ($category['product_list'] as $_product): ?>
				<?php if (empty($_product['url_path']) || !preg_match('/sales/',$_product['url_path'])){
					$_product['url_path'] = $_product['request_path'];
				}?>
				<?php if ($_product['is_salable']==1): ?>
				<li class="item">
		        	<ul class="echoShare" 
					data-productname="<?php echo $_product['name'];?>"  
					data-productcap="" 
					data-productdesc="<?php echo $_product['description'];?>" 
					data-imageclass=""  
					sdata-producturl="<?php echo $_product['url_path']; ?>">
					</ul>
					<a href="<?php echo Mage::getBaseUrl().$_product['url_path']; ?>" title="<?php echo $_product['name']; ?>" class="product-image"><img src="<?php echo $_product['small_image']; ?>" width="125" height="125" alt="<?php echo $_product['name']; ?>" /></a>
						<a class="item-details" href="<?php echo Mage::getBaseUrl().$_product['url_path'] ?>" title="<?php echo $_product['name']; ?>">
							<h4 class="product-name">
								<?php echo $_product['name']; ?>
							</h4>
							<?php //echo $this->getPriceHtml($_product, true) ?>
							<div class="price-box">
								<span class="regular-price" id="product-price-<?php echo $_product['entity_id']; ?>">
								<?php $price = (isset($_product['special_price']))?$_product['special_price']:$_product['price']?>
									<span class="price">$<?php echo number_format($price,2,'.',''); ?></span>
								</span>
							</div>
						</a>
				</li>
				<?php 
					$i++; 
					$j = $i;
					if ($i==6){
						break;
					}
				?>
				<?php else:?>
				<?php $nonSalableArray[] = $_product;?>
				<?php endif; ?>
			<?php endforeach; ?>
			<li class="item last btn viewAllEvents">
				<a href="<?php echo Mage::getBaseUrl().$category['category_info']['url_path']; ?>">
					<img src="<?php echo $this->getSkinUrl()?>images/btn-viewevents-bug.png" />
				</a>
			</li>
		</ul>

			<script type="text/javascript">decorateGeneric($$('ul.products-grid'), ['odd','even','first','last'])</script>
		</div>
	
	<div class='vuall'>View all items from <a href="<?php echo Mage::getBaseUrl().$category['category_info']['url_path']; ?>"><?php echo $category['category_info']['name']; ?></a></div>
	
</div>
<?php endforeach ?>