<?php if ( $productData = $this->getProductData() ) : ?>
  <span itemscope itemtype="http://data-vocabulary.org/Product">
    <?php foreach ( $productData as $key => $value ) : ?>
      <meta itemprop="<?php echo $key; ?>" content="<?php echo $value; ?>" />
    <?php endforeach; ?>
    <?php if ( $data = $this->getOfferData() ) : ?>
      <span itemprop="offerDetails" itemscope itemtype="http://data-vocabulary.org/Offer">
        <?php foreach ( $data as $key => $value ) : ?>
          <meta itemprop="<?php echo $key; ?>" content="<?php echo $value; ?>" />
        <?php endforeach; ?>
        <meta itemprop="currency" content="USD" />
      </span>
    <?php endif; ?>
  </span>
<?php endif; ?>
