<?php
$_product = Mage::registry('current_product');
$_category = Mage::registry('current_category');

//include the signer
require("dev/sociablelabs/sociable_signer.php");

if( Mage::getSingleton('customer/session')->getCustomerId() ) {

    $customer_id = Mage::getSingleton('customer/session')->getCustomerId();

    $rondavu_data = array (
        "config" =>  array ( "version" => "1.2" ),
        "user" => array (
            "id" => array (
                array ( "id" => $customer_id, "type" => "totsy" )
            ),
            "tracking" => array (
                array (
                    "name" => "refId",
                    "value" => $customer_id
                )
            )
        ),
        "primary_mo" => array (
            "id" => array( array("id" => $_product->getId(), "type" => "product" )),
            "name" => array(array("name" => $_product->getName())),
            "primary_tag" => $_product->getCategory()->name,
            "tags" => array("product", $_category->getName(),
                $_product->getCategory()->name, $_category->getUrl()),
            "description"=> array(array("description" => strip_tags(html_entity_decode(str_replace(array("\r", "\n"), '', $_product->getDescription()))) )),
            "url"=> array(
                "detail" =>
                $_product->getProductUrl(),
                "picture" => array(
                    "primary" =>
                    (string) $this->helper('catalog/image')->init($_product, 'image')->resize(500),
                    "primary_secure" =>
                    str_replace("http:","https:", $this->helper('catalog/image')->init($_product, 'image')->resize(500))
                )
            )
        ,
            "price" => array(
                "retail_price" => $_product->getFinalPrice(),
                "sale_price" => $_product->getSaleWholesale(),
                "currency"=> "USD"
            )));

    // declare a path to the key
    $key_path = "dev/sociablelabs/sign_private_key";
    $socialable_labs_output = rondavu_sign($rondavu_data, $key_path);
}
?>

<script type="text/javascript">
    var socialableLabsOutput = <?php echo $socialable_labs_output ?>;
</script>

<?php echo $this->getChildHtml('sociable.footer.pixel');