
<!-- Socialable Labs 
<script type="text/javascript">

    if(socialableLabsOutput) {
        window.RondavuData = socialableLabsOutput;
    }

</script>
<script type="text/javascript">

    (function(){
        var s = document.createElement('script');
        s.async = true;

        s.src =  ('https:' == window.location.protocol ? 'https://s3.amazonaws.com/' : 'http://') +
            ('www.totsy.com' == window.location.host ? 'static.rondavu.com' +'/C/' +  'Totsy_PROD' : 'qa.rondavu.com' +'/C/' +  'Totsy_QA')  + '/rondavu.js';

        document.getElementsByTagName('head')[0].appendChild(s);
    })();
</script>

Socialable Labs -->