<?php
if( Mage::getSingleton('customer/session')->getCustomerId() ) :

    $customer_id = Mage::getSingleton('customer/session')->getCustomerId();

    //include the signer
    require("dev/sociablelabs/sociable_signer.php");

    // declare a path to the key
    $key_path = "dev/sociablelabs/sign_private_key";

    // declare RondavuData
    $rondavu_data = array (
        "config" =>  array ( "version" => "1.2" ),
        //information about the currently logged in user
        "user" => array (
            "id" => array (
                array ( "id" => $customer_id, "type" => "totsy" )
            ),
            // use tracking fields to have query params on click back. e.g. http=>//www.totsy.com?refId=user12345
            "tracking" => array (
                array (
                    "name" => "refId",
                    "value" => $customer_id
                )
            )
        ),
        "primary_mo" => array (
            "id" => array (
                array ( "id"=> "totsy", "type" => "site" )
            ),
            "name" => array (
                array ( "name" => "Totsy" )
            ),
            "url" => array (
                "detail" => "http://www.totsy.com",
                "picture" => array (
                    "primary" => "http://www.totsy.com/img/logo-125x77.png",
                    "primary_secure" => "https://www.totsy.com/img/logo-125x77.png"
                )
            )
        )
    );

    //sign it
    $socialable_labs_output = rondavu_sign($rondavu_data, $key_path);

    ?>

<?php if(isset($socialable_labs_output)) : ?>
    <script type="text/javascript">
        socialableLabsOutput = <?php echo $socialable_labs_output ?>;
    </script>
<?php endif;
    echo $this->getChildHtml('sociable.footer.pixel');
endif;
