<?php
$_product = Mage::registry('current_product');
$_category = Mage::registry('current_category');
$referring_url = Mage::registry('referring_url');
$urlParams = array();
if($_product && $_category && $_product->getId() && $_category->getId()) {
    $urlParams['category'] = $_category->getId();
    $urlParams['product'] = $_product->getId();
}
$urlParams['current_url'] = base64_encode(Mage::helper('core/url')->getCurrentUrl());
$urlParams['referrer_url'] = base64_encode($referring_url);
Mage::log('testing in steelhouse pixel');
?>
<!-- Steelhouse BEGIN -->
<div id="steelhouse_pixel"></div>
<script type="text/javascript">
    Event.observe(window,'load',function() {
        new Ajax.Updater($('steelhouse_pixel'), '<?php echo Mage::getUrl('pixels/steelhouse/index', $urlParams); ?>'
            , {method:'get',evalScripts: true});
    });

</script>
<!-- Steelhouse END -->