<div class="sp-methods" id="checkout-payment-method-load">
<?php if( ! count( $methods = $this->getMethods() ) ): ?>
	<div>No payment methods available, please try again later or contact us.</div>
<?php elseif( count( $methods ) == 1 ): ?>
	<input type="hidden" name="payment[method]" value="<?php echo $methods[0]->getCode() ?>">
	<div><?php echo $this->getPaymentMethodFormHtml( $methods[0] ) ?></div>
	<script type="text/javascript">
		jQuery( "#payment_form_<?php echo $methods[0]->getCode() ?>" ).show();
	</script>
<?php else: ?>	
<div>
</div>
<?php foreach ($methods as $_method): ?>
		<?php if ($html = $this->getPaymentMethodFormHtml($_method)): ?>
		    <div>
		        <?php echo $html; ?>
		    </div>
	    <?php endif; ?>
	<?php endforeach; ?>
<script type="text/javascript">
    jQuery( document ).ready ( function() {
    	jQuery('#payment_method').click( function() {
    	   jQuery('.validate-cybsersource-cc-type').attr("checked", false);
    		hpcheckout.switchPaymentMethod(jQuery('input[name=payment[method]]:checked', '#hpcheckout-payment-form').val());				
        });
        jQuery('.validate-cybsersource-cc-type').click( function() {
            jQuery('#payment_method').attr("checked", false);
            jQuery("#payment_form_paypal_express").hide();
            jQuery("#cc_data").show();
    		hpcheckout.switchPaymentMethod('_paymentfactory_tokenize');				
        });
    });	
</script>
<?php endif ?>