<div class="sp-methods" id="checkout-payment-method-load span6">
    <?php if(!count( $methods = $this->getMethods())): ?>
        <div>No payment methods available, please try again later or contact us.</div>
    <?php elseif( count( $methods ) == 1 ): ?>
        <div>
            <input type="hidden" name="payment[method]" value="<?php echo $methods[0]->getCode(); ?>"> 
            <?php echo $this->getPaymentMethodFormHtml( $methods[0] ) ?>
        </div>
    <?php else: ?>
        <div class="hpcheckout-payment-title">
            <h4 class="legend">Your payment methods</h4>
        </div>
        <!--
        security icon used to be here
        -->
        <?php foreach (array_reverse($methods) as $_method):  $_code = $_method->getCode() ?>
            <?php //if($_code != 'paymentfactory_tokenize'): ?>
                <?php if ($html = $this->getPaymentMethodFormHtml($_method)): ?>
                <div>
                    <?php echo $html; ?>
                </div>
                <?php endif; ?>
            <?php //endif; ?>
        <?php endforeach; ?>
    <?php endif ?>
 </div>
 <div id="paypal_container">
 </div>
<script type="text/javascript">
    jQuery(document).ready( function() {   
        if(jQuery('input:radio[name=paypal_payment]')) {
            jQuery('input:radio[name=paypal_payment]').click( function() {
                jQuery('.validate-cybsersource-cc-type').attr("checked", false);
        	       jQuery('input[name="payment[method]"]').val("paypal_express");
                hpcheckout.switchPaymentMethod('paypal_express');			
            });
        }    
		
        jQuery('.validate-cybsersource-cc-type').click( function() {
            if(jQuery('#paypal_payment').length > 0) {
                jQuery('#paypal_payment').attr("checked", false);
            }
            if(jQuery("#payment_form_paypal_express").length > 0) {
                jQuery("#payment_form_paypal_express").hide();
            }
            jQuery("#cc_data").show();
            jQuery('input[name="payment[method]"]').val("creditcard");
    		hpcheckout.switchPaymentMethod('creditcard');		
        });
    });	
</script>