<?php
    $_code = $this->getMethodCode();
    $hasVirtual = false;
    $_quote = Mage::getSingleton('checkout/session')->getQuote();
    // Check to see if there are multiple fulfillment types
    foreach($_quote->getAllItems() as $item) {
        if($item->getParentItemId()) {
            continue;
        }
        $product = Mage::getModel ( 'catalog/product' )->load ( $item->getProductId () );
        if($product->getIsVirtual() && $product->getFulfillmentType() !== 'nominal') {
            $_fulfillmentType = 'virtual';
            $hasVirtual = true;
        } else {
            $_fulfillmentType = $product->getFulfillmentType();
        }
        $fulfillmentTypes [$_fulfillmentType] [] = $item->getId ();
    }

    $multiShipping = false;
    if(count($fulfillmentTypes) > 1) {
        $multiShipping = true;
    }

    $_reportGroup = $this->getReportGroup();
    $_paypageId = Mage::getModel('Litle_CreditCard_Model_PaymentLogic')->getConfigData("paypage_id");
    $_paypageUrl = Mage::getModel('Litle_CreditCard_Model_PaymentLogic')->getConfigData("paypage_url");
    $_isLoggedIn = Mage::helper('customer')->isLoggedIn();

    $_time =  date('ymdHis');
    $_session =  Mage::getModel("core/session")->getEncryptedSessionId();
    $_id = $_time . substr($_session,13);
?>
<div class="form-list one-page-payment" id="payment_form_<?php echo $_code ?>">

<script type="text/javascript">
    jQuery(document).ready( function() {

        if(hasCBProfile==false) {
            checkoutPayment.hasProfile = "<?php echo $this->hasStoredCards(); ?>";
        }
        checkoutPayment.toggleViews();

        jQuery("[name='payment[cc_vaulted]'],[name='payment[cybersource_subid]']").change( function() {
            checkoutPayment.setPaymentUI(this);
        });

        jQuery(".use-saved-card-control").click( function() {
            checkoutPayment.useSavedCard(this);
        });
        jQuery(".cc_types input").click( function() {
            checkoutPayment.setPaymentType(this);
        });
    });
</script>

<div>
    <div>
        <div>
            <div class="cc_types use-new-card-wrapper input-box validation-error pull-left">
                <?php $_ccType = $this->getInfoData('cc_type') ?>
                <div id="<?php echo $_code ?>_cc_type">
                    <?php foreach ($this->getCcAvailableTypes() as $_typeCode => $_typeName): ?>
                        <input type="radio" name="payment[cc_type]" value="<?php echo $_typeCode ?>" <?php if ($_typeCode==$_ccType) { echo "checked"; } ?> />
                        <span class="cc">
                            <span title="<?php echo $_typeName; ?>"  class="<?php echo strtolower($_typeCode); ?>" >
                            </span>
                        </span>
                    <?php endforeach ?>
                    <?php $methods = $this->getLayout()->getBlock('hpcheckout.payment.methods')->getMethods();  ?>
                    <?php if(count($methods)): ?>
                        <?php if(!$multiShipping && !$hasVirtual && Mage::getModel('paypal/config')->isMethodActive('paypal_express')): ?>
                            <input type="radio" value="paypal_express" id="paypal_payment" name="paypal_payment">
                            <div>
                                <span title="Paypal Express" class="paypal"></span>
                                <a class="what-is-paypal-link" href="https://www.paypal.com/cgi-bin/webscr?cmd=xpt/Marketing/popup/OLCWhatIsPayPal-outside" target="_blank">What is<br /> PayPal?</a>
                            </div>
                        <?php endif; ?>
                    <?php endif; ?>
                    <div style="clear:both; height:10px"></div>
                </div>
            </div>
        </div>
        <div style="clear:both"></div>
        <?php if($this->getVaultEnabled() && $this->hasStoredCards()) { ?>
            <div class="pull-left" id="use-card-method">
                <div id="cybersource-use-card-method">
                    <table class="saved_card">
                        <tr>
                            <th></th>
                            <th></th>
                            <th></th>
                            <th></th>
                            <th></th>
                        </tr>
                        <?php foreach ($this->getStoredCards() as $card): ?>
                            <?php
                                $lastCardUsed = Mage::helper('litle')->getLastCardUsed();
                                $customerAddress = Mage::getModel('customer/address')->load($card->getData('address_id'));
                                $customerName = $customerAddress->getFirstname() ." ". $customerAddress->getLastname();
                                $customerStreet = $customerAddress['street'];
                            ?>
                            <tr>
                                <td>
                                    <div>
                                        <input type="radio" data-billing-address-id="<?php echo $card->address_id; ?>" id="payment[cc_vaulted]" name="payment[cc_vaulted]" value="<?php echo $card->getVaultId() ?>"
                                            <?php if($lastCardUsed && ($lastCardUsed->getId() == $card->getVaultId()) && (!$lastCardUsed->getSubscriptionId()))  echo 'checked="yes"'; ?> class="use-saved-card-control pull-left" id="payment">
                                                <span class="cc">
                                                    <span title="<?php echo strtolower($card->type); ?>" class="<?php echo strtolower($card->type); ?>" >
                                                    </span>
                                               </span>
                                        <strong><?php $card->getTypeName(); ?></strong>
                                    </div>
                                </td>
                                <td class="card-type"> ending in <?php echo $card->getData('last4'); ?></td>
                                <td class="card-name"><?php echo $customerName; ?></td>
                                <td class="billing-address"><?php echo $customerStreet; ?></td>
                                <td class="card-expdate"><?php echo $card->getData('expiration_month')."/".$card->getData('expiration_year'); ?></td>
                            </tr>
                        <?php endforeach ?>
                        </div>
                        <script type="text/javascript">
                            Event.observe($("<?php echo $_code ?>_cc_vaulted"), 'change', function() {
                                if ($F(this) != '0') {
                                    $$('.new-card').invoke('hide');
                                    $('<?php echo $_code ?>_cc_cid').value="";
                                    $$('.cid-class').invoke('show');
                                } else {
                                    $$('.new-card').invoke('show');
                                    $('<?php echo $_code ?>_cc_cid').value="";
                                    $('<?php echo $_code ?>_cc_type').value = "";
                                    $('<?php echo $_code ?>_expiration').value = "";
                                    $('<?php echo $_code ?>_expiration_yr').value = "";
                                    $('<?php echo $_code ?>_cc_should_save').setValue(false);
                                    $$('.cid-class').invoke('show');
                                }
                            });
                        </script>
                    </table>
                </div>
            </div>
        <?php } ?>
    </div>
</div>
<div id="credits_and_card_save">
    <div class="cc_save_card use-new-card-wrapper cc_info">
        <?php if($_isLoggedIn && $this->getVaultEnabled()):?>
            <div id="<?php echo $_code ?>_cc_type_should_save_div" class="new-card">
                <?php echo $this->__('Save Card') ?>
                <span>
                    <input type="checkbox" title="<?php echo $this->__('Save Card') ?>" class="input-checkbox" id="<?php echo $_code ?>_cc_should_save" checked='checked' name="payment[cc_should_save]" />
                </span>
            </div>
        <?php endif; ?>
    </div>
    <div id="rewards_points">
        <?php echo $this->getLayout()->getBlock('hpcheckout.reward.points')->toHtml(); ?>
    </div>
</div>
<div id="cc_data">
    <div class="pull-left">
        <div>
            <div class="pull-left cc_num use-new-card-wrapper cc_info">
                <div class="input-box">
                    <input type="text" id="<?php echo $_code ?>_cc_number" name="payment[cc_number]" title="<?php echo $this->__('Credit Card Number') ?>" class="input-text" value="<?php echo (($this->__('Credit Card Number')!=='Credit Card Number') ? $this->__('Credit Card Number') : "") ?>" placeholder="<?php echo $this->__('Credit Card Number') ?>" />
                </div>
                <div class="validation-advice" id="cc-num-error-message" style="display:none">Credit card number does not match credit card type</div>
            </div>
        </div>
        <div style="clear:both"></div>
        <div>
            <?php if ($this->hasVerification()): ?>
                <div class="cc_cvn pull-left use-new-card-wrapper cc_info">
                    <label for="<?php echo $_code ?>_cc_cid" class="required"><em>*</em><?php echo $this->__('CVN#') ?></label>
                    <div class="input-box">
                        <div class="v-fix">
                            <input type="text" title="<?php echo $this->__('Card Verification Number') ?>" class="input-text cvv validate-cc-cvn-radio" id="<?php echo $_code ?>_cc_cid" name="payment[cc_cid]" value="<?php echo (($this->__('Card Verification Number')!=="Card Verification Number") ? $this->__('Card Verification Number') : "") ?>" placeholder="<?php echo $this->__('CVN#') ?>" />
                        </div>
                    </div>
                </div>
            <?php endif; ?>
            <div id="add_payment_save_card">
            </div>
            <div class="cc_exp pull-right use-new-card-wrapper cc_info">
                <div class="pull-left">
                    <div for="<?php echo $_code ?>_expiration" class="lbl"><em>*</em><?php echo $this->__('Exp.') ?></div>
                    <div class="pull-left">
                        <div class="pull-left">
                            <select id="<?php echo $_code ?>_expiration" name="payment[cc_exp_month]" class="month validate-cc-exp">
                                <?php $_ccExpMonth = $this->getInfoData('cc_exp_month') ?>
                                <?php foreach ($this->getCcMonths() as $k=>$v): ?>
                                    <option value="<?php echo $k?$k:'' ?>" <?php if($k==$_ccExpMonth): ?>selected="selected"<?php endif ?>><?php echo $v ?></option>
                                <?php endforeach ?>
                            </select>
                        </div>
                        <div class="pull-right">
                            <select id="<?php echo $_code ?>_expiration_yr" name="payment[cc_exp_year]" class="year">
                                <?php $_ccExpYear = $this->getInfoData('cc_exp_year') ?>
                                <?php foreach ($this->getCcYears() as $k=>$v): ?>
                                    <option value="<?php echo $k?$k:'' ?>" <?php if($k==$_ccExpYear): ?>selected="selected"<?php endif ?>><?php echo $v ?></option>
                                <?php endforeach ?>
                            </select>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<div style="clear:both"></div>
<div id="add_payment">
    <span class="add_payment_separator"><hr /></span>
    <div id="hpcheckout-payment-add-title">
        <h4 class="legend">Add a payment method</h4>
    </div>
    <div style="clear:both"></div>
    <div>
        <div class="pull-left" id="add_cc_types">
        </div>
        <div id="add_cc_data"></div>
    </div>
    <div style="clear:both"></div>
</div>
<?php if($this->getPaypageEnabled()):?>
    <input type="hidden" id="<?php echo $_code ?>_paypage_id" name="payment[paypage_id]" value="<?php echo $_paypageId; ?>"/>
    <input type="hidden" id="<?php echo $_code ?>_merchant_txn_id" name="payment[merchant_txn_id]" value="<?php echo $_id; ?>"/>
    <input type="hidden" id="<?php echo $_code ?>_paypage_url" name="payment[paypage_url]" value="<?php echo $_paypageUrl; ?>"/>
    <input type="hidden" id="<?php echo $_code ?>_order_id" name="payment[order_id]" value="<?php echo $_id; ?>"/>
    <input type="hidden" id="<?php echo $_code ?>_report_group" name="payment[report_group]" value="<?php echo $_reportGroup; ?>"/>
    <input type="hidden" id="<?php echo $_code ?>_paypage_enabled" name="payment[paypage_enabled]" value="<?php echo $this->getPaypageEnabled(); ?>"/>
    <input type="hidden" id="<?php echo $_code ?>_paypage_registration_id" name="payment[paypage_registration_id]" value=""/>
    <input type="hidden" id="<?php echo $_code ?>_bin" name="payment[bin]"/>
    <input type="hidden" id="<?php echo $_code ?>_code" name="payment[code]"/>
    <input type="hidden" id="<?php echo $_code ?>_message" name="payment[message]"/>
    <input type="hidden" id="<?php echo $_code ?>_response_time" name="payment[response_time]"/>
    <input type="hidden" id="<?php echo $_code ?>_type" name="payment[type]"/>
    <input type="hidden" id="<?php echo $_code ?>_litle_txn_id" name="payment[litle_txn_id]"/>
    <input type="hidden" id="<?php echo $_code ?>_vault_id" name="payment[vault_id]" value="<?php echo $purchase['token']; ?>"/>
    <input type="hidden" id="<?php echo $_code ?>_method" name="payment[method]" value="creditcard">
<?php endif; ?>
<?php if($this->getPaypageEnabled()):?>
    <script type="text/javascript">

        var litlePayment = new Payment($("payment_form_<?php echo $this->getMethodCode(); ?>"),
            "<?php echo $this->getUrl('checkout/onepage/');?>");
        var formId = "payment_form_<?php echo $this->getMethodCode(); ?>";
        var litlePaymentForm = new paymentForm(formId);

        document.observe("dom:loaded", function() {
            Payment.prototype.save = function() {
                var _saveUrl = this.saveUrl;
                var _onComplete = this.onComplete;
                var _onSave = this.onSave;
                var _currentMethod = "<?php echo $_code ?>";
                var _form = this.form;
                // Litle Page Stuff//
                function setLitleResponseFields(response) {
                    $('<?php echo $_code ?>_code').value = response.response;
                    $('<?php echo $_code ?>_message').value = response.message;
                    $('<?php echo $_code ?>_response_time').value = response.responseTime;
                    $('<?php echo $_code ?>_litle_txn_id').value = response.litleTxnId;
                    $('<?php echo $_code ?>_type').value = response.type;
                    hpcheckout.submit();
                }

                function submitAfterLitle() {
                    var request = new Ajax.Request(
                        _saveUrl,
                        {
                            method:'post',
                            onComplete: _onComplete,
                            onSuccess: _onSave,
                            //onFailure: checkout.ajaxFailure.bind(checkout),
                            parameters: Form.serialize(_form)
                        }
                    );
                }

                function timeoutOnLitle() {
                    setLitleResponseFields();
                    alert('timeout error');
                    return false;
                }

                function onErrorAfterLitle(response) {
                    setLitleResponseFields(response);
                    //alert('There was an error. Re-enter your payment information, or contact us for further assistance.');
                    return false;
                }

                var formFields = {
                    "accountNum" : $('<?php echo $_code ?>_cc_number'),
                    "paypageRegistrationId" : $('<?php echo $_code ?>_paypage_registration_id'),
                    "bin" : $('<?php echo $_code ?>_bin'),
                    "cvv2" : $('<?php echo $_code ?>_cc_cid')
                };

                var litleRequest = {
                    "paypageId" : $('<?php echo $_code ?>_paypage_id').value,
                    "reportGroup" : $('<?php echo $_code ?>_report_group').value,
                    "orderId" : $('<?php echo $_code ?>_order_id').value,
                    "id" : $('<?php echo $_code ?>_merchant_txn_id').value,
                    "url" : ($('<?php echo $_code ?>_paypage_url').value)
                };

                if(!hpcheckout.validate()) {
                    return;
                }

                if(typeof checkoutPayment!=="undefined" && !checkoutPayment.validateCardType()) {
                    return;
                }
                //this becomes a set of radio buttons instead
                var selectmenu = $("<?php echo $_code ?>_cc_vaulted");
                if(selectmenu){
                    var chosenoption=selectmenu.options[selectmenu.selectedIndex]
                    if (chosenoption.value == 0){
                        if( _currentMethod == "creditcard" ){
                            sendToLitle(litleRequest, formFields, setLitleResponseFields, onErrorAfterLitle);
                            submitAfterLitle();
                        }
                    } else {
                        submitAfterLitle();
                        hpcheckout.submit();
                    }
                } else {
                    if( _currentMethod == "creditcard" ){
                        sendToLitle(litleRequest, formFields, setLitleResponseFields, onErrorAfterLitle);
                    }
                    submitAfterLitle();
                }
            };
        });
    </script>
<?php endif; ?>
</div>
</div>