<?php
/**
 * Harapartners
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Harapartners License
 * that is bundled with this package in the file LICENSE_EE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.Harapartners.com/license
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@Harapartners.com so we can send you a copy immediately.
 *
 */
?>

<?php
/**
 * Catalog index list template
 * Load Top, Live, Upcoming events
 * @see Mage_Catalog_Block_Catalog_List
 */
?>
<?php 
	$cdsDataObj 	= 	$this->getCdsDataObject();
	$isFaceBook 	= 	Mage::getSingleton('customer/session')->getFacebookAccountFirstCreate();
	$baseUrl 		= 	Mage::getBaseUrl();
	$maxPerSend 	= 	0;
	$timer 			= 	0;
	$topArray 		= 	'';
	$liveArray 		= 	'';
	$upcomingArray  = 	'';	
	
	if( $cdsDataObj->hasData('toplive') ){
		$topArray = $cdsDataObj->getData('toplive');
	}
	if( $cdsDataObj->hasData('live') ){
		$liveArray = $cdsDataObj->getData('live');
	}
	if( $cdsDataObj->hasData('upcoming') ){
		$upcomingArray = $cdsDataObj->getData('upcoming');
	}
?>


<?php if ( !!$isFaceBook && $isFaceBook ):?>
	<a id="facebook_pop" href="#facebook_window" class="hidden"></a>
	<div style="display: none;">
		<div id="facebook_window">
			<div class="window_content">	
				<h3><img src="<?php echo $this->getSkinUrl()?>images/facebook_pop.png" width="40px" height="40px"></img>Thanks for Joining Totsy!</h3>
				<p>	Please retrieve your temporary password through your email and update it in your <a  class="needgreen" href="<?php echo $this->getBaseUrl()?>customer/account/edit/changepass/1/">account panel</a></p>
			</div>
		</div>
	</div>
	
	<script type="text/javascript">
	    jQuery(document).ready(function() {
	    	jQuery("#facebook_pop").fancybox({
				'speedIn'		:	600, 
				'speedOut'		:	200, 
			}).trigger('click');
	    });
	</script>
	<?php Mage::getSingleton('customer/session')->setFacebookAccountFirstCreate(false);?>
<?php elseif( (Mage::getSingleton('customer/session')->getData('login_refer')) && (Mage::helper('enterprise_invitation')->isInvitationMessageAllowed()) && $storeId==1 ):?>
	<a id="invite_pop" href="#invite_window" class="hidden"></a>
	<div style="display: none;">
		<div id="invite_window" >
			<div class="little-title">
			    <h2><?php echo Mage::helper('enterprise_invitation')->__('Send Invitations') ?></h2>
				<hr class="the-hr"/>
				<p class="invite-notes">
				<?php $inviteFriendNotes = "For each friend you invite, Totsy will credit your account with <span class='needgreen'>$15</span> after your friend's place their first order."; ?>
				<?php echo Mage::helper('enterprise_invitation')->__($inviteFriendNotes); ?>
				</p>
			</div>
			<form id="invitationForm" action="<?php echo $this->helper('enterprise_invitation')->getCustomerInvitationFormUrl()?>" method="post">
			    <div class="fieldset">		
			        <ul class="form-list">
			            <?php //$_perRow = ceil($maxPerSend/3); for($_index = 1; $_index <= $maxPerSend; $_index ++): ?>
			            <li class="email-add-box">
							<label for="email"><?php echo Mage::helper('enterprise_invitation')->__('Enter Your Friends Email Addresses:');?> </label>
			                <div class="input-box">
			                    <textarea id="contact_list" tabindex="<?php //echo $_index+1 ?>" name="email" id="inviteemailaddress" title="<?php echo Mage::helper('enterprise_invitation')->__('email') ?>"  class="input-text" rows="3" cols="4"></textarea>
			                </div>
			               
			            </li>
			            <?php //endfor; ?>
			        <?php if (Mage::helper('enterprise_invitation')->isInvitationMessageAllowed()): ?>
			            <li class="email-msg-box">
			                <label for="message"><?php echo Mage::helper('enterprise_invitation')->__('Personalized Message To Friends:');?> </label>
			                <div class="input-box">
			                    <textarea tabindex="<?php //echo $_index+1 ?>" name="message" id="message" title="<?php echo Mage::helper('enterprise_invitation')->__('Message') ?>"  class="input-text" rows="3" cols="4"><?php echo 'Please accept this invitation to join Totsy'; ?></textarea>
			                </div>
			            </li>
			        </ul>
			        <?php endif;?>
			    </div>
			   <!--p class="required"><?php echo Mage::helper('enterprise_invitation')->__('* Required Fields') ?></p-->
			    <div class="buttons-set form-buttons">
			        <!--p class="back-link"><a href="<?php echo Mage::helper('enterprise_invitation')->getCustomerInvitationUrl() ?>"><small>&laquo; </small><?php  echo Mage::helper('enterprise_invitation')->__('Back to Invitations') ?></a></p-->
			        <button class="button" type="submit"><div class="invite-button"><?php echo Mage::helper('enterprise_invitation')->__('Send Invitations') ?></div></button>
			    </div>			
			</form>
			<script type="text/javascript">
			    var contactForm = new VarienForm('invitationForm', false);
			</script>
		</div>
	</div>
	
	<script type="text/javascript">
	    jQuery(document).ready(function() {
	    	jQuery("#invite_pop").fancybox({
				'speedIn'		:	600, 
				'speedOut'		:	200, 
			}).trigger('click');
	    });
	</script>
<?php Mage::getSingleton('customer/session')->setData('login_refer',false);?>
<?php endif; ?>

<div class="catalog-events-container">
	<div class="live-events-container">
		<h1 class="event-collection-title">Today's Sales</h1>
		<div class="top-events">
			<?php foreach ($topArray as $top):?>
			<?php
				$endcountRaw = strtotime($top['event_end_date']);
				$endcount = date("F j, Y, G:i:s", $endcountRaw);
			?>
			<div class="catalog-top-event">
				<?php $imgFile = BP.DS.'media'.DS.'catalog'.DS.'category'.DS.$top['thumbnail'];?>	
				<a class="event-link" href="<?php echo Mage::getBaseUrl().$top['url_path']; ?>"><img src="<?php echo Mage::helper('service/image')->loadImageFile($imgFile)->resize(349,403); ?>" width="349px" height="403px" alt="" /></a>
				<div class="splash-details">
					<div class="table-cell-left">	
						<p class="event-name"><?php echo $top['name'];?></p>
						<p id="time1-top-<?php echo $timer ?>"></p>					 
						<script type="text/javascript">
							jQuery("#time1-top-<?php echo $timer ?>").countdown({
								//date: "12 10, 2011 16:11", //Counting TO a date
								date: "<?php echo $endcount; ?>", //Counting TO a date
								htmlTemplate: "<span>Ends in</span> %{d} <span class=\"cd-time\">Days</span> %{h}<span class=\"cd-time\">:</span>%{m}<span class=\"cd-time\">:</span>%{s}<span class=\"cd-time\"></span>",
				
								onChange: function( event, timer ){
								},
								onComplete: function( event ){										
									jQuery(this).html("Completed");
								},
								leadingZero: true,
								direction: "down"
							});
						</script>
					</div>
					<div class="table-cell-right">
						<a class="shop-button" href="<?php echo Mage::getBaseUrl().$top['url_path']; ?>">Shop</a>
					</div>
				</div>	
			</div>	
			<?php $timer++;?>		
			<?php endforeach;?>
			<div class="catalog-top-event">
				<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('topcms')->toHtml()?>
			</div>
		</div>	
		<?php foreach ($liveArray as $live):?>
			<?php
				$endcountRaw = strtotime($live['event_end_date']);
				$endcount = date("F j, Y, G:i:s", $endcountRaw);
			?>
			<div class="catalog-event">
				<?php $imgFile = BP.DS.'media'.DS.'catalog'.DS.'category'.DS.$live['thumbnail'];?>	
				<a class="event-link" href="<?php echo Mage::getBaseUrl().$live['url_path']; ?>"><img src="<?php echo Mage::helper('service/image')->loadImageFile($imgFile)->resize(228,263); ?>" width="228px" height="263px" alt="" /></a>
				<div class="splash-details">
					<div class="table-cell-left">	
						<p class="event-name"><?php echo $live['name'];?></p>
						<p id="time1-<?php echo $timer ?>"></p>					 
						<script type="text/javascript">
							jQuery("#time1-<?php echo $timer ?>").countdown({
								//date: "12 10, 2011 16:11", //Counting TO a date
								date: "<?php echo $endcount; ?>", //Counting TO a date
								htmlTemplate: "<span>Ends in</span> %{d} <span class=\"cd-time\">Days</span> %{h}<span class=\"cd-time\">:</span>%{m}<span class=\"cd-time\">:</span>%{s}<span class=\"cd-time\"></span>",
				
								onChange: function( event, timer ){
								},
								onComplete: function( event ){										
									jQuery(this).html("Completed");
								},
								leadingZero: true,
								direction: "down"
							});
						</script>
					</div>
					<div class="table-cell-right">
						<a class="shop-button" href="<?php echo Mage::getBaseUrl().$live['url_path']; ?>">Shop</a>
					</div>
				</div>	
			</div>
			<?php $timer++;?>
		<?php endforeach;?>
	</div>

	<?php if (!!$upcomingArray && !empty($upcomingArray)):?>	
	<div class="upcoming-events-container">
		<h1 class="event-collection-title" id="event-upcoming">Upcoming Sales</h1>
		<?php foreach ($upcomingArray as $up):?>
			<?php
				$endcountRaw = strtotime($up['event_end_date']);
				$endcount = date("F j, Y, G:i:s", $endcountRaw);
			?>
			<div class="catalog-event">
				<?php $imgFile = BP.DS.'media'.DS.'catalog'.DS.'category'.DS.$up['thumbnail'];?>	
				<a class="event-link" href="<?php echo Mage::getBaseUrl().$up['url_path']; ?>"><img src="<?php echo Mage::helper('service/image')->loadImageFile($imgFile)->resize(228,263); ?>" width="228px" height="263px" alt="" /></a>
				<div class="splash-details">
					<div class="table-cell-left">	
						<p class="event-name"><?php echo $up['name'];?></p>
						<p id="time2-<?php echo $timer ?>"></p> 
						<script type="text/javascript">
							jQuery("#time2-<?php echo $timer ?>").countdown({
								//date: "12 10, 2011 16:11", //Counting TO a date
								date: "<?php echo $endcount; ?>", //Counting TO a date
								htmlTemplate: "<span>Opens in</span> %{d} <span class=\"cd-time\">Days</span> %{h}<span class=\"cd-time\">:</span>%{m}<span class=\"cd-time\">:</span>%{s}<span class=\"cd-time\"></span>",
				
								onChange: function( event, timer ){
								},
								onComplete: function( event ){										
									jQuery(this).html("Completed");
								},
								leadingZero: true,
								direction: "down"
							});
						</script>
					</div>
					<div class="table-cell-right">
						<a class="shop-button" href="<?php echo Mage::getBaseUrl().$up['url_path']; ?>">View</a>
					</div>
				</div>	
			</div>
			<?php $timer++;?>
		<?php endforeach;?>		
	</div>
	<?php endif;?>	
</div>