<?php
/**
 * Harapartners
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Harapartners License
 * that is bundled with this package in the file LICENSE_EE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.Harapartners.com/license
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@Harapartners.com so we can send you a copy immediately.
 *
 */
?>

<?php
/**
 * Catalog index list template
 * Load Top, Live, Upcoming events
 * 
 */
?>
<?php 
	$indexDataObj 	= 	$this->getIndexDataObject();
	$isFaceBook 	= 	Mage::getSingleton('customer/session')->getFacebookAccountFirstCreate();
	$baseUrl 		= 	Mage::getBaseUrl();
	$maxPerSend 	= 	0;
	$timer 			= 	0;
	$topArray 		= 	'';
	$liveArray 		= 	'';
	$upcomingArray  = 	'';	
	
	if( $indexDataObj->hasData('toplive') ){
		$topArray = $indexDataObj->getData('toplive');
		$topArray = array(); //Harapartners, yang: temploary block the top events
	}
    if ( $indexDataObj->hasData('live_queue') ){
        $liveArray = json_decode($indexDataObj->getData('live_queue'), true);
    }
    if ( $indexDataObj->hasData('upcoming_queue') ){
        $upcomingArray = json_decode($indexDataObj->getData('upcoming_queue'), true);
    }
?>


<?php if ( !!$isFaceBook && $isFaceBook ):?>
	<a id="facebook_pop" href="#facebook_window" class="hidden"></a>
	<div style="display: none;">
		<div id="facebook_window">
			<div class="window_content">	
				<h3><img src="<?php echo $this->getSkinUrl()?>images/facebook_pop.png" width="40px" height="40px"></img>Thanks for Joining Totsy!</h3>
				<p>	Please retrieve your temporary password through your email and update it in your <a  class="needgreen" href="<?php echo $this->getBaseUrl()?>customer/account/edit/">account panel</a></p>
			</div>
		</div>
	</div>
	
	<script type="text/javascript">
	    jQuery(document).ready(function() {
	    	jQuery("#facebook_pop").fancybox({
				'speedIn'		:	600, 
				'speedOut'		:	200, 
			}).trigger('click');
	    });
	</script>
	<?php Mage::getSingleton('customer/session')->setFacebookAccountFirstCreate(false);?>
<?php endif; ?>

<div class="catalog-events-container">
	<form class="ui-listview-filter ui-bar-c" role="search">
		<div class="ui-input-search ui-shadow-inset ui-btn-corner-all ui-btn-shadow ui-icon-searchfield ui-body-c">
			<input class="ui-input-text ui-body-c" placeholder="Filter Sales..." onkeyup="namefilter()" data-type="search" id="name-filter">
		</div>
	</form>
	<div class="live-events-box">
		<ul class="live-events-container">
			<?php foreach ($liveArray as $live):?>
			<?php
				$endcountRaw = strtotime($live['event_end_date']);
				$endcount = date("F j, Y, G:i:s", $endcountRaw);
				$hasProduct = $this->countCategoryProducts($live['entity_id']);
				$imgFile = BP.DS.'media'.DS.'catalog'.DS.'category'.DS.$live['thumbnail'];
			?>
			<?php if ($hasProduct):?>
			<li class="catalog-event ui-btn-up-c live-event-<?php echo $timer?>">
				<div class="ui-btn-text ">
					<a class="event-link" href="<?php echo Mage::getBaseUrl().$live['url_path']; ?>">
						<img src="<?php echo Mage::helper('service/image')->loadImageFile($imgFile)->resize(80,92); ?>" width="80px" height="80px" alt=""></img>
						<h3 class="event-name"><?php echo $live['name'];?></h3>
						<p id="time1-<?php echo $timer ?>"></p>					 
						<script type="text/javascript">
							var html = getTimerHtml('live','<?php echo $endcount ?>');
							jQuery("#time1-<?php echo $timer ?>").countdown({
								//date: "12 10, 2011 16:11", //Counting TO a date
								date: "<?php echo $endcount; ?>", //Counting TO a date
								htmlTemplate: html,
								onComplete: function( event ){										
									jQuery(this).html("Completed");
									jQuery("li.live-event-<?php echo $timer?>").hide();
								},
								leadingZero: true,
								direction: "down"
							});
						</script>
						<span class="ui-icon ui-icon-arrow-r ui-icon-shadow hp-ui-icon-right"></span>
						<div class="clear"></div>
					</a>
				</div>	
			</li>
			<?php $timer++;?>
			<?php endif;?>
			<?php endforeach;?>
		</ul>
	</div>
	<?php if (!!$upcomingArray && !empty($upcomingArray)):?>	
	<div class="upcoming-events-box">
		<h3 class="event-collection-title" id="event-upcoming">Upcoming Sales</h3>
		<hr/>
		<ul class="upcoming-events-container">
		<?php foreach ($upcomingArray as $up):?>
			<?php 
				$endcountRaw = strtotime($up['event_start_date']);
				$endcount = date("F j, Y, G:i:s", $endcountRaw);
			?>
			<li class="catalog-event ui-btn-up-c up-event-<?php echo $timer?>">			
				<div class="ui-btn-text">
					<a class="event-link" href="<?php echo Mage::getBaseUrl().$up['url_path']; ?>">
						<p class="event-name"><?php echo $up['name'];?></p>
						<p id="time2-<?php echo $timer ?>"></p> 
						<script type="text/javascript">
							var html = getTimerHtml('upcoming','<?php echo $endcount ?>');
							jQuery("#time2-<?php echo $timer ?>").countdown({
								//date: "12 10, 2011 16:11", //Counting TO a date
								date: "<?php echo $endcount; ?>", //Counting TO a date
								htmlTemplate: html,
								onComplete: function( event ){										
									jQuery(this).html("Completed");
									jQuery("li.up-event-<?php echo $timer?>").hide();
								},
								leadingZero: true,
								direction: "down"
							});
						</script>
						<span class="ui-icon ui-icon-arrow-r ui-icon-shadow hp-ui-icon-right"></span>
						<div class="clear"></div>
					</a>
				</div>	
			</li>
			<?php $timer++;?>
		<?php endforeach;?>	
		</ul>
	</div>
	<?php endif;?>	
</div>
<script>
	function namefilter(){
		//alert(jQuery('#name-filter').val());
		var searchName = jQuery('#name-filter').val();
		var patt=new RegExp(searchName,"i");
		jQuery(".live-events-box .event-link .event-name").each(function(){
			var eventName = jQuery(this).html();
			if (eventName.match(patt) == null){
				jQuery(this).parent().hide();
			}else{
				jQuery(this).parent().show();
			}
		})
		;
	}
</script>
