<?php
/**
 * {magecore_license_notice}
 *
 * @category   design
 * @package    enterprise_iphone
 * @copyright  {magecore_copyright}
 * @license    {magecore_license}
 */
/**
 * @var $this Oro_Sales_Block_Order_Info_Button
 */
?>
<?php if ($this->isShowEditBilling()): ?>
    <span class="separator">|</span>
    <a href="<?php echo $this->getEditBillingUrl() ?>"><?php echo $this->__('Edit Billing Info') ?></a>
<?php endif; ?>
