<?php
/**
 * {magecore_license_notice}
 *
 * @category   design
 * @package    enterprise_iphone
 * @copyright  {magecore_copyright}
 * @license    {magecore_license}
 */
/**
 * @var $this Oro_Sales_Block_Order_Billing_Edit
 * @var $profile Harapartners_Paymentfactory_Model_Profile
 */

$paymentCode    = $this->getPaymentMethod()->getCode();

?>
<div class="page-header">
    <h2><?php echo $this->__('Edit Order #%s Billing Info', $this->getOrder()->getIncrementId()) ?></h2>
</div>
<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<form id="order-billing-edit-form" action="<?php echo $this->getFormActionUrl() ?>" method="POST">
<div class="well alfa">
    <?php if ($this->hasPaymentMethods()): ?>
    <h4 class="table-caption"><?php echo $this->__('Your payment methods') ?></h4>
    <div class="pull-left" id="use-card-method">
        <div id="cybersource-use-card-method">
            <table class="saved_card">
                <tr>
                    <th></th>
                    <th></th>
                    <th><?php echo $this->__('Name on card') ?></th>
                    <th><?php echo $this->__('Billing address') ?></th>
                    <th><?php echo $this->__('Expires') ?></th>
                </tr>
                <?php foreach ($this->getPaymentCollection() as $profile): ?>
                <?php if (!$this->canShowPaymentProfile($profile)): continue; endif; ?>
                <?php $address = $this->getProfileAddress($profile); ?>
                <tr>
                    <td>
                        <input type="radio" name="payment[cybersource_subid]" id="payment_cybersource_subid_<?php echo $profile->getId() ?>"
                               class="use-saved-card-control pull-left" value="<?php echo $profile->getEncryptedSubscriptionId() ?>">
                        <span class="cc">
                            <span title="<?php echo $this->getFullCcType($profile->getCardType()); ?>" class="<?php echo strtolower($profile->getCardType()); ?>"></span>
                        </span>
                    </td>
                    <td class="card-type">
                        <strong><?php echo $this->getFullCcType($profile->getCardType()); ?></strong> ending in <?php echo $profile->getLast4no() ?>
                    </td>
                    <td class="card-name"><?php echo $this->escapeHtml($this->getAddressCustomerName($address)) ?></td>
                    <td class="billing-address"><?php echo $this->escapeHtml($address->getStreet1()); ?></td>
                    <td class="card-expdate"><?php echo $profile->getExpireMonth() ?>/<?php echo $profile->getExpireYear() ?></td>
                </tr>
                <?php endforeach; ?>
            </table>
        </div>
    </div>
    <div style="clear:both;"></div>
    <?php endif; ?>
    <h4 class="legend"><?php echo $this->__('Add a payment method') ?></h4>
    <div class="cc_types input-box validation-error pull-left">
        <div id="payment_cc_type">
        <?php foreach ($this->getCcAvailableTypes() as $ccCode => $ccName): ?>
            <input type="radio" class="validate-cybsersource-cc-type" name="payment[cc_type]" value="<?php echo $ccCode ?>" />
            <span class="cc">
                <span title="<?php echo $this->escapeHtml($ccName); ?>" class="<?php echo strtolower($ccCode); ?>"></span>
            </span>
        <?php endforeach ?>
            <div style="clear:both; height:10px"></div>
        </div>
    </div>

    <div id="cc_info" class="oro-cc-info">
    <div class="pull-left">
        <div>
            <div class="pull-left cc_num cc_info">
                <div class="input-box">
                    <input type="text" id="<?php echo $paymentCode ?>_cc_number" name="payment[cc_number]"
                           title="<?php echo $this->__('Credit Card Number') ?>" class="input-text validate-cc-number validate-cc-type-radio"
                           placeholder="<?php echo $this->__('Credit Card Number') ?>" autocomplete="off" />
                </div>
            </div>
        </div>
        <div style="clear:both"></div>
        <div>
            <?php if ($this->hasVerification()): ?>
            <div class="cc_cvn pull-left cc_info">
                <label for="<?php echo $paymentCode ?>_cc_cid" class="required"><em>*</em><?php echo $this->__('CVN#') ?></label>
                <div class="input-box">
                    <div class="v-fix">
                        <input type="text" title="<?php echo $this->__('Card Verification Number') ?>" class="input-text cvv validate-cc-cvn-radio"
                               id="<?php echo $paymentCode ?>_cc_cid" name="payment[cc_cid]"
                               placeholder="<?php echo $this->__('CVN#') ?>" autocomplete="off" />
                    </div>
                </div>
            </div>
            <?php endif; ?>
            <div class="cc_save_card cc_info">
                <div>
                    <input type="checkbox" value="1" name="payment[saved_by_customer]" checked="checked"
                           id="<?php echo $paymentCode ?>_cc_save" class="no-required">
                </div>
                <label for="<?php echo $paymentCode ?>_cc_save"><?php echo $this->__('Save') ?></label>
            </div>
            <div class="cc_exp pull-right cc_info">
                <div class="pull-left">
                    <div for="<?php echo $paymentCode ?>_expiration" class="lbl"><em>*</em><?php echo $this->__('Exp.') ?></div>
                    <div class="pull-left">
                        <div class="pull-left">
                            <select id="<?php echo $paymentCode ?>_expiration" name="payment[cc_exp_month]" class="month validate-cc-exp">
                            <?php foreach ($this->getCcMonths() as $k => $v): ?>
                                <option value="<?php echo $k ? $k : '' ?>"><?php echo $this->escapeHtml($v) ?></option>
                            <?php endforeach ?>
                            </select>
                        </div>
                        <div class="pull-right">
                            <select id="<?php echo $paymentCode ?>_expiration_yr" name="payment[cc_exp_year]" class="year">
                            <?php foreach ($this->getCcYears() as $k=>$v): ?>
                                <option value="<?php echo $k ? $k : '' ?>"><?php echo $this->escapeHtml($v) ?></option>
                            <?php endforeach ?>
                            </select>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div style="clear:both;"></div>
    </div>

    <div id="billing-address" class="addresses billing-address-oro pull-left well">
        <div class="checkout-headline">
            <h4 class="legend pull-left"><?php echo $this->__('Billing Address') ?></h4>
            <?php if ($this->customerHasAddresses()): ?>
                <span class="billing-address-select totsy-selective-input-box pull-right">
                    <?php echo $this->getAddressesHtmlSelect() ?>
                </span>
            <?php endif; ?>
        </div>
        <div style="clear:both"></div>
        <div id="billing-address-form">
            <div class="clearfix">
                <div class="pull-left left-well">
                    <label for="billing:firstname" class="required"><em>*&nbsp;</em><?php echo $this->__('First Name') ?></label>
                    <input type="text" name="billing[firstname]" title="<?php echo $this->__('First Name') ?>"
                           class="input-text required-entry firstname validate-alpha" value=""
                           placeholder="<?php echo $this->__('First Name') ?>" id="billing:firstname" />
                </div>
                <div>
                    <label for="billing:lastname" class="required"><em>*&nbsp;</em><?php echo $this->__('last name') ?></label>
                    <input type="text" name="billing[lastname]" title="<?php echo $this->__('Last Name') ?>"
                           class="input-text required-entry lastname validate-alpha" value=""
                           placeholder="<?php echo $this->__('Last Name') ?>" id="billing:lastname" />
                </div>
            </div>
            <input type="hidden" name="billing[email]" id="billing:email" value="<?php echo $this->getCustomer()->getEmail() ?>" />
            <input type="hidden" name="billing[selected]" id="billing:selected" />
            <div class="clearfix">
                <div>
                    <label for="billing:street1" class="required"><em>*&nbsp;</em><?php echo $this->__('Street Address Line 1') ?></label>
                    <input type="text" title="<?php echo $this->__('Street Address Line 1') ?>" name="billing[street][0]"
                           id="billing:street1" value="" class="input-text required-entry streetaddress1"
                           placeholder="<?php echo $this->__('Street Address Line 1') ?>" />
                </div>
            </div>
            <div class="clearfix">
                <div class="pull-left">
                    <label for="billing:street2">&nbsp;<?php echo $this->__('Street Address Line 2') ?></label>
                    <input type="text" title="<?php echo $this->__('Street Address Line 2') ?>" name="billing[street][1]"
                           id="billing:street2" value="" class="input-text streetaddress2"
                           placeholder="<?php echo $this->__('Street Address Line 2') ?>" />
                </div>
            </div>
            <div class="clearfix">
                <div class="pull-left left-well">
                    <label for="billing:city" class="required"><em>*&nbsp;</em><?php echo $this->__('City') ?></label>
                    <input type="text" title="<?php echo $this->__('City') ?>" name="billing[city]" class="input-text oro-city required-entry city"
                           value="" placeholder="<?php echo $this->__('City') ?>" id="billing:city" />
                </div>
                <div class="pull-left left-well">
                    <label for="billing:region_id" class="required"><em>*&nbsp;</em><?php echo $this->__('State') ?></label>
                    <div class="totsy-selective-input-box">
                        <select id="billing:region_id" name="billing[region_id]" title="<?php echo $this->__('State') ?>" class="validate-select oro-region state">
                            <option value=""><?php echo $this->__('Please select state') ?></option>
                        </select>
                    </div>
                    <script type="text/javascript">
                        $('billing:region_id').setAttribute('defaultValue', "");
                    </script>
                    <input type="text" id="billing:region" name="billing[region]" value=""
                           title="<?php echo $this->__('State/Province') ?>" class="input-text hidden-state"
                           style="display:none;" />
                </div>
                <div>
                    <label for="billing:postcode" class="required"><em>*&nbsp;</em><?php echo $this->__('zip/postal code') ?></label>
                    <input type="text" title="<?php echo $this->__('Zip Code') ?>" name="billing[postcode]"
                           id="billing:postcode" class="input-text validate-zip oro-zip required-entry zip"
                           value="" placeholder="<?php echo $this->__('Zip/Postal Code') ?>" />
                </div>
            </div>
            <div class="last-billing-form-row">
                <div class="field pull-left">
                    <label for="billing:telephone" class="required"><em>*&nbsp;</em><?php echo $this->__('telephone') ?></label>
                    <input type="text" name="billing[telephone]" title="<?php echo $this->__('Telephone') ?>"
                           class="input-text required-entry validate-phoneLax telephone" id="billing:telephone"
                           value="" placeholder="Telephone"/>
                </div>
            </div>
            <div style="display:none;">
                <label for="billing:country_id" class="required"><em>*&nbsp;</em><?php echo $this->__('country') ?></label>
                <div class="totsy-selective-input-box totsy-selective-input-box-billing-country country">
                    <?php echo $this->getCountryHtmlSelect() ?>
                    <script type="text/javascript">
                        $('billing:country_id').setAttribute('defaultValue', "US");
                    </script>
                </div>
            </div>
        </div>
    </div>
    <div class="clear"></div>
    <div class="buttons-set" id="buttons-container">
        <hr />
        <button id="saveBilling" type="button" title="<?php echo $this->__('Save Billing') ?>" class="button btn btn-primary">
            <div class="totsy-button"><?php echo $this->__('Update Billing Information') ?></div>
        </button>
    <div class="clear"></div>
    </div>
</div>

<script type="text/javascript">
Validation.addAllThese([
    ['validate-cc-type-radio', 'Please enter a valid credit card number.', function(v, elm) {
        var ccType;
        var ccTypes = $$("[name='" + elm.name.replace(/cc_number/, 'cc_type') + "']");
        ccTypes.each(function(e){
            if (e.checked) { ccType = e.value; }
            e.observe('change', function(event, element){
                Validation.validate(element);
            }.bindAsEventListener(this, elm));
        });

        if (typeof Validation.creditCartTypes.get(ccType) != 'undefined') {
            var re = Validation.creditCartTypes.get(ccType)[0];
            v = removeDelimiters(v);
            if (v.match(re)) {
                return true;
            }
            return false;
        }

        return validateCreditCard(v);
    }],
    ['validate-cc-cvn-radio', 'Please enter a valid credit card verification number.', function(v, elm) {
        var ccType;
        var ccTypes = $$("[name='" + elm.name.replace(/cc_cid/, 'cc_type') + "']");
        ccTypes.each(function(e){
            if (e.checked) { ccType = e.value; }
            e.observe('change', function(event, element){
                Validation.validate(element);
            }.bindAsEventListener(this, elm));
        });

        if (typeof Validation.creditCartTypes.get(ccType) == 'undefined') {
            return false;
        }

        var re = Validation.creditCartTypes.get(ccType)[1];

        if (v.match(re)) {
            return true;
        }

        return false;
    }]]);
var countryRegions = <?php echo $this->helper('directory')->getRegionJson() ?>;
var billingRegionUpdater = new RegionUpdater('billing:country_id', 'billing:region', 'billing:region_id', countryRegions, undefined, 'billing:postcode');
var editBilling = (function() {
    return {
        initialize: function() {
            jQuery('[name="payment[cybersource_subid]"]').change(editBilling.useProfile);
            jQuery('[name="payment[cc_type]"]').change(editBilling.newPayment);
            jQuery('#billing-address-select').change(editBilling.changeAddress);
            jQuery('#saveBilling').click(editBilling.save);

            editBilling.showCcInfo(false);
            editBilling.changeAddress();
            editBilling.form = new VarienForm('order-billing-edit-form', false);
        },
        useProfile: function() {
            editBilling.showCcInfo(false);
            editBilling.resetPayment();
            var addressId = editBilling.profileAddresses[this.value];
            editBilling.setAddress(addressId);
            editBilling.disableAddressSelect(true);
        },
        newPayment: function() {
            editBilling.showCcInfo(true);
            editBilling.resetProfile();
            editBilling.disableAddressSelect(false);
        },
        resetProfile: function() {
            jQuery('[name="payment[cybersource_subid]"]').each(function(){
                jQuery(this).attr('checked', false);
            });
        },
        resetPayment: function() {
            jQuery('[name="payment[cc_type]"]').each(function(){
                jQuery(this).attr('checked', false);
            });
        },
        showCcInfo: function(trigger) {
            var container = jQuery('#cc_info');
            if (trigger === true) {
                container.show();
                jQuery('#cc_info select, #cc_info input').each(function(){
                    if (jQuery(this).hasClass('no-required')) {return;}
                    jQuery(this).addClass('required-entry');
                });
            } else {
                container.hide();
                jQuery('#cc_info select, #cc_info input').each(function(){
                    if (jQuery(this).hasClass('no-required')) {return;}
                    jQuery(this).removeClass('required-entry');
                });
            }
        },
        disableAddressSelect: function(trigger) {
            jQuery('#billing-address-select').attr('disabled', trigger);
        },
        disableAddressForm: function(trigger) {
            jQuery('#billing-address-form input, #billing-address-form select').each(function() {
                jQuery(this).attr('disabled', trigger);
            });
        },
        setAddress: function(addressId) {
            jQuery('#billing-address-select').val(addressId);
            editBilling.changeAddress();
        },
        changeAddress: function() {
            var select = jQuery('#billing-address-select');
            var addressId = select.val();
            if (!addressId) {
                addressId = 0;
            }
            var data   = editBilling.addresses[addressId];
            if (!data) {
                data = {};
            }
            jQuery('#billing-address-form input, #billing-address-form select').each(function() {
                var value, idx = this.id.substr(8);
                if (idx in data) {
                    value = data[idx];
                } else {
                    value = jQuery(this).attr('defaultValue');
                }
                if (typeof value == 'undefined') {
                    value = '';
                }

                this.value = value;
            });

            editBilling.disableAddressForm(addressId ? true : false);
        },
        save: function() {
            var hasPayment = false;
            jQuery('[name="payment[cybersource_subid]"]').each(function(){
                if (this.checked) {
                    hasPayment = true;
                }
            });
            jQuery('[name="payment[cc_type]"]').each(function(){
                if (this.checked) {
                    hasPayment = true;
                }
            });

            if (!hasPayment) {
                alert('Please choose Payment method');
            }

            if (hasPayment && editBilling.form.validator.validate()) {
                jQuery('#saveBilling').attr('disabled', true);
                editBilling.form.submit();
            }
        },
        form: null,
        paymentForm: false,
        profileAddresses: [],
        addresses: []
    };
})();

editBilling.profileAddresses = <?php echo $this->getPaymentAddressJson() ?>;
editBilling.addresses = <?php echo $this->getAddressesJson() ?>;
editBilling.initialize();

</script>

</form>
