<div>
<script type="text/javascript"> 
	jQuery(document).ready(function(){	
		jQuery(".date-pick").datepicker({ showOn: 'both',  buttonImageOnly: true,    buttonImage: '<?php echo $this->getSkinUrl()?>calendar.png',
			   buttonText: 'datepicker', maxDate: "+1", dateFormat: 'yy-mm-dd'});
	})
</script>
<h1><?php echo $this->__('Affiliate Report:')?></h1>
	<form action="<?php echo $this->getUrl("adminhtml_affiliate/adminhtml_report/result"); ?>" method="post" >
	<?php $affiliateCollection = Mage::getModel('affiliate/record')->getCollection()
																	->addFieldToFilter('status','1') ?>
	<?php echo $this->getLayout()->getBlock('formkey')->toHtml(); ?>
		<div class="time_period required">
			<div class="from"><?php echo $this->__('From:')?><input type="text" name="from" class="date-pick"/></div>
			<div class="to"><?php echo $this->__('To:')?><input type="text" name="to" class="date-pick"/></div>
		</div>
		<div class="affiliate_code required"><?php echo $this->__('Choose Affiliate Code: ')?>
			<select name="affiliate_code" >
			<?php foreach ($affiliateCollection as $affiliate): ?>
				<option value="<?php echo $affiliate->getId() ?>">
				<?php echo $affiliate->getAffiliateCode() ?> 
				</option>					
			<?php endforeach;?>
			</select>
			<input type="checkbox" name="all" /> <?php echo $this->__(' Include all sub affiliate')?>
		</div><!--
		<div class="sub_affiliate_code"><?php echo $this->__('Specified Sub Affiliate Code If Applicable: ')?> <input type="text" name="sub_affiliate_code" /></div>
		--><div class="report_type required"><?php echo $this->__('Choose Report Type: ')?>
			<select name="report_type" >
				<option value="totalregistrations">
				Total Registrations
				</option>
				<option value="totalrevenue">
				Total Revenue
				</option>
				<option value="totalbounces">
				Total Bounces
				</option>				
				<option value="effectivecoreg">
				Effective Co-reg
				</option>					
			</select>
		</div>		
		<button type="submit" title="<?php echo $this->__('Get Report') ?>" class="button"><span><span><?php echo $this->__('Get Report') ?></span></span></button>
	</form>
</div>