<?php
$_sales_products = Array();
$_product = Array();
$_category = Array();
$_referring_url = "";
$_productId = "";
$_categoryId = "";

//pass al products in sale (when we're on a sales page) 
/*
if(Mage::registry('current_sales_products')) {
	$_sales_products = implode(",", Mage::registry('current_sales_products'));    
} */

if(Mage::registry('current_product')) {
    $_product = Mage::registry('current_product');
    $_productId = $_product->getId();
}

if(Mage::registry('current_category')) {
    $_category = Mage::registry('current_category');
    $_categoryId = $_category->getId();
}

if (Mage::registry('referring_url')) {
    $referring_url = Mage::registry('referring_url');
}

//check if not on the signup page or if this isn't the post-registration landing page, or the purchase success page 
if (!($this->getRequest()->getActionName()=="create" && $this->getRequest()->getModuleName()=="customer") &&
!($this->getRequest()->getActionName()=="welcome" && $this->getRequest()->getModuleName()=="customertracking")):
?>
<!-- Steelhouse BEGIN -->
<div id="steelhouse_product_pixel"></div>
<script type="text/javascript">
    Event.observe(window,'load',function() {
        new Ajax.Updater({success: 'steelhouse_product_pixel'}, '<?php echo Mage::getUrl('pixels/steelhouse/index'
        , array('product'=>$_productId,'category'=>$_categoryId, 'current_url'=> base64_encode(Mage::helper('core/url')->getCurrentUrl()),'referrer_url'=> base64_encode($_referring_url))); ?>'
            , { method:'get',evalScripts: true });
    });
</script>
<!-- Steelhouse END -->
<?php endif; ?>