<?php
/**
 * Harapartners
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Harapartners License
 * that is bundled with this package in the file LICENSE_EE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.Harapartners.com/license
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@Harapartners.com so we can send you a copy immediately.
 *
 */
?>
<?php
/**
 * Catalog index list template
 * Load Top, Live, Upcoming events
 * @see Mage_Catalog_Block_Catalog_List
 */
?>
<?php
	$sortDate = Mage::getSingleton('customer/session')->getData('categoryevent_sort_queue_date');
	$storeId = Mage::getSingleton('customer/session')->getData('categoryevent_sort_queue_store');
	$isFaceBook = Mage::getSingleton('customer/session')->getFacebookAccountFirstCreate();
	$pageNumber = $this->getPageNumber();
	$arrayCollection = $this->renderSortCollection($sortDate, $storeId);
	$topArray = $this->loadTopCollection($storeId, $sortDate);
	$liveArray = $arrayCollection['live'];
	$upcomingArray = $arrayCollection['upcoming'];
	$maxPerSend = 0;
?>

<?php if ( !!$isFaceBook && $isFaceBook ):?>
	<a id="facebook_pop" href="#facebook_window" class="hidden"></a>
	<div style="display: none;">
		<div id="facebook_window">
			<div class="window_content">	
				<h3><img src="<?php echo $this->getSkinUrl()?>images/facebook_pop.png" width="40px" height="40px"></img>Thanks for Joining Totsy!</h3>
				<p>	Please retrieve your temporary password through your email and update it in your <a  class="needgreen" href="<?php echo $this->getBaseUrl()?>customer/account/edit/">account panel</a></p>
			</div>
		</div>
	</div>
	<script type="text/javascript">
	    jQuery(document).ready(function() {
	    	jQuery("#facebook_pop").fancybox({
				'speedIn'		:	600, 
				'speedOut'		:	200, 
			}).trigger('click');
	    });
	</script>
	<?php Mage::getSingleton('customer/session')->setData('login_refer',false);?>
<?php endif;?>

<script>
	function filter(){
		var html = jQuery('#filter').val()
		alert('d');
	}
</script>
<div class="catalog-events-container">
	<form class="ui-listview-filter ui-bar-c" role="search">
		<div class="ui-input-search ui-shadow-inset ui-btn-corner-all ui-btn-shadow ui-icon-searchfield ui-body-c">
			<input id="filter" class="ui-input-text ui-body-c" onkeyup="filter()" placeholder="Filter Sales...placeholder for now" data-type="search" />
		</div>
	</form>
	<div class="live-events-box">
		<ul class="live-events-container">
			<?php foreach ($topArray as $top):?>
			<?php 
				$timerSet = $this->setCountDownTimer($top['event_end_date']);
				$timer = $timerSet['timer'];
				$endcount = $timerSet['endcount'];
				$imgFile = BP.DS.'media'.DS.'catalog'.DS.'category'.DS.$top['thumbnail'];
			?>
			<li class="catalog-top-event ui-btn-up-c">
				<div class="ui-btn-text">	
					<a class="event-link" href="<?php echo Mage::getBaseUrl().$top['url_path']; ?>">
						<img src="<?php echo Mage::helper('service/image')->loadImageFile($imgFile)->resize(80,80); ?>" width="80px" height="80px" alt="" ></img>
						<h3 class="event-name"><?php echo $top['name'];?></h3>
						<p id="time1-top-<?php echo $timer ?>"></p>					 
						<script type="text/javascript">
							jQuery("#time1-top-<?php echo $timer ?>").countdown({
								//date: "12 10, 2011 16:11", //Counting TO a date
								date: "<?php echo $endcount; ?>", //Counting TO a date
								htmlTemplate: "<span>Ends in</span> %{d} <span class=\"cd-time\">Days</span> %{h}<span class=\"cd-time\">:</span>%{m}<span class=\"cd-time\">:</span>%{s}<span class=\"cd-time\"></span>",
				
								onChange: function( event, timer ){
								},
								onComplete: function( event ){										
									jQuery(this).html("Completed");
								},
								leadingZero: true,
								direction: "down"
							});
						</script>
						<span class="ui-icon ui-icon-arrow-r ui-icon-shadow hp-ui-icon-right "></span>
						<div class="clear"></div>
					</a>
				</div>	
			</li>			
			<?php endforeach;?>
	
			<?php foreach ($liveArray as $live):?>
			<?php 
				$timerSet = $this->setCountDownTimer($live['event_end_date']);
				$timer = $timerSet['timer'];
				$endcount = $timerSet['endcount'];
				$imgFile = BP.DS.'media'.DS.'catalog'.DS.'category'.DS.$live['thumbnail'];
			?>
			<li class="catalog-event ui-btn-up-c">
				<div class="ui-btn-text">
					<a class="event-link" href="<?php echo Mage::getBaseUrl().$live['url_path']; ?>">
						<img src="<?php echo Mage::helper('service/image')->loadImageFile($imgFile)->resize(80,80); ?>" width="80px" height="80px" alt=""></img>
						<h3 class="event-name"><?php echo $live['name'];?></h3>
						<p id="time1-<?php echo $timer ?>"></p>					 
						<script type="text/javascript">
							jQuery("#time1-<?php echo $timer ?>").countdown({
								//date: "12 10, 2011 16:11", //Counting TO a date
								date: "<?php echo $endcount; ?>", //Counting TO a date
								htmlTemplate: "<span>Ends in</span> %{d} <span class=\"cd-time\">Days</span> %{h}<span class=\"cd-time\">:</span>%{m}<span class=\"cd-time\">:</span>%{s}<span class=\"cd-time\"></span>",
				
								onChange: function( event, timer ){
								},
								onComplete: function( event ){										
									jQuery(this).html("Completed");
								},
								leadingZero: true,
								direction: "down"
							});
						</script>
						<span class="ui-icon ui-icon-arrow-r ui-icon-shadow hp-ui-icon-right"></span>
						<div class="clear"></div>
					</a>
				</div>	
			</li>
			<?php endforeach;?>
		</ul>
		<div class="show-more-controller" id="show-more-live" <?php if ( (count($liveArray)<$pageNumber) ):?>style="display:none"<?php endif;?> onclick="loadEventsBlock(1);">
			<div class="show-more-banner" id="start-ajax-live" ><span>Show More</span></div>
		</div>
	</div>
	<?php if (!!$upcomingArray && !empty($upcomingArray)):?>	
	<div class="upcoming-events-box">
		<h1 class="event-collection-title" id="event-upcoming">Upcoming Sales</h1>
		<hr/>
		<ul class="upcoming-events-container">
		<?php foreach ($upcomingArray as $up):?>
			<?php 
				$timerSet = $this->setCountDownTimer($up['event_start_date']);
				$timer = $timerSet['timer'];
				$endcount = $timerSet['endcount'];
			?>
			<li class="catalog-event ui-btn-up-c">			
				<div class="ui-btn-text">
					<a class="event-link" href="<?php echo Mage::getBaseUrl().$up['url_path']; ?>">
						<p class="event-name"><?php echo $up['name'];?></p>
						<p id="time2-<?php echo $timer ?>"></p> 
						<script type="text/javascript">
							jQuery("#time2-<?php echo $timer ?>").countdown({
								//date: "12 10, 2011 16:11", //Counting TO a date
								date: "<?php echo $endcount; ?>", //Counting TO a date
								htmlTemplate: "<span>Opens in</span> %{d} <span class=\"cd-time\">Days</span> %{h}<span class=\"cd-time\">:</span>%{m}<span class=\"cd-time\">:</span>%{s}<span class=\"cd-time\"></span>",
				
								onChange: function( event, timer ){
								},
								onComplete: function( event ){										
									jQuery(this).html("Completed");
								},
								leadingZero: true,
								direction: "down"
							});
						</script>
						<span class="ui-icon ui-icon-arrow-r ui-icon-shadow hp-ui-icon-right"></span>
						<div class="clear"></div>
					</a>
				</div>	
			</li>
		<?php endforeach;?>	
		</ul>
		<div class="show-more-controller" id="show-more-upcoming" <?php if ( (count($upcomingArray)<$pageNumber) ):?>style="display:none"<?php endif;?> onclick="loadEventsBlock(2)">
			<div class="show-more-banner" id="start-ajax-upcoming" ><span>Show More</span></div>
		</div>	
	</div>
	<?php endif;?>	
</div>

<script type="text/javascript">
	function loadEventsBlock(event){
		if(event == 1){
			var block = 'live';
		}else if(event == 2){
			var block = 'upcoming';
		}
		jQuery.ajax({
			type: "GET",
			url: "<?php echo $this->getBaseUrl();?>catalog/ajax/update/flag/"+event,
			dataType: "json",
			success: function(ajaxResponse){
	         	if(ajaxResponse.status == 1){
		         	jQuery("."+block+"-events-container").append(ajaxResponse.html_content);
		         	jQuery(".ajax-event-"+block+"-display").fadeIn();
		         	jQuery("#start-ajax-"+block).fadeIn();
		         	if(ajaxResponse.page_checker == 1)	{
		         		jQuery("#show-more-"+block).fadeOut();
		         	}
	         	}else if(ajaxResponse.status == 0){
	         		jQuery("#show-more-"+block).fadeOut();
	         	}else if(ajaxResponse.error){
		         	alert(ajaxResponse.error_message);
	         	}
	        }						
		});
	}
</script>

