<?php 
if((($this->getRequest()->getActionName()!=="view" && $this->getRequest()->getControllerName()!=="catalog") || $this->getRequest()->getControllerName()=="category") &&  ($this->getRequest()->getActionName()!=="success" && $this->getRequest()->getControllerName()!=="checkout")): ?>
<!-- Social Labs BEGIN -->
<div id="sociable_header_pixel"></div>
<script type="text/javascript">
    var socialableLabsOutput = false;
        
    jQuery(window).load( function() {            
        jQuery.ajax({
            url: '<?php echo Mage::getUrl('pixels/sociable/header', array('_secure'=>Mage::app()->getStore()->isCurrentlySecure())); ?>',
            success: function (data) {
                if (data) {
                    jQuery('#sociable_header_pixel').html(data);
                }    
            }
        });       
    } );
</script>
<!-- Social Labs END -->
<?php endif;
