<body class="app p-status p-status-503">

<div id="totsy" class="container_16 roundy glow">
<header class="group">
<h1><em>Totsy - </em>We're taking a scheduled time-out.</h1>
</header>
<section>
<p>Totsy is down for some quick maintenance to improve your shopping experience. </p>
<p>We apologize for any inconvenience and will be back soon.</p>
<p>In the meantime, feel free to contact <a href="http://totsy.custhelp.com/app/ask" title="Email Totsy Support">Customer Support</a> if you'd like more information regarding this scheduled maintenance.
</section>
</div>

<div id="footer">
<span id="copyright">&copy; 2013 Totsy.com. All Rights Reserved.</span>
</div>

<script type="text/javascript">
var _gaq = _gaq || [];
_gaq.push(['_setAccount', 'UA-675412-15']);
_gaq.push(['_trackPageview']);

(function() {
var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
})();
</script>
</body>
