<!doctype html>
<html>
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<title>Woopsies - Totsy [500 Internal Server Error]</title>
	<link rel="stylesheet" type="text/css" href="/errors/totsy/css/base.css" />
	<link rel="stylesheet" type="text/css" href="/errors/totsy/css/960.css" />
	<link href="img/favicon.ico" title="Icon" type="image/x-icon" rel="icon" />
	<link href="img/favicon.ico" title="Icon" type="image/x-icon" rel="shortcut icon" />
</head>

<?php require_once $contentTemplate; ?>

</html>

