<div id="userinfo">
    <?php echo $this->getChildHtml('customertracking.headermsg');?>
</div>
<div id="usercart" class="group">
    <?php //Place holder for session check, may be remove later?>
    <?php if ( true ): ?>
    <?php echo $this->getChildHtml('topCart') ?>
    <?php //echo $this->getChildHtml('checkoutLinks') ?>
    <a class="btn checkout" title="Checkout" href="<?php echo Mage::getUrl('checkout/cart')?>"><strong>Checkout</strong></a>
    <?php else :?>
    <?php echo 'JS here'?>
    <?php endif;?>
</div>