<?php $customer = Mage::getSingleton('customer/session')->getCustomer();?>
<div class="validation-form-container">
    <form name="validation-check-form" method="post" action="<?php echo $this->getUrl('customer/revalidate/validationcheckpost',array('_secure'=>true)); ?>">
        <div class="fieldset">
            <h2>Validation Required</h2>
            <p><?php echo $this->__("Sorry, for the interruption! Please sign in again to continue shopping. If you need help with your password, click ")?><a style="font-weight:bold; color:#ED1C25" href="<?php echo $this->getUrl('customer/account/forgotpassword')?>"><?php echo $this->__("here")?></a></p>
            <ul class="form-list emailpassword">
                <li>
                    <label for="email" class="required">Email <em>*</em></label>
                    <div class="input-box">
                        <input name="login[username]" id="email" type="text" class="input-text required-entry validate-email" title="Email Address" value="<?php echo $customer->getEmail();?>"/>
                    </div>
                </li>
                <li>
                    <label for="password" class="required">Password <em>*</em></label>
                    <div class="input-box">
                        <input name="login[password]" id="password" autocomplete="off" type="password" class="input-text required-entry validate-password" title="Password" value=""/>
                    </div>
                </li>
            </ul>
            <div class="buttons-set form-buttons btn-only">
                <a href="<?php echo $this->getUrl('customer/account/logout', array('_secure' => true)) ?>">Not You?</a>
                <button type="submit" class="button" name="send" id="send2">
                    <div class="sign-in-button">Submit</div>
                </button>
            </div>
        </div>
    </form>
</div>
