<?php

$multiShipping = FALSE;
$fulfillmentTypes = array();
$TotsyPLUS = false;

// Check to see if there are multiple fulfillment types
foreach($this->getItems() as $item) {
    if($item->getParentItemId()) {
        continue;
    }
    if($item->getProductId() == Mage::getStoreConfig('Crown_Club/clubgeneral/club_product_id')) {
        $TotsyPLUS = true;
    }
    $product = Mage::getModel ( 'catalog/product' )->load ( $item->getProductId () );
//        if($product->getIsVirtual()) {
//            continue;
//        }
    $fulfillmentTypes [$product->getFulfillmentType ()] [] = $item->getId ();
}

if(count($fulfillmentTypes) > 1) {
    $multiShipping = TRUE;
}

// Split cart check
$splitCartFlag = Mage::getSingleton('checkout/session')->getSplitCartFlag() ? 'checked="checked"' : '';
?>

<div id="checkout-review-table-wrapper" >
    <table class="data-table cart-table table table-bordered table-condensed" id="checkout-review-table">
        <?php if ($this->helper('tax')->displayCartBothPrices()): $colspan = $rowspan = 2; else: $colspan = $rowspan = 1; endif; ?>
        <col/>
        <col/>
        <?php if ($this->helper('tax')->displayCartBothPrices()): ?>
        <col/>
        <col/>
        <?php endif; ?>
        <thead>
            <tr>
                <th><?php echo $this->__('Product Name') ?></th>
                <th><?php echo !$TotsyPLUS ? $this->__('Shipping Info') : $this->__('Info'); ?></th>
                <th><?php echo !$TotsyPLUS ? $this->__('Price') : $this->__('Price/Month'); ?></th>
                <th><?php echo $this->__('Qty') ?></th>
                <th><?php echo $this->__('Subtotal') ?></th>
            </tr>
            <?php if ($this->helper('tax')->displayCartBothPrices()): ?>
                <tr>
                    <th class="a-right"><?php echo $this->helper('tax')->getIncExcTaxLabel(false) ?></th>
                    <th><?php echo $this->helper('tax')->getIncExcTaxLabel(true) ?></th>
                    <th class="a-right"><?php echo $this->helper('tax')->getIncExcTaxLabel(false) ?></th>
                    <th><?php echo $this->helper('tax')->getIncExcTaxLabel(true) ?></th>
                </tr>
            <?php endif; ?>
        </thead>
        <tbody>
        <?php if($multiShipping):?>

        <?php foreach($fulfillmentTypes as $fulfillmentType => $items):?>

        <?php foreach($items as $key=>$itemId):?>
            <?php foreach($this->getItems() as $_item): ?>
                <?php if($_item->getId() == $itemId):?>
                    <?php echo $this->getItemHtml($_item) ?>
                    <?php endif;?>
                <?php endforeach ?>
            <?php endforeach;?>
        <?php endforeach;?>
        <?php else:?>
            <?php foreach($this->getItems() as $_item): ?>
                    <?php echo $this->getItemHtml($_item) ?>
                <?php endforeach ?>
        <?php endif;?>
        </tbody>
		<?php echo $this->getChildHtml('totals'); ?>	
    </table>
</div>

<div class="spinner" style="display: none;"><img src="<?php echo $this->getSkinUrl( 'images/ajax-loader.gif' ) ?>"></div>

<div id="checkout-review-submit">
    <div class="buttons-set" id="review-buttons-container">
        <p class="f-left"><?php echo $this->__('Forgot an Item?') ?> <a href="<?php echo $this->getUrl('checkout/cart') ?>"><?php echo $this->__('Edit Your Cart') ?></a></p>
        <?php echo $this->getChildHtml('button') ?>
    </div>
</div>
