<div class="well">
    <div class="page-title">
        <h4>Other Sales</h4>
        <hr />
    </div>
<?php
    $defaultTimezone = date_default_timezone_get();
    $mageTimezone = Mage::getStoreConfig(Mage_Core_Model_Locale::XML_PATH_DEFAULT_TIMEZONE);
    date_default_timezone_set($mageTimezone);
    $sortDate = now("Y-m-d");
    date_default_timezone_set($defaultTimezone);
    $storeId = Mage::app()->getStore()->getId();
    $sortentryLive = Mage::getModel('categoryevent/sortentry')->loadByDate($sortDate, $storeId, false)->getLiveQueue();
    $liveCategoryInfoArray = json_decode($sortentryLive, true);
    $i = 1;
?>
<ul class="thumbnails">
    <?php  foreach ($liveCategoryInfoArray as $liveCategory): ?>
    <li class="span2">
    <div class="thumbnail">
    <a href="<?php echo $this->getBaseUrl().$liveCategory['url_path']?>"><?php if(isset($liveCategory['image'])){
    //$containerProductInfo['small_image'] = $mediaBaseDir . str_ireplace('/', DS, $productInfo['small_image']);    //it call from file system like F:\www\totsy\media\catalog\product\n\e\newborn_tiered_dots_top_2pc_diaper_set.jpg
    if (($liveCategory['image'] == 'no_selection')||empty($liveCategory['image'])){
        $smallImage['image'] = Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).'catalog/product/placeholder/small_image.jpg';
        } else {
        $smallImage = Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).'catalog/category/'.$liveCategory['image'];
        }
        } else {
        $smallImage = "/skin/frontend/enterprise/bootstrap/images/catalog/product/placeholder/small_image.jpg";
        }
    ?>
    <img width="160px" height="120px" src="<?php echo $smallImage; ?>" /></a>
    <div class="caption">
        <h5><?php echo $liveCategory['name'] ?></h5>
    </div>
    </div>
    </li>
    <?php
        if ($i >= 6){
            break;
        }
            $i++;
    ?>
    <?php endforeach; ?>
</ul>
</div>