<style>
  .center {text-align: center; margin-left: auto; margin-right: auto; margin-bottom: auto; margin-top: auto;}
</style>
<title>Error 404</title>
<body>
  <div class="hero-unit center">
    <h1>Page Not Found! <small><font face="Tahoma" color="red">Error 404</font></small></h1>
    <br />
    <p>The page you requested could not be found, either contact <a href="http://totsy.custhelp.com" target="_blank"> Customer Service</a> or try again. 
    </p>
    <ul class="unstyled">
<li><a href="/">Home Page</a></li>
<li><a href="/pages/aboutus/">Learn more about Totsy</a></li>
<li><a href="http://totsy.custhelp.com/app/ask" target="_blank">Report a broken link</a></li>
</ul>

    <p><b>Or you could just press this neat little button:</b></p>
    <a href="#" class="btn btn-large btn-info"><i class="icon-home icon-white"></i> Take Me Home</a>
  </div>
  <br />
<div class="thumbnail">
  <center><h2>Perhaps you'd like one of these:</h2></center>
</div>
  <br />
  <div class="thumbnail span3 center">
    <h3>Try This...</h3>
    <p>write about your error page conent here and give some fool a good load of information or not</p>
    <div class="hero-unit">
      <img src="http://placehold.it/100x100"><!--Why Not Put a Picture To Celebrate Your 404-->
      <p></p>
    </div>
    <a href="#" class="btn btn-danger btn-large"><i class="icon-share icon-white"></i> Take Me There...</a>
  </div>
  <div class="thumbnail span3 center"> 
    <h3>Try This...</h3>
    <p>write about your error page conent here and give some fool a good load of information or not</p>
    <div class="hero-unit">
      <img src="http://placehold.it/100x100"><!--Why Not Put a Picture To Celebrate Your 404-->
      <p></p>
    </div>
    <a href="#" class="btn btn-danger btn-large"><i class="icon-share icon-white"></i> Take Me There...</a>
  </div>
      <div class="thumbnail span3 center">
    <h3>Try This...</h3>
    <p>write about your error page conent here and give some fool a good load of information or not</p>
    <div class="hero-unit">
      <img src="http://placehold.it/100x100"><!--Why Not Put a Picture To Celebrate Your 404-->
      <p></p>
    </div>
    <a href="#" class="btn btn-danger btn-large"><i class="icon-share icon-white"></i> Take Me There...</a>
  </div>
      <div class="thumbnail span3 center">
    <h3>Try This...</h3>
    <p>write about your error page conent here and give some fool a good load of information or not</p>
    <div class="hero-unit">
      <img src="http://placehold.it/100x100"><!--Why Not Put a Picture To Celebrate Your 404-->
      <p></p>
    </div>
    <a href="#" class="btn btn-danger btn-large"><i class="icon-share icon-white"></i> Take Me There...</a>
  </div>
  <br />
  <p></p>
  
    
  <!-- By ConnerT HTML & CSS Enthusiast -->  
  
  <div style="margin-top:40px;">
    <div class="page-title">
        <h4>Other Sales</h4>
        <hr />
    </div>
<?php
    $defaultTimezone = date_default_timezone_get();
    $mageTimezone = Mage::getStoreConfig(Mage_Core_Model_Locale::XML_PATH_DEFAULT_TIMEZONE);
    date_default_timezone_set($mageTimezone);
    date_default_timezone_set($defaultTimezone);
    $storeId = Mage::app()->getStore()->getId();
    $sortentryLive = Mage::getModel('categoryevent/sortentry')->loadCurrent()->getLiveQueue();
    $liveCategoryInfoArray = json_decode($sortentryLive, true);
    $i = 1;
?>
<ul class="thumbnails">
    <?php  foreach ($liveCategoryInfoArray as $liveCategory): ?>
    <?php if(!isset($liveCategory['club_only_event']) || !$liveCategory['club_only_event']) : ?>

        <li class="span3">
    <a href="<?php echo $this->getBaseUrl().$liveCategory['url_path']?>"><?php if(isset($liveCategory['image'])){
    //$containerProductInfo['small_image'] = $mediaBaseDir . str_ireplace('/', DS, $productInfo['small_image']);    //it call from file system like F:\www\totsy\media\catalog\product\n\e\newborn_tiered_dots_top_2pc_diaper_set.jpg
    if (($liveCategory['image'] == 'no_selection')||empty($liveCategory['image'])){
        $smallImage['image'] = Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).'catalog/product/placeholder/small_image.jpg';
        } else {
        $smallImage = Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).'catalog/category/'.$liveCategory['image'];
        }
        } else {
        $smallImage = "/skin/frontend/enterprise/bootstrap/images/catalog/product/placeholder/small_image.jpg";
        }
    ?>
    <img src="<?php echo $smallImage; ?>" /></a>
    <div class="caption">
        <h5><?php echo $liveCategory['name'] ?></h5>
    </div>
    </li>
    <?php
        if ($i >= 4){
            break;
        }
            $i++;
    ?>
    <?php endif; ?>
    <?php endforeach; ?>
</ul>
</div>