<?php
/**
 * Harapartners
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Harapartners License
 * that is bundled with this package in the file LICENSE_EE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.Harapartners.com/license
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@Harapartners.com so we can send you a copy immediately.
 *
 */
?>
<?php
/**
 * Catalog update ajax template
 * 'show more' block return
 * @see Mage_Catalog_Block_Catalog_ajax
 */
?>
<?php 
	$flag = Mage::getSingleton('customer/session')->getData('categoryevent_sort_update_selected_block');
	$eventArray = $this->loadUpdateSortCollection($flag);
?>
<?php foreach ($eventArray as $value):?>
	<?php
		if ($flag == 1 || $flag == 'live'){
			$timerSet = $this->setCountDownTimer($value['event_end_date']);
			$timerFlag = 'Ends in';
		}elseif ($flag == 2 || $flag == 'upcoming'){
			$timerSet = $this->setCountDownTimer($value['event_start_date']);
			$timerFlag = 'Opens in';
		}
		$timer = $timerSet['timer'];
		$endcount = $timerSet['endcount'];
	?>
	<div class="catalog-event ajax-event-<?php echo $flag;?>-display" style="display: none;">
		<?php $imgFile = BP.DS.'media'.DS.'catalog'.DS.'category'.DS.$value['thumbnail'];?>	
		<a class="event-link" href="<?php echo Mage::getBaseUrl().$value['url_path']; ?>"><img src="<?php echo Mage::helper('service/image')->loadImageFile($imgFile)->resize(228,263); ?>" width="228px" height="263px" alt="" /></a>
		<div class="splash-details">
			<div class="table-cell-left">	
				<p class="event-name"><?php echo $value['name'];?></p>
				<p id="time<?php echo $flag;?>-<?php echo $timer ?>"></p> 
				<script type="text/javascript">
					jQuery("#time<?php echo $flag;?>-<?php echo $timer ?>").countdown({
						//date: "12 10, 2011 16:11", //Counting TO a date
						date: "<?php echo $endcount; ?>", //Counting TO a date
						htmlTemplate: "<span><?php echo $timerFlag;?></span> %{d} <span class=\"cd-time\">Days</span> %{h}<span class=\"cd-time\">:</span>%{m}<span class=\"cd-time\">:</span>%{s}<span class=\"cd-time\"></span>",
		
						onChange: function( event, timer ){
						},
						onComplete: function( event ){										
							jQuery(this).html("Completed");
						},
						leadingZero: true,
						direction: "down"
					});
				</script>
			</div>
			<div class="table-cell-right">
				<a class="shop-button" href="<?php echo Mage::getBaseUrl().$value['url_path']; ?>">Shop</a>
			</div>
		</div>	
	</div>
<?php endforeach;?>