<?php
/**
 * Harapartners
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Harapartners License
 * that is bundled with this package in the file LICENSE_EE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.Harapartners.com/license
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@Harapartners.com so we can send you a copy immediately.
 *
 */
$sortDate = $this->getRequest()->getPost('sort_date');
$storeId = $this->getRequest()->getPost('sort_store');
$sortentry = $this->getSortentry();
$liveArray = json_decode($sortentry->getLiveQueue(), true);
$upcomingArray = json_decode($sortentry->getUpcomingQueue(), true);
?>
<div class="catalog-events-container">
	<div class="live-events-container">
		<p class="event-list-title"><?php echo Mage::helper('categoryevent')->__('All possible live events today') ?></p>
		<p>This list includes <strong>ALL</strong> events that are possibly live today, regardless of the hour when the event starts. Note this may be different from the content of "Today's Sales" in the frontend.</p>
		<p>"Today's Sales" is a filtered list of "All possible live events today", based on (1) whether the time (hour/minute/second) of the event passes the current time and (2) whether the event contains product.</p>
		<ul id="sortable" class="ui-sortable" >
		<?php foreach ( $liveArray as $live ):?>
			<li class="ui-state-default" id="recordsLiveArray_<?php echo $live['entity_id'];?>" >
				<?php
                    if (isset($live['thumbnail'])) {
                        $imgFile = BP.DS.'media'.DS.'catalog'.DS.'category'.DS.$live['thumbnail'];
                    } else {
                        $imgFile = BP.DS.'skin'.DS.'frontend'.DS.'enterprise'.DS.'harapartners'.DS.'images'.DS.'catalog'.DS.'product'.DS.'placeholder'.DS.'thumbnail.jpg';
                    }
                ?>
				<p class="event-name"><?php echo $live['name'] ?><time datetime="<?php echo date('Y-m-d H:i:s', strtotime($live['event_start_date'])) ?>"><?php echo date('Y-m-d H:i:s', strtotime($live['event_start_date'])) ?></time></p>
				<img src="<?php echo Mage::helper('service/image')->loadImageFile($imgFile)->resize(150,173); ?>" width="150px" height="173px" alt="" />
                <a href="<?php echo $this->getEventUrl($live)?>" target="_blank" class="event-control btn-ctrl-view"><img src="/skin/adminhtml/default/enterprise/images/btn_go.gif" width="11" height="12" alt="View (in new window)"/></a>
			</li>
		<?php endforeach; ?>
		</ul>
	</div>
	<div class="upcoming-events-container">
		<p class="event-list-title"><?php echo Mage::helper('categoryevent')->__('Events that starts next day (within ' . Harapartners_Categoryevent_Model_Sortentry::EVENT_CATEGORY_DATE_RANGE . ' days range )') ?></p>
		<p>This list contains <strong>ALL</strong> events that are opening soon. The content may also be different from the frontend "Upcoming Sales".</p>
		<p>"Upcoming Sales" contains a filtered list of "Events that starts next day", plus events in "All possible live events today" that are <strong>not live yet</strong>.</p>
		<ul id="sortable2" class="ui-sortable">
			<?php foreach ( $upcomingArray as $up ):?>
				<li class="ui-state-default" id="recordsUpArray_<?php echo $up['entity_id'];?>">
                    <?php
                    if (isset($up['thumbnail'])) {
                        $imgFile = BP.DS.'media'.DS.'catalog'.DS.'category'.DS.$up['thumbnail'];
                    } else {
                        $imgFile = BP.DS.'skin'.DS.'frontend'.DS.'enterprise'.DS.'harapartners'.DS.'images'.DS.'catalog'.DS.'product'.DS.'placeholder'.DS.'thumbnail.jpg';
                    }
                    ?>
                    <p class="event-name"><?php echo $up['name'] ?><time datetime="<?php echo date('Y-m-d H:i:s', strtotime($up['event_start_date'])) ?>"><?php echo date('Y-m-d H:i:s', strtotime($up['event_start_date'])) ?></time></p>
                    <img src="<?php echo Mage::helper('service/image')->loadImageFile($imgFile)->resize(150,173); ?>" width="150px" height="173px" alt="" />
                    <a href="<?php echo $this->getEventUrl($up)?>" target="_blank" class="event-control btn-ctrl-view"><img src="/skin/adminhtml/default/enterprise/images/btn_go.gif" width="11" height="12" alt="View (in new window)"/></a>
				</li>
			<?php endforeach; ?>
		</ul>
	</div>
</div>

<script>

	var liveorder = 0;
	var uporder = 0;
	var sortdate = '<?php echo $sortDate; ?>';
	var storeid = '<?php echo $storeId; ?>';

	jQuery(function() {
		jQuery( "#sortable" ).sortable({
				update: function(){
					liveorder = jQuery(this).sortable("serialize");
				}
			});
		jQuery( "#sortable" ).disableSelection();
	});

	jQuery(function() {
		jQuery( "#sortable2" ).sortable({
				update: function(){
					uporder = jQuery(this).sortable("serialize");
				}
			});
		jQuery( "#sortable2" ).disableSelection();
	});

    function saveOrderSubmit(){
        var sortformkey = '<?php echo $this->getFormKey(); ?>';

        var result = new Ajax.Request("<?php echo $this->getSortSavePostUrl(); ?>", {
            parameters: "sortdate="+sortdate+"&storeid="+storeid+"&"+liveorder+"&"+uporder+"&form_key="+sortformkey,
            onSuccess: function() {
                alert("Sort order saved.");
            }
        });
    }

    function rebuildSubmit(){
        var sortformkey = '<?php echo $this->getFormKey(); ?>';

        var result = new Ajax.Request("<?php echo $this->getSortRebuildPostUrl(); ?>", {
            parameters: "sortdate="+sortdate+"&storeid="+storeid+"&"+liveorder+"&"+uporder+"&form_key="+sortformkey,
            onSuccess: function() {
                alert("Sort order has been rebuilt.");
                jQuery("#sort-type-submit").click();
            }
        });
    }

	function changeOrder(events) {
		events.sort(function(left,right){
			leftid = jQuery(left).attr('id');
			leftid = leftid.substr(17);
			leftid_pos = liveids.indexOf(leftid);

			rightid = jQuery(right).attr('id');
			rightid = rightid.substr(17);
			rightid_pos = liveids.indexOf(rightid);
			return (leftid_pos < rightid_pos) ? -1 : (leftid_pos > rightid_pos)? 1 : 0;
		});

		return events;
	}
</script>
<style type="text/css">
    .ui-sortable {
    }
    .ui-sortable > li {
        width: 150px;
        position: relative;
        padding: 4px;
        margin: 8px;
        border: solid 1px #ccc;
        cursor: move;
    }
    .ui-sortable .event-name {
        height: 50px;
    }
    .ui-sortable > li time {
        display: block;
        color: #666;
        font-size: smaller;
        font-weight: normal;
    }
    .ui-sortable > li > .event-control {
        position: absolute;
        display: none;
    }
    .ui-sortable > li:hover > .event-control {
        display: block;
    }
    .ui-sortable > li > .btn-ctrl-view {
        top: 4px;
        right: 4px;
    }
</style>