<div class="form-list .one-page-payment">
<?php $customerId = Mage::getSingleton('customer/session')->getCustomerId(); ?>
<?php if ($this->getProfilesByCustomerId( $customerId )) { ?>
<?php $profiles = $this->getProfilesByCustomerId( $customerId ) ?>
<?php
    $profilesCounter = 0;
    foreach( $profiles as $profile ) {
        if($profile->getSubscriptionId() && $profile->getIsDefault()==0 && $profile->getData('saved_by_customer')) {
            $profilesCounter++;
        }
    }

    $hasProfile = false;

    if ($profilesCounter > 0 ) {
        $hasProfile = true;
    } else {
        $hasProfile = false;
    }
?>
<?php } ?>
        <?php if($profiles && $profilesCounter > 0 ) { ?>
                <div class="pull-left" id="use-card-method">
                    <div id="cybersource-use-card-method ">
                    <table class="saved_card">
                    	<tr>
                        	<th></th>
                        	<th></th>
                        	<th>Name on card</th>
                        	<th>Billing address</th>
                        	<th>Expires</th>
                        </tr>
                    <?php foreach( $profiles as $profile ): ?>
                        <?php 
                            $checked = '';
                            $customerObj = Mage::getSingleton('customer/customer')->load($profile->getCustomerId());
                            $customerAddress = Mage::getSingleton('customer/address')->load($profile->getAddressId());
                            
                            $customerName = $customerAddress->getFirstname() ." ". $customerAddress->getLastname();
                            
                            //reset gets the first item from the array passed in
                            $customerStreetArray = $customerAddress->getStreet();
                            $customerStreet = reset($customerStreetArray);
                            
                            $orders = Mage::getResourceModel('sales/order_collection')->addFieldToSelect('*')
    ->addFieldToFilter('customer_id', $profile->getCustomerId())->addAttributeToSort('created_at', 'DESC')->setPageSize(1);
    
    						//checking the users last used, saved to expedite checkout
                            //comparing cybersource profile id to id of card used in last order placed
                            if($orders->getFirstItem()->getPayment()) {
                            	if($orders->getFirstItem()->getPayment()->getData('cybersource_subid')==$profile->getSubscriptionId()) {
                                	$checked = 'checked';
                            	}
                            } 
                        ?>
                        
                        <script type="text/javascript">
                        jQuery(document).ready( function() {
                            checkoutPayment.lastUsedAddressId = "<?php echo $profile->getAddressId(); ?>"; 
                        });
                        </script>
                        <?php if(!$profile->getSubscriptionId() || $profile->getIsDefault()== 1 || !$profile->getData('saved_by_customer')) { continue; } ?>
                        <tr>
                        	<td>
                                <input type="radio" checked="<?php echo $checked; ?>" name="payment[cybersource_subid]" id="payment[cybersource_subid]" class="use-saved-card-control pull-left" value="<?php echo $profile->getEncryptedSubscriptionId() ?>">
                                    <span class="cc">
        		 	                    <span title="<?php echo $this->getFullCcCardType( $profile->getData( 'card_type' )); ?>" class="<?php echo strtolower($profile->getData('card_type')); ?>" >
        		 	                    </span>
        		 	                </span>
        		 	         </td>
                            <td class="card-type">
                            <strong><?php echo $this->getFullCcCardType( $profile->getData( 'card_type' )); ?></strong> ending in <?php echo $profile->getLast4no() ?></td>
                            <td class="card-name"><?php echo $customerName ?></td>
                            <td class="billing-address"><?php echo $customerStreet; ?></td>
                            <td class="card-expdate"><?php echo $profile->getExpireMonth()."/".$profile->getExpireYear() ?>
                            </td>
                        </tr>
                    <?php endforeach ?>
						</table>
                    </div>
                </div> 
                <?php } ?>
                <div>
                     <?php foreach( $profiles as $profile ): ?>
                        <?php if( !$profile->getSubscriptionId() || $profile->getIsDefault()== 1 ) { continue; } ?>
                        <input type="hidden" id="address_<?php echo $profile->getEncryptedSubscriptionId() ?>" value="<?php echo $profile->getData('address_id') ?>" />
                    <?php endforeach ?>
                </div>
</div>