<?php $_code=$this->getMethodCode();
$hasVirtual = false;
// Check to see if there are multiple fulfillment types
foreach($this->getQuote()->getAllItems() as $item) {
    if($item->getParentItemId()) {
        continue;
    }
    $product = Mage::getModel ( 'catalog/product' )->load ( $item->getProductId () );
    if($product->getIsVirtual() && $product->getFulfillmentType() !== 'nominal') {
        $_fulfillmentType = 'virtual';
        $hasVirtual = true;
    } else {
        $_fulfillmentType = $product->getFulfillmentType();
    }
    $fulfillmentTypes [$_fulfillmentType] [] = $item->getId ();
}

$multiShipping = FALSE;
if(count($fulfillmentTypes) > 1) {
    $multiShipping = TRUE;
}
?>

<div class="form-list one-page-payment" id="payment_form_<?php echo $_code ?>">
<?php $customerId = Mage::getSingleton('customer/session')->getCustomerId(); ?>
<?php $profiles = $this->getProfilesByCustomerId( $customerId ) ?>
<?php
    $profilesCounter = 0;
    foreach( $profiles as $profile ) {
        if($profile->getSubscriptionId() && $profile->getIsDefault()==0 && $profile->getData('saved_by_customer')) { 
            $profilesCounter++;
        }
    }
    
    $hasProfile = false;
    
    if ($profilesCounter > 0 ) { 
        $hasProfile = true; 
    } else { 
        $hasProfile = false; 
    }
    
?>
<div>
    <div>   
        <div style="clear:both"></div>
        <?php if($profiles && $profilesCounter > 0 ) { ?>
                <div class="pull-left" id="use-card-method">
                    <div id="cybersource-use-card-method ">
                    <table class="saved_card"
                    	<tr>
                        	<th></th>
                        	<th></th>
                        	<th>Name on card</th>
                        	<th>Billing address</th>
                        	<th>Expires</th>
                        </tr>
                    <?php foreach( $profiles as $profile ): ?>
                        <?php 
                            $checked = '';
                            $customerObj = Mage::getSingleton('customer/customer')->load($profile->getCustomerId());
                            $customerAddress = Mage::getSingleton('customer/address')->load($profile->getAddressId());
                            $lastCardUsed = Mage::helper('palorus')->getLastCardUsed();
                            $customerName = $customerAddress->getFirstname() ." ". $customerAddress->getLastname();
                            
                            //reset gets the first item from the array passed in
                            $customerStreetArray = $customerAddress->getStreet();
                            $customerStreet = reset($customerStreetArray);
                        ?>
                        
                        <script type="text/javascript">
                            jQuery(document).ready( function() {
                                checkoutPayment.hasProfile = "<?php echo $hasProfile; ?>"; 
                                
                                if(checkoutPayment.hasProfile==1){
                                    hasCBProfile = true;
                                }
                                
                                checkoutPayment.lastUsedAddressId = "<?php echo $profile->getAddressId(); ?>"; 
                            });
                        </script>
                        <?php if(!$profile->getSubscriptionId() || $profile->getIsDefault()== 1 || !$profile->getData('saved_by_customer')) { continue; } ?>
                        <tr>
                        	<td>
                                <input type="radio" <?php if($lastCardUsed && ($lastCardUsed->getSubscriptionId()==$profile->getSubscriptionId())) echo 'checked'; ?> name="payment[cybersource_subid]" id="payment[cybersource_subid]" data-billing-address-id="<?php echo $profile->address_id; ?>" class="use-saved-card-control pull-left" value="<?php echo $profile->getEncryptedSubscriptionId() ?>">
                                    <span class="cc">
        		 	                    <span title="<?php echo $this->getFullCcCardType( $profile->getData( 'card_type' )); ?>" class="<?php echo strtolower($profile->getData('card_type')); ?>" >
        		 	                    </span>
        		 	                </span>
        		 	         </td>
                            <td class="card-type">
                            <strong></strong> ending in <?php echo $profile->getLast4no() ?></td>
                            <td class="card-name"><?php echo $customerName ?></td>
                            <td class="billing-address"><?php echo $customerStreet; ?></td>
                            <td class="card-expdate"><?php echo $profile->getExpireMonth()."/".$profile->getExpireYear() ?>
                            </td>
                        </tr>
                    <?php endforeach ?>
						</table>
                    </div>
                </div> 
                <?php } ?>
                <div>
                     <?php foreach( $profiles as $profile ): ?>
                        <?php if( !$profile->getSubscriptionId() || $profile->getIsDefault()== 1 ) { continue; } ?>
                        <input type="hidden" id="address_<?php echo $profile->getEncryptedSubscriptionId() ?>" value="<?php echo $profile->getData('address_id') ?>" />
                    <?php endforeach ?>
                </div>
    </div>
</div>
<div style="clear:both"></div>