<?php
    $baseurl = Mage::getUrl('',array('_forced_secure'=>true));
    $customer = Mage::getSingleton('customer/session')->getCustomer();
    $id = $customer->getId(); 
    $paymentCollection = Mage::getModel('paymentfactory/profile')->loadByCustomerId($id);
    $creditCardsCount = 0;
?>
<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<?php if($creditCardsCount == 0): ?>

sdfsadasdasd

<?php endif; ?>
<div class="page-header">
    <h2><?php echo $this->__('Manage Credit Cards') ?> <img class="cart-type pull-right"  width="180px;" src="<?php echo $this->getSkinUrl('images/creditcards.jpg')?>"/></h2>
</div>

<div class="well">
<div class="page-title">
    <h4>My Credit Cards <button class="add-new-card-button btn btn-primary pull-right">Add New Card</button>
        <button class="add-new-card-close btn pull-right add-new-card-form" style="display:none;">Close</button>
    </h4>
    <hr />
    <div class="add-new-card">
    <?php if($creditCardsCount == 0): ?>
    <h3>Sorry, You don't have any credit cards on file with Totsy.</h3>
    <p><span class="label label-info">NOTE:</span> Adding a credit card helps speed up the checkout process.</p>
    <?php endif; ?>
        <script type="text/javascript">
            jQuery(document).ready(function(){
                jQuery(".add-new-card-button").click( function() {
                    jQuery(".add-new-card-form").fadeIn();
                    jQuery(this).hide();
                });
                jQuery(".add-new-card-close").click( function() {
                    jQuery(".add-new-card-form").fadeOut();
                    jQuery(".add-new-card-button").show();
                });
            })
        </script>
        <div class="add-new-card-form" style="display:none;">
        <hr />
        <h4>Add New Credit Card</h4>
            <?php echo $this->getChildHtml('credit_cards_form');?>
    </div>
</div>
<div class="cards-info">
    <?php foreach($paymentCollection as $payment):
            $type = $payment->getData('card_type');
            switch ($type) {
                case "VI":
                    $creditCardImage = 'cc_visa.gif';
                    $cardType = 'Visa';
                    break;
                case "MC":
                    $creditCardImage = 'cc_mastercard.gif';
                    $cardType = 'Master Card';
                    break;
                case "AE":
                    $creditCardImage = 'cc_amex.gif';
                    $cardType = 'American Express';
                    break;
                case "DI":
                    $creditCardImage = 'cc_discover.gif';
                    $cardType = 'Discover';
                    break;
            }
    ?>
    <?php if($payment->getIsDefault()== 0 && $payment->getData('saved_by_customer')):?>
    <?php $creditCardsCount++; ?>

        <table class="table table-striped table-bordered">
            <tr>
                <td>
                <img src="<?php echo $this->getSkinUrl('images/' . $creditCardImage)?>"> 
                </td>            
                <td width="71%">
                    <?php echo $cardType?> ending in <strong><?php echo $payment->getData('last4no')?></strong>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                    expires <strong><?php echo $payment->getData('expire_month');?>/<?php echo $payment->getData('expire_year');?></strong>
                </td>
                <td width="2%">
                    <a href="<?php echo $baseurl ?>paymentfactory/index/delete/?entity_id=<?php echo $payment->getData('entity_id');?>" id="remove_<?php echo $payment->getData('entity_id');?>" title="Remove Credit Card" class="delete-new-card-button btn">Delete</a>
                </td>
            </tr>
            <?php if($payment->getData('address_id')):?>
                <?php $address_id = $payment->getData('address_id'); ?>
                <?php if($this->getAddress($address_id)->getFirstname()):?>
             <tr>
                <td width="10%" align="left"></td>
                <td width="90%">
                    <table class="table table-condensed">
                        <tr>
                            <td width="141" valign="top">Cardholder Name:</td>
                            <td width="281"><?php echo $this->htmlEscape($this->getAddress($address_id)->getFirstname()); ?> <?php echo $this->htmlEscape($this->getAddress($address_id)->getLastname()); ?></td>
                        </tr>
                        <tr>
                            <td valign="top">Billing Address:</td>
                            <td><?php echo $this->htmlEscape($this->getAddress($address_id)->getStreet(1)); ?>
                                <?php if($this->getAddress($address_id)->getStreet(1)): ?>
                                    <?php echo $this->htmlEscape($this->getAddress($address_id)->getStreet(2)); ?><br />
                                <?php endif ?>
                                <?php echo $this->htmlEscape($this->getAddress($address_id)->getCity()); ?>, <?php echo $this->htmlEscape($this->getAddress($address_id)->getRegion()); ?> <?php echo $this->htmlEscape($this->getAddress($address_id)->getPostcode()); ?>
                            </td>
                        </tr>
                    </table>
                </td>
            </tr>
                <?php endif; ?>
            <?php endif; ?>
        </table>
<?php endif;?>
<?php endforeach;?>
</div>
<div class="clear"></div>
</div>