<?php if($messageData = $this->getMessageData()): ?>
    <div class="page-head">
        <h3><?php echo $this->__('Message Details') ?></h3>
    </div>
    <div class="wsalogger-detail">
    	<p><strong><?php echo $this->__('Code:') ?></strong> <?php echo $messageData->getCode(); ?></p>    
	    <p><strong><?php echo $this->__('Severity:') ?></strong> <?php echo $messageData->getSeverity(); ?></p>
	    <p><strong><?php echo $this->__('Date Added:') ?></strong> <?php echo $messageData->getDateAdded(); ?></p>
	    <p><strong><?php echo $this->__('Title:') ?></strong> <?php echo $messageData->getTitle(); ?></p>
	    <p><strong><?php echo $this->__('Message:') ?></strong></p>
	    <div style='width:100%; word-wrap: break-word;'>
	    	<?php echo '<pre>'.htmlentities($messageData->getDescription()).'</pre>'; ?>
	    </div>	      
    </div>
    <br />
    <div class="button-set"><a href="<?php echo $this->getBackUrl() ?>" class="left">&laquo; <?php echo $this->__('Back to WebShopApps Log') ?></a></div><br />
<?php endif; ?>
