<?php
/**
 * Harapartners
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Harapartners License
 * that is bundled with this package in the file LICENSE_EE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.Harapartners.com/license
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@Harapartners.com so we can send you a copy immediately.
 *
 * 
 */

?>
<hr />
<form action="<?php echo $this->getBaseUrl();?>paymentfactory/index/create/" method="post" id="hpcheckout-billing-form" >
<?php $_code='paymentfactory_tokenize'; ?>
    <div id="card-info">
        <script type="text/javascript">
        //<![CDATA[
            Validation.creditCartTypes.set('JCB', [new RegExp('^(35[0-9]{14}|(2131|1800)[0-9]{11})$'), new RegExp('^([0-9]{3})?$'), true]);
            Validation.creditCartTypes.set('LASER', [new RegExp('^((6304|6706|6771|6709)[0-9]{12}([0-9]{3}))$'), new RegExp('^([0-9]{3})?$'), false]);
            Validation.creditCartTypes.set('UATP', [false, new RegExp('^[0-9]{3}([0-9]{1})?$'), false]);
            Validation.creditCartTypes.set('MCI', [false, new RegExp('^[0-9]{3}([0-9]{1})?$'), false]);
        //]]>
        </script>
        <div id="payment_form_paymentfactory_tokenize" class="form-list" style="">

                <label class="required" for="paymentfactory_tokenize_cc_type"><em>*</em><?php echo $this->__('Card Type');?></label>
                
                <div class="input-box">
                    <div class="totsy-selective-input-box middle-length">
                        <select id="paymentfactory_tokenize_cc_type" class="required-entry validate-cybsersource-cc-type-select" name="payment[cc_type]">
                            <option value="AE"><?php echo $this->__('American Express');?></option>
                            <option value="VI"><?php echo $this->__('Visa');?></option>
                            <option value="MC"><?php echo $this->__('MasterCard');?></option>
                            <option value="DI"><?php echo $this->__('Discover');?></option>
                        </select>
                    <span><?php echo $this->__('American Express');?></span>
                    </div>
                </div>

                <label class="required" for="paymentfactory_tokenize_cc_number"><em>*</em><?php echo $this->__('Card Number');?></label>
                <div class="input-box">
                    <input id="paymentfactory_tokenize_cc_number" class="input-text validate-cc-number validate-cc-type" type="text" value="" title="Credit Card Number" name="payment[cc_number]">
                </div>

                <label class="required" for="paymentfactory_tokenize_expiration"><em>*</em><?php echo $this->__('Expiration Date');?></label>
                <div class="input-box">
                    <div class="v-fix right-margin">
                        <div class="totsy-selective-input-box short-length span2">
                            <span>Month</span>
                            <select id="paymentfactory_tokenize_expiration" class="month validate-cc-exp required-entry span2" name="payment[cc_exp_month]">
                                <option selected="selected" value="">Month</option>
                                <option value="1">01 - January</option>
                                <option value="2">02 - February</option>
                                <option value="3">03 - March</option>
                                <option value="4">04 - April</option>
                                <option value="5">05 - May</option>
                                <option value="6">06 - June</option>
                                <option value="7">07 - July</option>
                                <option value="8">08 - August</option>
                                <option value="9">09 - September</option>
                                <option value="10">10 - October</option>
                                <option value="11">11 - November</option>
                                <option value="12">12 - December</option>
                            </select>
                        </div>
                    </div>
                    <div class="v-fix">
                        <div class="totsy-selective-input-box short-length span2">
                            <span>Year</span>
                            <select id="paymentfactory_tokenize_expiration_yr" class="year required-entry span2" name="payment[cc_exp_year]">
                                <option selected="selected" value="">Year</option>
                                <option value="2012">2012</option>
                                <option value="2013">2013</option>
                                <option value="2014">2014</option>
                                <option value="2015">2015</option>
                                <option value="2016">2016</option>
                                <option value="2017">2017</option>
                                <option value="2018">2018</option>
                                <option value="2019">2019</option>
                                <option value="2020">2020</option>
                                <option value="2021">2021</option>
                                <option value="2022">2022</option>
                            </select>
                        </div>
                    </div>
                </div>
                
                <div class="span2">
                <label class="required" for="paymentfactory_tokenize_cc_cid"><em>*</em><?php echo $this->__('Security Code');?></label>
                <div class="input-box">
                    <div class="v-fix">
                        <input id="paymentfactory_tokenize_cc_cid" class="input-text cvv required-entry validate-cc-cvn" type="text" value="" name="payment[cc_cid]" title="Card Verification Number">
                    </div>
                </div>
                <div>
                     <input type="hidden" value="1" name="payment[saved_by_customer]" id="<?php echo $_code ?>_saved">
                </div>
                </div>

    </div>
    
    <div id="billing-info" class="span8">
        <p class="billing-addr-title"><?php echo $this->__('Billing Address');?></p>
            <label for="billing:firstname" class="required"><em>*</em><?php echo $this->__('First Name') ?></label>
            <input type="text" name="billing[firstname]" title="<?php echo $this->__('First Name') ?>" class="input-text required-entry" value="<?php //echo $this->htmlEscape($this->getFirstname()) ?>" id="billing:firstname" />
            <label for="billing:lastname" class="required"><em>*</em><?php echo $this->__('Last Name') ?></label>
            <input type="text" name="billing[lastname]" title="<?php echo $this->__('Last Name') ?>" class="input-text required-entry" value="<?php //echo $this->htmlEscape($this->getLastname()) ?>" id="billing:lastname" />
            <label for="billing:telephone" class="required"><em>*</em><?php echo $this->__('Telephone') ?></label>
            <input type="text" name="billing[telephone]" title="<?php echo $this->__('Telephone') ?>" class="input-text required-entry validate-phoneLax" id="billing:telephone" value="<?php //echo $this->htmlEscape($this->getAddress()->getTelephone()) ?>" onkeyup="backspacerUP(this,event);" onkeydown="backspacerDOWN(this,event);"/>
            <label for="billing:street1" class="required"><em>*</em><?php echo $this->__('Street Address 1') ?></label>
            <input type="text" title="<?php echo $this->__('Street Address Line 1') ?>" name="billing[street][0]" id="billing:street1" value="<?php //echo $this->htmlEscape($this->getAddress()->getStreet(1)) ?>" class="input-text required-entry" />
            <label for="billing:street2">&nbsp;&nbsp;<?php echo $this->__('Street Address 2') ?></label>
            <input type="text" title="<?php echo $this->__('Street Address Line 2') ?>" name="billing[street][1]" id="billing:street2" value="<?php //echo $this->htmlEscape($this->getAddress()->getStreet(2)) ?>" class="input-text" />
            <label for="billing:city" class="required"><em>*</em><?php echo $this->__('City') ?></label>
            <input type="text" title="<?php echo $this->__('City') ?>" name="billing[city]" class="input-text required-entry" value="<?php //echo $this->htmlEscape($this->getAddress()->getCity()) ?>" id="billing:city" />
            <label for="region_id" class="required"><em>*</em><?php echo $this->__('State/Province') ?></label>
            <span>State</span>
            <select id="billing:region_id" name="billing[region_id]" title="<?php echo $this->__('State/Province') ?>" class="validate-select">
                <option value="">Please select region, state or province</option>
                <?php foreach($this->getRegions() as $region) {
                    echo '<option value="'.$region->getId().'" >'.$region->getName().'</option>';
            } ?>
            </select>
            <input type="hidden" title="<?php echo $this->__('State/Province') ?>" name="billing[region]" id="billing:region" />
            <label for="billing:postcode" class="required"><em>*</em><?php echo $this->__('Zip/Postal Code') ?></label>
            <input type="text" title="<?php echo $this->__('Zip/Postal Code') ?>" name="billing[postcode]" id="billing:postcode" class="input-text validate-zip-international required-entry" value="<?php //echo $this->htmlEscape($this->getAddress()->getPostcode()) ?>" />
           <label for="billing:country_id" class="required"><em>*</em><?php echo $this->__('Country') ?></label>
           <span>Country</span>
           <select id="billing:country_id" name="billing[country_id]" title="<?php echo $this->__('Country') ?>" class="validate-select">
           <option value="US">United States</option>
           </select>
           <button class="button general top btn btn-primary" type="submit"><?php echo $this->__('Submit');?></button>
</form>
</div>
</div></div>
<script type="text/javascript">

    var paymentForm = new VarienForm( 'hpcheckout-billing-form' );

    jQuery( document ).ready( function() {
        updateSelectText();
        jQuery('.totsy-selective-input-box select').bind( 'change', updateSelectText );
    }); 
    
    function updateSelectText(){
        jQuery(".totsy-selective-input-box select").each(function(){
            var temphtml = jQuery(this).html();
            var text = jQuery(this).find("option:selected").text();
            var value = jQuery(this).find("option:selected").val();
            if (value==''){
                text = jQuery(this).find("option[selected='true']").text();
                if (text=='') {
                    text = jQuery(this).find("option[value='']").text();
                }
            }
            jQuery(this).parent('div').children('span').html(text);
        });
    };
    jQuery('#hpcheckout-billing-form').submit(function() {
        jQuery("#billing\\:region").val(jQuery("select#billing\\:region_id :selected").text());
        return true;
    });
</script>