<?php
$_product = Mage::registry('current_product');
$_category = Mage::registry('current_category');

if($_product && $_category && $_product->getId() && $_category->getId()){
?>
<!-- Social Labs BEGIN -->
<div id="sociable_product_pixel"></div>
<script type="text/javascript">
    var socialableLabsOutput = false;
    Event.observe(window,'load',function() {
        new Ajax.Updater({success:'sociable_product_pixel'}, '<?php echo Mage::getUrl('pixels/sociable/product'
            , array('product'=>$_product->getId(),'category'=>$_category->getId())); ?>'
            , {method:'get',evalScripts: true});
    });
</script>
<!-- Social Labs END -->
<?php } ?>
